# Generated by Django 5.2.7 on 2025-12-29 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documentofirmado_firma_auditoriafirmas_and_more'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='documentos',
        ),
        migrations.CreateModel(
            name='DocumentoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, help_text='Nota o descripción del documento en este proyecto', max_length=200)),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_vinculados', to='documentos.documento')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_proyecto', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Documento del Proyecto',
                'verbose_name_plural': 'Documentos del Proyecto',
                'unique_together': {('proyecto', 'documento')},
            },
        ),
    ]
