# Generated by Django 5.2.7 on 2025-12-29 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0023_pinplano_actividad'),
        ('proyectos', '0002_add_documento_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='visor',
            field=models.ForeignKey(blank=True, help_text='Visor de plano para ubicar actividades del proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='activos.visorplano'),
        ),
    ]
