# Generated by Django 5.2.7 on 2025-12-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0023_pinplano_actividad'),
        ('proyectos', '0003_add_visor_to_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='visor',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='visores',
            field=models.ManyToManyField(blank=True, help_text='Visores de plano para ubicar actividades del proyecto', related_name='proyectos', to='activos.visorplano'),
        ),
    ]
