# Generated by Django 5.2.7 on 2025-12-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_remove_proyecto_visor_proyecto_visores'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='nota',
            field=models.TextField(blank=True, help_text='Notas internas del proyecto'),
        ),
    ]
