# Generated by Django 5.2.7 on 2026-01-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_proyecto_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único del proyecto (se genera automáticamente si se deja vacío, formato: PROY-YYYY-NNNN)', max_length=50, unique=True),
        ),
    ]
