# Generated by Django 5.2.7 on 2026-01-06 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_alter_proyecto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='predecesora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucesoras', to='proyectos.actividad', verbose_name='Actividad Predecesora'),
        ),
    ]
