# Generated by Django 5.2.12 on 2026-04-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_actividad_predecesora'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='porcentaje_avance',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de avance (0-100)'),
        ),
    ]
