# Generated by Django 5.2.12 on 2026-04-15 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_actividad_porcentaje_avance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='proyectos.carpetaproyecto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Carpeta de Proyecto',
                'verbose_name_plural': 'Carpetas de Proyecto',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='documentoproyecto',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='proyectos.carpetaproyecto'),
        ),
    ]
