# Generated by Django 5.2.12 on 2026-04-15 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0031_carpeta_documento_carpeta'),
        ('proyectos', '0009_carpetaproyecto_documentoproyecto_carpeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoproyecto',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_proyectos', to='documentos.carpeta'),
        ),
        migrations.DeleteModel(
            name='CarpetaProyecto',
        ),
    ]
