# Generated by Django 5.2.12 on 2026-06-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0082_ordentrabajo_proyecto'),
        ('proyectos', '0010_alter_documentoproyecto_carpeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='ordenes_trabajo',
            field=models.ManyToManyField(blank=True, related_name='actividades_proyecto', to='mantenimiento.ordentrabajo', verbose_name='Órdenes de Trabajo'),
        ),
    ]
