# Generated by Django 6.0.6 on 2026-07-02 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_actividad_ordenes_trabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En Proceso'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20, verbose_name='Estado')),
                ('fecha_observacion', models.DateField(verbose_name='Fecha de observación')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='proyectos.documentoproyecto', verbose_name='Documento del proyecto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='proyectos.proyecto', verbose_name='Proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_proyecto', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Observación de Proyecto',
                'verbose_name_plural': 'Observaciones de Proyecto',
                'ordering': ['-fecha_observacion'],
            },
        ),
    ]
