# Generated by Django 5.2.12 on 2026-07-10 01:30

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_planoproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinObservacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenada_x', models.FloatField(help_text='Posición X en píxeles absolutos del viewport base')),
                ('coordenada_y', models.FloatField(help_text='Posición Y en píxeles absolutos del viewport base')),
                ('pagina', models.PositiveIntegerField(default=1)),
                ('color', colorfield.fields.ColorField(default='#EF4444', image_field=None, max_length=25, samples=None)),
                ('nota', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pines_plano', to='proyectos.observacionproyecto')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pines_observacion', to='proyectos.planoproyecto')),
            ],
            options={
                'verbose_name': 'Pin de Observación en Proyecto',
                'verbose_name_plural': 'Pines de Observación en Proyecto',
                'unique_together': {('plano', 'observacion')},
            },
        ),
    ]
