# Generated by Django 5.2.12 on 2026-07-10 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_pinobservacionproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacionproyecto',
            name='documento_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='proyectos.documentoproyecto', verbose_name='Documento del proyecto'),
        ),
    ]
