# Generated by Django 5.2.12 on 2026-07-10 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0015_observacion_documento_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPinObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos/fotos_pines/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='proyectos.pinobservacionproyecto')),
            ],
            options={
                'verbose_name': 'Foto de Pin de Observación',
                'verbose_name_plural': 'Fotos de Pin de Observación',
                'ordering': ['creado_en'],
            },
        ),
    ]
