# Generated by Django 5.2.12 on 2026-07-10 17:32

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0016_foto_pin_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPlanoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', colorfield.fields.ColorField(default='#3B82F6', image_field=None, max_length=25, samples=None)),
                ('x1', models.FloatField(help_text='X esquina superior izquierda (viewport base)')),
                ('y1', models.FloatField(help_text='Y esquina superior izquierda (viewport base)')),
                ('x2', models.FloatField(help_text='X esquina inferior derecha (viewport base)')),
                ('y2', models.FloatField(help_text='Y esquina inferior derecha (viewport base)')),
                ('pagina', models.PositiveIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='proyectos.planoproyecto')),
            ],
            options={
                'verbose_name': 'Área de Plano de Proyecto',
                'verbose_name_plural': 'Áreas de Plano de Proyecto',
                'ordering': ['creado_en'],
            },
        ),
    ]
