# Generated by Django 6.0.6 on 2026-07-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_area_plano_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaplanoproyecto',
            name='x1',
            field=models.FloatField(help_text='X esquina superior izquierda (puntos PDF intrínsecos, scale=1)'),
        ),
        migrations.AlterField(
            model_name='areaplanoproyecto',
            name='x2',
            field=models.FloatField(help_text='X esquina inferior derecha (puntos PDF intrínsecos, scale=1)'),
        ),
        migrations.AlterField(
            model_name='areaplanoproyecto',
            name='y1',
            field=models.FloatField(help_text='Y esquina superior izquierda (puntos PDF intrínsecos, scale=1)'),
        ),
        migrations.AlterField(
            model_name='areaplanoproyecto',
            name='y2',
            field=models.FloatField(help_text='Y esquina inferior derecha (puntos PDF intrínsecos, scale=1)'),
        ),
        migrations.AlterField(
            model_name='pinobservacionproyecto',
            name='coordenada_x',
            field=models.FloatField(help_text='Posición X en puntos PDF intrínsecos (viewport scale=1)'),
        ),
        migrations.AlterField(
            model_name='pinobservacionproyecto',
            name='coordenada_y',
            field=models.FloatField(help_text='Posición Y en puntos PDF intrínsecos (viewport scale=1)'),
        ),
    ]
