# Generated by Django 6.0.6 on 2026-07-21 16:16

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0069_itemcotizacion_aprobado_itemcotizacion_aprobado_en'),
        ('proyectos', '0018_update_coordinate_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del elemento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_ejecucion_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio ejecución')),
                ('fecha_ejecucion_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin ejecución')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Cantidad')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('item_cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_proyecto', to='presupuestos.itemcotizacion', verbose_name='Item de Cotización')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Elemento de Proyecto',
                'verbose_name_plural': 'Elementos del Proyecto',
                'ordering': ['orden', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ElementoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, storage=core.storage.MinIOStorage(), upload_to='proyectos/elementos/', verbose_name='Archivo / Foto')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('FOTO', 'Foto'), ('DOCUMENTO', 'Documento'), ('OTRO', 'Otro')], default='FOTO', max_length=20, verbose_name='Tipo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='proyectos.elementoproyecto', verbose_name='Elemento')),
            ],
            options={
                'verbose_name': 'Documento de Elemento',
                'verbose_name_plural': 'Documentos del Elemento',
                'ordering': ['-creado_en'],
            },
        ),
    ]
