# Generated by Django 6.0.6 on 2026-07-21 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0035_add_proveedor_to_groqapikey'),
        ('proyectos', '0019_elementoproyecto_elementodocumento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementoproyecto',
            options={'ordering': ['disciplina__nombre', 'area', 'orden', 'creado_en'], 'verbose_name': 'Elemento de Proyecto', 'verbose_name_plural': 'Elementos del Proyecto'},
        ),
        migrations.AddField(
            model_name='elementoproyecto',
            name='area',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Área / Nivel'),
        ),
        migrations.AddField(
            model_name='elementoproyecto',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_proyecto', to='documentos.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='elementoproyecto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Precio unitario'),
        ),
        migrations.AddField(
            model_name='elementoproyecto',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unidad de medida'),
        ),
    ]
