# Generated by Django 5.2.3 on 2026-02-24 02:24

import core.storage
import django.db.models.deletion
import plantillas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la plantilla', max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(help_text='Sube aquí la plantilla Word diseñada con marcadores {{ campo }}', storage=core.storage.MinIOStorage(), upload_to=plantillas.models.plantilla_upload_path, verbose_name='Archivo Word (.docx)')),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Modelo de Django al que aplica esta plantilla', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Plantilla Word',
                'verbose_name_plural': 'Plantillas Word',
                'ordering': ['content_type', 'nombre'],
            },
        ),
    ]
