# Generated by Django 6.0.6 on 2026-07-16 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('INFO', 'Información'), ('SUCCESS', 'Éxito'), ('WARNING', 'Advertencia'), ('ERROR', 'Error')], default='INFO', max_length=10, verbose_name='Tipo')),
                ('modulo', models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('PRESUPUESTOS', 'Presupuestos'), ('PORTAL_SUB', 'Portal Subcontratistas'), ('INVENTARIOS', 'Inventarios'), ('SISTEMA', 'Sistema')], db_index=True, default='SISTEMA', max_length=50, verbose_name='Módulo')),
                ('enlace', models.CharField(blank=True, max_length=500, verbose_name='Enlace')),
                ('icono', models.CharField(blank=True, max_length=50, verbose_name='Ícono')),
                ('leida', models.BooleanField(db_index=True, default=False, verbose_name='Leída')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Emisor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_app', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['user', 'leida'], name='notificacio_user_id_35b6d0_idx'), models.Index(fields=['user', 'modulo'], name='notificacio_user_id_61f33a_idx')],
            },
        ),
    ]
