# Generated by Django 5.1.7 on 2025-05-07 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_consumo_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMedidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='medidor',
            name='medidor_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medidores_hijos', to='core.medidor'),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medidores', to='core.tipomedidor'),
        ),
    ]
