# Generated by Django 5.1.7 on 2025-04-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='medidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='core.medidor'),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='activo',
            field=models.BooleanField(),
        ),
    ]
