# Generated by Django 5.1.7 on 2025-04-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_consumo_medidor_alter_medidor_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo',
            name='descripcion',
        ),
    ]
