# Generated by Django 5.1.7 on 2025-05-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipomedidor_medidor_medidor_padre_alter_medidor_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidor',
            name='tipo_medidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medidores', to='core.tipomedidor'),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
