# Generated by Django 5.1.7 on 2025-04-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_consumo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='consumo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
