# Generated by Django 5.1.7 on 2025-05-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medidor_tipo_medidor_alter_medidor_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceconsumo',
            name='consumo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interfaceconsumo',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interfaceconsumo',
            name='medidor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
