# Generated by Django 5.1.7 on 2025-04-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_consumo_consumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='medidor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='consumo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='consumo',
            name='updated',
        ),
        migrations.DeleteModel(
            name='Medidor',
        ),
    ]
