# Generated by Django 5.1.7 on 2025-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_interfaceconsumo_consumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceconsumo',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
