# Generated by Django 5.2.3 on 2025-07-01 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_interfaceconsumo_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaConsumoDiferencia',
            fields=[
                ('medidor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('consumo', models.FloatField()),
                ('consumo_anterior', models.FloatField()),
                ('diferencia_consumo', models.FloatField()),
            ],
            options={
                'verbose_name': 'Vista Consumo Diferencia',
                'verbose_name_plural': 'Vista Consumo Diferencia',
                'db_table': 'vista_consumo_diferencia',
                'ordering': ['-fecha'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('simbolo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.AddField(
            model_name='medidor',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medidores', to='core.unidadmedida'),
        ),
    ]
