# Generated by Django 5.1.7 on 2025-04-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_consumo_medidor_remove_consumo_created_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumo',
            unique_together={('fecha', 'medidor')},
        ),
    ]
