# Generated by Django 5.2.3 on 2025-07-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vistaconsumodiferencia_unidadmedida_medidor_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='fecha',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='consumo',
            index=models.Index(fields=['medidor', 'fecha'], name='core_consum_medidor_9a28eb_idx'),
        ),
    ]
