# Generated by Django 5.1.7 on 2025-04-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_medidor_alter_consumo_options_alter_consumo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('consumo', models.FloatField()),
                ('medidor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'interface_core_consumo',
                'managed': True,
            },
        ),
    ]
