# Generated by Django 5.1.7 on 2025-04-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_interfaceconsumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoDeMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('medidores', models.ManyToManyField(related_name='puntos_de_medicion', to='core.medidor')),
            ],
        ),
    ]
