# Generated by Django 5.2.7 on 2025-12-26 17:07

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_proyecto', models.CharField(default='Energía', help_text='Título en la barra superior', max_length=100)),
                ('color_primario', colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None, verbose_name='Color Primario (Botones, Headers)')),
                ('color_secundario', colorfield.fields.ColorField(default='#6c757d', image_field=None, max_length=25, samples=None, verbose_name='Color Secundario')),
                ('matriz_header_bg', colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None, verbose_name='Fondo Encabezado Matriz')),
                ('matriz_header_text', colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Texto Encabezado Matriz')),
                ('matriz_border_color', colorfield.fields.ColorField(default='#dee2e6', image_field=None, max_length=25, samples=None, verbose_name='Color de Bordes Matriz')),
                ('matriz_hover_row', colorfield.fields.ColorField(default='rgba(0,0,0,0.05)', image_field=None, max_length=25, samples=None, verbose_name='Hover Fila')),
                ('matriz_hover_cell', colorfield.fields.ColorField(default='rgba(0,0,0,0.1)', image_field=None, max_length=25, samples=None, verbose_name='Hover Celda')),
                ('orden_preventiva_bg', colorfield.fields.ColorField(default='#28a745', image_field=None, max_length=25, samples=None, verbose_name='Fondo OT Preventiva')),
                ('orden_correctiva_bg', colorfield.fields.ColorField(default='#dc3545', image_field=None, max_length=25, samples=None, verbose_name='Fondo OT Correctiva')),
                ('orden_texto', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Texto OT')),
            ],
            options={
                'verbose_name': 'Configuración Visual',
                'verbose_name_plural': 'Configuración Visual',
            },
        ),
    ]
