# Generated by Django 5.1.7 on 2025-04-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_puntodemedicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntodemedicion',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='puntodemedicion',
            name='medidores',
        ),
    ]
