# Generated by Django 5.1.7 on 2025-04-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_puntodemedicion_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaPuntoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_lectura', models.DateTimeField(auto_now_add=True)),
                ('valor_leido', models.FloatField()),
                ('lectura_contador', models.FloatField(blank=True, null=True, verbose_name='Lectura de Contador (si aplica)')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Documento de Medición',
                'verbose_name_plural': 'Documentos de Medición',
                'ordering': ['-fecha_hora_lectura'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_equipo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoMedicion',
            fields=[
                ('numero_interno', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('ambito_medicion_inferior', models.FloatField(blank=True, null=True, verbose_name='Límite Inferior')),
                ('ambito_medicion_superior', models.FloatField(blank=True, null=True, verbose_name='Límite Superior')),
                ('valor_objetivo', models.FloatField(blank=True, null=True, verbose_name='Valor Deseado')),
                ('es_contador', models.BooleanField(verbose_name='Es Contador')),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.caracteristicamedicion')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriapuntomedicion')),
                ('objeto_tecnico_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipo', verbose_name='Equipo Asociado')),
            ],
            options={
                'verbose_name': 'Punto de Medición',
                'verbose_name_plural': 'Puntos de Medición',
            },
        ),
        migrations.CreateModel(
            name='UbicacionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ubicacion', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PuntoDeMedicion',
        ),
        migrations.AddField(
            model_name='documentomedicion',
            name='punto_medicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.puntomedicion'),
        ),
        migrations.AddField(
            model_name='puntomedicion',
            name='objeto_tecnico_ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ubicaciontecnica', verbose_name='Ubicación Técnica Asociada'),
        ),
    ]
