# Generated by Django 5.1.7 on 2025-04-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_caracteristicamedicion_categoriapuntomedicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntomedicion',
            name='ambito_medicion_inferior',
        ),
        migrations.RemoveField(
            model_name='puntomedicion',
            name='ambito_medicion_superior',
        ),
        migrations.RemoveField(
            model_name='puntomedicion',
            name='valor_objetivo',
        ),
        migrations.AddField(
            model_name='caracteristicamedicion',
            name='ambito_medicion_inferior',
            field=models.FloatField(blank=True, null=True, verbose_name='Límite Inferior'),
        ),
        migrations.AddField(
            model_name='caracteristicamedicion',
            name='ambito_medicion_superior',
            field=models.FloatField(blank=True, null=True, verbose_name='Límite Superior'),
        ),
        migrations.AddField(
            model_name='caracteristicamedicion',
            name='valor_objetivo',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Deseado'),
        ),
    ]
