# Generated by Django 5.2.7 on 2026-02-24 22:13

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_perfilusuario_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('query_string', models.TextField(help_text='Query string del filtro (ej: ?empresa__id=1)')),
                ('es_publica', models.BooleanField(default=False, verbose_name='¿Es pública?')),
                ('color', colorfield.fields.ColorField(default='#4f46e5', image_field=None, max_length=25, samples=None, verbose_name='Color de la etiqueta')),
                ('icono', models.CharField(default='fas fa-filter', max_length=50, verbose_name='Icono FontAwesome')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas_personalizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vista Personalizada',
                'verbose_name_plural': 'Vistas Personalizadas',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'nombre', 'app_label', 'model_name')},
            },
        ),
    ]
