# Generated by Django 5.1.7 on 2025-04-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_rangomedicion_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentomedicion',
            name='rango',
        ),
    ]
