# Generated by Django 5.1.7 on 2025-04-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_documentomedicion_rango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentomedicion',
            name='fecha_hora_lectura',
            field=models.DateTimeField(verbose_name='Fecha y hora de lectura'),
        ),
    ]
