# Generated by Django 5.2.12 on 2026-03-13 01:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_knowledgechunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
