# Generated by Django 5.2.12 on 2026-04-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0018_departamento_perfilusuario_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Identificador interno (ej: auditoria, finanzas, logistica)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre visible en el admin (ej: Auditoría, Gestión Financiera)', max_length=100)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Desactivar para ocultar globalmente')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('grupos', models.ManyToManyField(blank=True, help_text='Grupos que pueden ver este elemento. Si está vacío, es visible para TODOS.', to='auth.group')),
            ],
            options={
                'verbose_name': 'Elemento de App',
                'verbose_name_plural': 'Elementos de App',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
