# Generated by Django 5.2.12 on 2026-04-10 17:01

from django.db import migrations


ELEMENTOS = [
    {'clave': 'scanner', 'nombre': 'Escanear Código', 'descripcion': 'QR Scanner', 'orden': 1},
    {'clave': 'mis_avisos', 'nombre': 'Mis Avisos', 'descripcion': 'Ver reportes de usuario', 'orden': 2},
    {'clave': 'crear_aviso', 'nombre': 'Crear Aviso', 'descripcion': 'Reportar falla', 'orden': 3},
    {'clave': 'auditoria', 'nombre': 'Auditoría', 'descripcion': 'Auditoría de equipos IA', 'orden': 4},
    {'clave': 'tiempo_acordado', 'nombre': 'Nuevo T. Acordado', 'descripcion': 'Extensión de tiempo', 'orden': 5},
    {'clave': 'logistica', 'nombre': 'Logística e Inventario', 'descripcion': 'Sección completa de logística', 'orden': 6},
    {'clave': 'gestion_almacen', 'nombre': 'Gestión de Almacén', 'descripcion': 'Despachar materiales', 'orden': 7},
    {'clave': 'finanzas', 'nombre': 'Gestión Financiera', 'descripcion': 'Requisiciones y presupuesto', 'orden': 8},
    {'clave': 'mi_planta', 'nombre': 'Mi Planta', 'descripcion': 'Infraestructura y ubicaciones', 'orden': 9},
    {'clave': 'tareas_hoy', 'nombre': 'Tareas de Hoy', 'descripcion': 'Órdenes de trabajo del día', 'orden': 10},
]


def seed_elementos(apps, schema_editor):
    ElementoApp = apps.get_model('core', 'ElementoApp')
    for elem in ELEMENTOS:
        ElementoApp.objects.get_or_create(clave=elem['clave'], defaults=elem)


def reverse_seed(apps, schema_editor):
    ElementoApp = apps.get_model('core', 'ElementoApp')
    claves = [e['clave'] for e in ELEMENTOS]
    ElementoApp.objects.filter(clave__in=claves).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_elementoapp'),
    ]

    operations = [
        migrations.RunPython(seed_elementos, reverse_seed),
    ]

