# Generated by Django 5.2.12 on 2026-06-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_seed_elementoapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Código'),
        ),
    ]
