# Generated by Django 6.0.6 on 2026-07-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_aprobador_to_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='correo',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo del Departamento'),
        ),
    ]
