# Generated by Django 6.0.6 on 2026-07-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_departamento_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='invitation_status',
            field=models.CharField(choices=[('pending', 'Pending Invitation'), ('active', 'Active')], default='active', max_length=10, verbose_name='Estado de Invitación'),
        ),
    ]
