# Generated by Django 6.0.6 on 2026-07-09 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_fix_invitation_status_db_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNavColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='Encabezado')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Columna de menú',
                'verbose_name_plural': 'Columnas de menú',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdminNavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('icon', models.CharField(default='fas fa-circle', max_length=100, verbose_name='Icono (FontAwesome)')),
                ('color', models.CharField(default='#0064d2', max_length=20, verbose_name='Color (hex)')),
                ('superuser_only', models.BooleanField(default=False, verbose_name='Solo superusuarios')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menú de navegación',
                'verbose_name_plural': 'Menús de navegación',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdminNavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('permission', models.CharField(blank=True, max_length=200, null=True, verbose_name='Permiso requerido')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.adminnavcolumn', verbose_name='Columna')),
            ],
            options={
                'verbose_name': 'Elemento de menú',
                'verbose_name_plural': 'Elementos de menú',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='adminnavcolumn',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.adminnavmenu', verbose_name='Menú'),
        ),
    ]
