# Generated by Django 6.0.6 on 2026-07-09 20:35

from django.db import migrations


def seed_admin_nav(apps, schema_editor):
    AdminNavMenu = apps.get_model("core", "AdminNavMenu")
    AdminNavColumn = apps.get_model("core", "AdminNavColumn")
    AdminNavItem = apps.get_model("core", "AdminNavItem")

    mantenimiento = AdminNavMenu.objects.create(
        name="Mantenimiento", icon="fas fa-tools", color="#f97316", order=1
    )
    col_ot = AdminNavColumn.objects.create(menu=mantenimiento, heading="Órdenes de Trabajo", order=1)
    AdminNavItem.objects.create(column=col_ot, name="Listado de Órdenes", url="/admin/mantenimiento/ordentrabajo/", permission="mantenimiento.view_ordentrabajo", order=1)
    AdminNavItem.objects.create(column=col_ot, name="Nueva Orden", url="/admin/mantenimiento/ordentrabajo/add/", permission="mantenimiento.add_ordentrabajo", order=2)
    col_mao = AdminNavColumn.objects.create(menu=mantenimiento, heading="MAO", order=2)
    AdminNavItem.objects.create(column=col_mao, name="Listado de Tickets", url="/admin/callcenter/solicitudticket/", permission="callcenter.view_solicitudticket", order=1)
    AdminNavItem.objects.create(column=col_mao, name="Dashboard de tickets", url="/callcenter/dashboard/", permission="callcenter.view_solicitudticket", order=2)

    costos = AdminNavMenu.objects.create(
        name="Costos y Presupuestos", icon="fas fa-wallet", color="#0064d2", order=2
    )
    col_req = AdminNavColumn.objects.create(menu=costos, heading="Requisiciones", order=1)
    AdminNavItem.objects.create(column=col_req, name="Dashboard", url="/presupuestos/requisiciones/dashboard/", permission="presupuestos.view_requisicion", order=1)
    AdminNavItem.objects.create(column=col_req, name="Listado de Requisiciones", url="/admin/presupuestos/requisicion/", permission="presupuestos.view_requisicion", order=2)
    AdminNavItem.objects.create(column=col_req, name="Nueva Requisición", url="/admin/presupuestos/requisicion/add/", permission="presupuestos.add_requisicion", order=3)
    AdminNavItem.objects.create(column=col_req, name="Solicitudes de Pago", url="/admin/presupuestos/solicitudpago/", permission="presupuestos.view_solicitudpago", order=4)

    inventarios = AdminNavMenu.objects.create(
        name="Inventarios", icon="fas fa-boxes", color="#107e3e", order=3
    )
    col_mat = AdminNavColumn.objects.create(menu=inventarios, heading="Materiales", order=1)
    AdminNavItem.objects.create(column=col_mat, name="Catálogo de Materiales", url="/admin/inventarios/material/", permission="inventarios.view_material", order=1)
    AdminNavItem.objects.create(column=col_mat, name="Requisición de materiales", url="/inventarios/crear-solicitud/", permission="inventarios.view_solicitudmaterial", order=2)

    ajustes = AdminNavMenu.objects.create(
        name="Ajustes", icon="fas fa-cog", color="#556b82", superuser_only=True, order=4
    )
    col_imp = AdminNavColumn.objects.create(menu=ajustes, heading="Importaciones", order=1)
    AdminNavItem.objects.create(column=col_imp, name="Dashboard de Importaciones", url="/activos/import-dashboard/", permission="activos.view_registroimportacion", order=1)


def unseed_admin_nav(apps, schema_editor):
    AdminNavMenu = apps.get_model("core", "AdminNavMenu")
    AdminNavMenu.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_adminnavcolumn_adminnavmenu_adminnavitem_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_admin_nav, unseed_admin_nav),
    ]
