# Generated by Django 6.0.6 on 2026-07-09 21:21

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_items(apps, schema_editor):
    AdminNavItem = apps.get_model("core", "AdminNavItem")
    for item in AdminNavItem.objects.all():
        if item.column_id and not item.menu_id:
            item.menu = item.column.menu
            item.group = item.column.heading
            item.save(update_fields=["menu_id", "group"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_seed_admin_nav"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminnavitem",
            name="group",
            field=models.CharField(
                blank=True,
                help_text="Agrupa items bajo un mismo encabezado en el mega menú",
                max_length=100,
                null=True,
                verbose_name="Encabezado de columna",
            ),
        ),
        migrations.AddField(
            model_name="adminnavitem",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.adminnavmenu",
                verbose_name="Menú",
            ),
        ),
        migrations.AlterField(
            model_name="adminnavitem",
            name="column",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.adminnavcolumn",
                verbose_name="Columna",
            ),
        ),
        migrations.RunPython(migrate_existing_items, migrations.RunPython.noop),
    ]
