# Generated by Django 6.0.6 on 2026-07-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_refactor_admin_nav_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='nav_config',
            field=models.JSONField(blank=True, default=dict, help_text='{"hidden_menus": ["Mantenimiento"], "custom_menus": [{"name": "Mis Links", "icon": "fas fa-star", "color": "#f59e0b", "columns": [{"heading": "", "items": [{"name": "Link", "url": "/url/"}]}]}]}', verbose_name='Configuración de navegación'),
        ),
    ]
