# Generated by Django 6.0.6 on 2026-08-04 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_nav_config_to_perfil'),
        ('mantenimiento', '0090_add_embedding_ordentrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_usuario', to='mantenimiento.puestotrabajo', verbose_name='Puesto de Trabajo'),
        ),
    ]
