# Generated by Django 6.0.6 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_puesto_trabajo_to_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnavmenu',
            name='descripcion',
            field=models.CharField(blank=True, default='', help_text='Texto corto mostrado en la tarjeta de la página de inicio.', max_length=255, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='adminnavmenu',
            name='grupos',
            field=models.ManyToManyField(blank=True, help_text='Grupos (roles) que pueden ver este módulo. Si está vacío, es visible para TODOS.', to='auth.group', verbose_name='Grupos (rol)'),
        ),
        migrations.AddField(
            model_name='adminnavmenu',
            name='url',
            field=models.CharField(blank=True, default='', help_text='Enlace directo de la tarjeta. Si se define, la tarjeta enlaza directo (sin sub-accesos).', max_length=500, verbose_name='URL directa (opcional)'),
        ),
        migrations.AddField(
            model_name='adminnavitem',
            name='icon',
            field=models.CharField(default='fas fa-angle-right', max_length=100, verbose_name='Icono (FontAwesome)'),
        ),
    ]
