# Generated by Django 6.0.6 on 2026-08-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_backfill_adminnavitem_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMedidorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Dashboard de Medidores', max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True)),
                ('intervalo_refresh', models.PositiveIntegerField(default=60, verbose_name='Intervalo de Refresco (segundos)')),
                ('titulo', models.CharField(default='Monitoreo de Medidores', max_length=200, verbose_name='Título')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('medidores', models.ManyToManyField(blank=True, related_name='dashboard_configs', to='core.medidor', verbose_name='Medidores a Mostrar')),
            ],
            options={
                'verbose_name': 'Config Dashboard Medidores',
                'verbose_name_plural': 'Config Dashboard Medidores',
            },
        ),
    ]
