# Generated by Django 6.0.6 on 2026-08-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0075_add_codigo_exoneracion_fk_categoria'),
        ('core', '0034_dashboard_medidor_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmedidorconfig',
            name='puntos_medicion',
            field=models.ManyToManyField(blank=True, related_name='dashboard_configs', to='activos.puntomedicion', verbose_name='Puntos de Medición a Mostrar'),
        ),
        migrations.AlterField(
            model_name='dashboardmedidorconfig',
            name='medidores',
            field=models.ManyToManyField(blank=True, related_name='dashboard_configs', to='core.medidor', verbose_name='Medidores a Mostrar (legacy)'),
        ),
        migrations.AlterField(
            model_name='dashboardmedidorconfig',
            name='titulo',
            field=models.CharField(default='Monitoreo de Puntos de Medición', max_length=200, verbose_name='Título'),
        ),
    ]
