# Generated by Django 6.0.6 on 2026-08-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_puntos_medicion_to_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='aprobador_salidas',
            field=models.BooleanField(default=False, help_text='Si está activo, este usuario puede aprobar solicitudes de material de su departamento.', verbose_name='Aprobador de Salidas'),
        ),
    ]
