# Generated by Django 6.0.6 on 2026-09-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_seed_nav_dashboard_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='expo_push_token',
            field=models.CharField(blank=True, help_text='Token de notificaciones push de la app móvil.', max_length=255, null=True, verbose_name='Token Push (Expo)'),
        ),
    ]
