# Generated by Django 5.2.12 on 2026-04-25 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BACnetGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='IP local del servidor para el socket BACnet (o IP VPN)')),
                ('port', models.IntegerField(default=47808)),
                ('device_id', models.IntegerField(default=123, help_text='Device ID de este servidor en la red BACnet')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gateway BACnet',
                'verbose_name_plural': 'Gateways BACnet',
            },
        ),
        migrations.CreateModel(
            name='BACnetDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(help_text='IP remota del controlador', max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='iot.bacnetgateway')),
            ],
            options={
                'verbose_name': 'Dispositivo BACnet',
                'verbose_name_plural': 'Dispositivos BACnet',
            },
        ),
        migrations.CreateModel(
            name='BACnetPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('object_type', models.CharField(choices=[('analogInput', 'Analog Input'), ('analogOutput', 'Analog Output'), ('analogValue', 'Analog Value'), ('binaryInput', 'Binary Input'), ('binaryOutput', 'Binary Output'), ('binaryValue', 'Binary Value'), ('multiStateInput', 'Multi-state Input'), ('multiStateOutput', 'Multi-state Output'), ('multiStateValue', 'Multi-state Value')], max_length=50)),
                ('instance', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('save_history', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='iot.bacnetdevice')),
            ],
            options={
                'verbose_name': 'Punto BACnet',
                'verbose_name_plural': 'Puntos BACnet',
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('value', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='iot.bacnetpoint')),
            ],
            options={
                'verbose_name': 'Lectura de Telemetría',
                'verbose_name_plural': 'Lecturas de Telemetría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
