# Generated by Django 5.2.12 on 2026-04-28 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BACnetSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instance', models.IntegerField()),
                ('weekly_schedule', models.JSONField(blank=True, help_text='JSON representation of weekly events', null=True)),
                ('present_value', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='iot.bacnetdevice')),
            ],
            options={
                'verbose_name': 'Horario BACnet',
                'verbose_name_plural': 'Horarios BACnet',
                'unique_together': {('device', 'instance')},
            },
        ),
    ]
