# Generated by Django 5.2.7 on 2026-01-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_solicitud', models.BigIntegerField(unique=True, verbose_name='ID Solicitud Servicio')),
                ('folio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Folio')),
                ('solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsable de Atención')),
                ('solicitud_descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Solicitud')),
                ('falla_descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Falla')),
                ('falla_clasificacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clasificación Falla')),
                ('servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('subservicio', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Solicitud')),
                ('tipo_recepcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Recepción')),
                ('fecha_tipo_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Tipo Recepción')),
                ('fecha_suspension', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Suspensión')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cierre')),
                ('tipo_solicitud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Solicitud')),
                ('tiempo_tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo Tipo')),
                ('fecha_diagnostico', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Diagnóstico')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('fecha_actividades', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Actividades')),
                ('actividades', models.TextField(blank=True, null=True, verbose_name='Actividades')),
                ('fecha_observaciones', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Observaciones')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_observaciones_usuario', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Obs. Usuario')),
                ('observaciones_usuario', models.TextField(blank=True, null=True, verbose_name='Observaciones Usuario')),
                ('clasificacion_falla_final', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clasificación Falla Final')),
                ('categoria_falla', models.CharField(blank=True, max_length=255, null=True, verbose_name='Categoría Falla')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Ticket',
                'verbose_name_plural': 'Solicitudes de Tickets',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
