# Generated by Django 5.2.7 on 2026-02-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0002_solicitudticket_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudticket',
            name='area',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudticket',
            name='fecha_solicitud',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudticket',
            name='folio',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='solicitudticket',
            name='servicio',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudticket',
            name='solicitante',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
