# Generated by Django 5.2.7 on 2026-02-21 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0046_bienafecto_plano_alter_activo_foto_and_more'),
        ('callcenter', '0003_alter_solicitudticket_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudticket',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='activos.ubicacion', verbose_name='Ubicación Física'),
        ),
    ]
