# Generated by Django 5.1.15 on 2026-02-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0004_solicitudticket_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Correlativo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('descripcion', models.TextField(verbose_name='Descripción del Grupo')),
                ('tickets', models.ManyToManyField(related_name='grupos', to='callcenter.solicitudticket', verbose_name='Tickets')),
            ],
            options={
                'verbose_name': 'Grupo de Ticket',
                'verbose_name_plural': 'Grupos de Tickets',
                'ordering': ['-fecha'],
            },
        ),
    ]
