# Generated by Django 5.1.15 on 2026-02-27 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0005_grupoticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='callcenter/evidencias/%Y/%m/%d/', verbose_name='Archivo/Foto')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción Corta')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='callcenter.solicitudticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Evidencia de Ticket',
                'verbose_name_plural': 'Evidencias de tickets',
            },
        ),
    ]
