# Generated by Django 5.2.12 on 2026-03-24 22:21

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0006_evidenciaticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudticket',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
