# Generated by Django 5.2.12 on 2026-03-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0007_solicitudticket_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudticket',
            name='cierre_enviado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Cierre Notificado'),
        ),
    ]
