# Generated by Django 5.2.12 on 2026-03-29 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0009_solicitudticket_usuario_responsable'),
        ('mantenimiento', '0060_add_foto_tipo_and_paso_to_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudticket',
            name='deductiva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Monto de la deductiva en USD', max_digits=12, null=True, verbose_name='Deductiva (USD)'),
        ),
        migrations.AddField(
            model_name='solicitudticket',
            name='proveedor_deductiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductivas_callcenter', to='mantenimiento.empresa', verbose_name='Proveedor de Deductiva'),
        ),
    ]
