# Generated by Django 5.2.12 on 2026-03-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0010_solicitudticket_deductiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudticket',
            name='correo_cierre',
            field=models.BooleanField(db_index=True, default=False, help_text='Se marca automáticamente cuando Power Automate confirma el envío del correo de cierre', verbose_name='Correo de Cierre Enviado'),
        ),
    ]
