# Generated by Django 5.2.12 on 2026-04-06 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0061_fix_puntos_3d_data_modelo_nullable'),
        ('callcenter', '0011_add_correo_cierre'),
        ('core', '0018_departamento_perfilusuario_departamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Institución')),
                ('ubicaciones', models.ManyToManyField(help_text='Una institución puede tener una o más ubicaciones físicas.', related_name='instituciones', to='activos.ubicacion', verbose_name='Ubicaciones de la Institución')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono / WhatsApp')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlaces', to='activos.ubicacion', verbose_name='Ubicación por Defecto')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='callcenter.institucion', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Enlace / Contacto',
                'verbose_name_plural': 'Enlaces de Instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TiempoAcordado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_extension', models.TextField(verbose_name='Motivo del Tiempo Acordado')),
                ('solucion_provisional', models.TextField(verbose_name='Solución Provisional Acordada')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('fecha_solucion_final', models.DateTimeField(verbose_name='Fecha Solución Final Comprometida')),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado / En Proceso'), ('VENCIDO', 'Vencido'), ('FINALIZADO', 'Finalizado')], default='BORRADOR', max_length=20, verbose_name='Estado del Acuerdo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acuerdos_departamento', to='core.departamento')),
                ('enlace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiempos_acordados', to='callcenter.enlace', verbose_name='Enlace Solicitante')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='callcenter.institucion', verbose_name='Institución')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_acordados', to='callcenter.solicitudticket', verbose_name='Ticket Relacionado')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.ubicacion', verbose_name='Ubicación del Reporte')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acuerdos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tiempo Acordado',
                'verbose_name_plural': 'Tiempos Acordados',
                'ordering': ['-fecha_solucion_final'],
            },
        ),
        migrations.CreateModel(
            name='TiempoAcordadoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Actividad / Tarea')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha Final')),
                ('completada', models.BooleanField(default=False, verbose_name='¿Completada?')),
                ('tiempo_acordado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='callcenter.tiempoacordado', verbose_name='Acuerdo')),
            ],
            options={
                'verbose_name': 'Tarea de Cronograma',
                'verbose_name_plural': 'Tareas de Cronogramas',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
