# Generated by Django 5.2.12 on 2026-04-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0012_institucion_enlace_tiempoacordado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='acronimo',
            field=models.CharField(blank=True, help_text='Ej: SAR, BANX, etc.', max_length=20, null=True, verbose_name='Acrónimo'),
        ),
    ]
