# Generated by Django 5.2.12 on 2026-04-06 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0061_fix_puntos_3d_data_modelo_nullable'),
        ('callcenter', '0013_institucion_acronimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='ubicaciones',
            field=models.ManyToManyField(blank=True, help_text='Una institución puede tener una o más ubicaciones físicas.', related_name='instituciones', to='activos.ubicacion', verbose_name='Ubicaciones de la Institución'),
        ),
        migrations.AlterField(
            model_name='tiempoacordado',
            name='enlace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiempos_acordados', to='callcenter.enlace', verbose_name='Enlace Solicitante'),
        ),
    ]
