# Generated by Django 5.2.12 on 2026-04-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0014_alter_institucion_ubicaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempoacordado',
            name='firma_enlace',
            field=models.TextField(blank=True, null=True, verbose_name='Firma del Enlace'),
        ),
    ]
