# Generated by Django 5.2.12 on 2026-04-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0015_tiempoacordado_firma_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempoacordado',
            name='firma_responsable',
            field=models.TextField(blank=True, null=True, verbose_name='Firma del Responsable'),
        ),
    ]
