# Generated by Django 5.2.12 on 2026-04-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0016_tiempoacordado_firma_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudticket',
            name='cierre_enviado',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Cierre Notificado'),
        ),
        migrations.AlterField(
            model_name='solicitudticket',
            name='correo_cierre',
            field=models.BooleanField(blank=True, db_index=True, default=False, help_text='Se marca automáticamente cuando Power Automate confirma el envío del correo de cierre', null=True, verbose_name='Correo de Cierre Enviado'),
        ),
    ]
