# Generated by Django 5.2.12 on 2026-04-07 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0017_alter_solicitudticket_cierre_enviado_and_more'),
        ('core', '0018_departamento_perfilusuario_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaPredefinido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Cronograma')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cronogramas_predefinidos', to='core.departamento', verbose_name='Departamento / Área')),
            ],
            options={
                'verbose_name': 'Cronograma Predefinido',
                'verbose_name_plural': 'Cronogramas Predefinidos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CronogramaItemPredefinido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='N°')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción de la Tarea')),
                ('duracion_dias', models.PositiveIntegerField(default=1, verbose_name='Duración (Días)')),
                ('predecesores', models.ManyToManyField(blank=True, related_name='sucesores', to='callcenter.cronogramaitempredefinido', verbose_name='Predecesores')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='callcenter.cronogramapredefinido', verbose_name='Cronograma')),
            ],
            options={
                'verbose_name': 'Item de Cronograma',
                'verbose_name_plural': 'Items de Cronograma',
                'ordering': ['numero'],
            },
        ),
    ]
