# Generated by Django 5.2.12 on 2026-04-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0018_cronogramapredefinido_cronogramaitempredefinido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempoacordado',
            name='enviado',
            field=models.BooleanField(default=False, help_text='Indica si el reporte PDF ya fue enviado a través del flujo de Power Automate.', verbose_name='¿Enviado por Correo?'),
        ),
    ]
