# Generated by Django 5.2.12 on 2026-04-07 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0019_tiempoacordado_enviado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestriccionAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_ra', models.CharField(max_length=50, unique=True, verbose_name='Folio RA')),
                ('fecha_restriccion', models.DateTimeField(verbose_name='Fecha y Hora de Restricción')),
                ('fecha_reprogramacion', models.DateTimeField(verbose_name='Fecha y Hora de Reprogramación')),
                ('horas_restriccion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas de Restricción')),
                ('firma_usuario', models.TextField(blank=True, null=True, verbose_name='Firma del Usuario')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restriccion_acceso', to='callcenter.solicitudticket', verbose_name='Ticket Relacionado')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restricción de Acceso',
                'verbose_name_plural': 'Restricciones de Acceso',
            },
        ),
    ]
