# Generated by Django 5.2.12 on 2026-04-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0020_restriccionacceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='restriccionacceso',
            name='firma_tecnico',
            field=models.TextField(blank=True, null=True, verbose_name='Firma del Técnico'),
        ),
    ]
