# Generated by Django 5.2.12 on 2026-04-16 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0021_restriccionacceso_firma_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Falla')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
            ],
            options={
                'verbose_name': 'Catálogo de Falla',
                'verbose_name_plural': 'Catálogo de Fallas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='solicitudticket',
            name='falla_reportada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='callcenter.fallaticket', verbose_name='Falla del Catálogo'),
        ),
    ]
