# Generated by Django 5.2.12 on 2026-04-16 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0023_fallaticket_departamento_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fallaticket',
            name='usuario_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallas_asignadas_defecto', to=settings.AUTH_USER_MODEL, verbose_name='Responsable por Defecto'),
        ),
    ]
