# Generated by Django 5.2.12 on 2026-04-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0024_fallaticket_usuario_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoticket',
            name='correlativo',
            field=models.CharField(max_length=255, unique=True, verbose_name='Número de Grupo / Cluster'),
        ),
    ]
