# Generated by Django 5.2.12 on 2026-04-16 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0025_alter_grupoticket_correlativo'),
        ('core', '0020_seed_elementoapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoticket',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clusters', to='core.departamento', verbose_name='Departamento Responsable'),
        ),
    ]
