# Generated by Django 5.2.12 on 2026-04-28 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0026_grupoticket_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallaticket',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfallas', to='callcenter.fallaticket', verbose_name='Falla Padre'),
        ),
    ]
