# Generated by Django 5.2.12 on 2026-04-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0027_fallaticket_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciaticket',
            name='analizada',
            field=models.BooleanField(default=False, verbose_name='Analizada por IA'),
        ),
        migrations.AddField(
            model_name='evidenciaticket',
            name='descripcion_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Análisis de IA (Visual)'),
        ),
    ]
