# Generated by Django 5.2.12 on 2026-04-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0028_evidenciaticket_analizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaticket',
            name='analizada',
            field=models.BooleanField(default=False, null=True, verbose_name='Analizada por IA'),
        ),
    ]
