# Generated by Django 5.2.12 on 2026-05-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0030_grupoticket_usuario_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudticket',
            name='es_interno',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Es Ticket Interno'),
        ),
    ]
