# Generated by Django 5.2.12 on 2026-05-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0031_solicitudticket_es_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudticket',
            name='comentarios_internos',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios Internos'),
        ),
    ]
