# Generated by Django 5.2.12 on 2026-05-19 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0032_solicitudticket_comentarios_internos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fallaticket',
            options={'verbose_name': 'Catálogo de Falla', 'verbose_name_plural': 'Catálogo de Fallas'},
        ),
        migrations.CreateModel(
            name='DiagnosticoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Diagnóstico')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Diagnóstico')),
                ('falla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_asociados', to='callcenter.fallaticket', verbose_name='Falla Asociada')),
            ],
            options={
                'verbose_name': 'Catálogo de Diagnóstico',
                'verbose_name_plural': 'Catálogos de Diagnósticos',
                'ordering': ['falla__nombre', 'nombre'],
            },
        ),
    ]
