# Generated by Django 5.2.12 on 2026-05-21 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0033_alter_fallaticket_options_diagnosticoticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudticket',
            name='diagnostico_reportado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='callcenter.diagnosticoticket', verbose_name='Diagnóstico del Catálogo'),
        ),
    ]
