# Generated by Django 5.2.12 on 2026-05-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0034_solicitudticket_diagnostico_reportado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudticket',
            name='robot_estatus',
            field=models.CharField(blank=True, help_text='Indica si el ticket fue documentado completa o parcialmente.', max_length=100, null=True, verbose_name='Estatus de Automatización'),
        ),
        migrations.AddField(
            model_name='solicitudticket',
            name='robot_log',
            field=models.TextField(blank=True, help_text='Historial detallado del proceso de guardado y carga de evidencias en SIG GIA.', null=True, verbose_name='Log de Automatización'),
        ),
    ]
