# Generated by Django 5.2.12 on 2026-05-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0035_solicitudticket_robot_estatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudticket',
            name='solicitud_adicional',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Solicitud Adicional'),
        ),
    ]
