# Generated by Django 6.0.6 on 2026-07-01 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0036_solicitudticket_solicitud_adicional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADO', 'Ticket Creado'), ('ACTUALIZADO', 'Ticket Actualizado'), ('DIAGNOSTICO', 'Diagnóstico Ingresado'), ('CIERRE_FECHA', 'Fecha de Cierre Asignada'), ('CORREO_CIERRE', 'Correo de Cierre Enviado'), ('SIG_SYNC', 'Sincronización SIG'), ('SIG_ERROR', 'Error en Sincronización SIG'), ('DEDUCTIVA', 'Deductiva Actualizada'), ('REASIGNADO', 'Técnico Reasignado'), ('COMENTARIO', 'Comentario Interno'), ('CIERRE_VISUAL', 'Cierre Visual Realizado')], max_length=20, verbose_name='Acción')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='callcenter.solicitudticket', verbose_name='Ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Ticket',
                'verbose_name_plural': 'Historial de Tickets',
                'ordering': ['-creado_en'],
            },
        ),
    ]
