# Generated by Django 6.0.6 on 2026-07-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0037_historial_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticoticket',
            name='actividad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Actividad Realizada'),
        ),
    ]
