# Generated by Django 6.0.6 on 2026-07-17 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0074_rack_bodega_area'),
        ('callcenter', '0038_diagnosticoticket_actividad'),
        ('documentos', '0035_add_proveedor_to_groqapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlace',
            name='contrasena_sig',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña SIG'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='correo_secundario',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Secundario'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='extension_ccg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Extensión CCG'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Alta'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('OTRO', 'Otro')], max_length=10, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='nivel_referencia',
            field=models.CharField(blank=True, help_text='Manual / Nivel jerárquico dentro de la institución', max_length=255, null=True, verbose_name='Nivel de Referencia'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='nombre_sig',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre SIG'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='oficio_alta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlaces_oficio_alta', to='documentos.documento', verbose_name='Oficio de Alta'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='oficio_baja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlaces_oficio_baja', to='documentos.documento', verbose_name='Oficio de Baja'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='pin_sig',
            field=models.IntegerField(blank=True, null=True, verbose_name='PIN SIG'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1er Apellido'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2do Apellido'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono 2'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='usuario_sig',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario SIG'),
        ),
        migrations.AlterField(
            model_name='enlace',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Principal'),
        ),
        migrations.AlterField(
            model_name='enlace',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='enlace',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono 1'),
        ),
        migrations.AlterField(
            model_name='enlace',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlaces', to='activos.ubicacion', verbose_name='Ubicación'),
        ),
    ]
