# Generated by Django 6.0.6 on 2026-07-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0039_enlace_campos_completos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudticket',
            name='enlace_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='callcenter.enlace', verbose_name='Enlace Solicitante'),
        ),
    ]
