# Generated by Django 6.0.6 on 2026-07-28 07:29

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0040_solicitudticket_enlace_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudticket',
            name='embedding_local',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
