# Generated by Django 6.0.6 on 2026-08-21 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0041_add_embedding_local'),
        ('core', '0033_backfill_adminnavitem_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Dashboard Principal', max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Configuración Activa')),
                ('mostrar_total_tickets', models.BooleanField(default=True, verbose_name='Mostrar Total Tickets')),
                ('mostrar_tickets_abiertos', models.BooleanField(default=True, verbose_name='Mostrar Tickets Abiertos')),
                ('mostrar_tickets_cerrados', models.BooleanField(default=True, verbose_name='Mostrar Tickets Cerrados')),
                ('mostrar_grafica_categorias', models.BooleanField(default=True, verbose_name='Mostrar Gráfica por Categorías')),
                ('mostrar_grafica_fallas', models.BooleanField(default=True, verbose_name='Mostrar Gráfica Top Fallas')),
                ('mostrar_tabla_recientes', models.BooleanField(default=True, verbose_name='Mostrar Tabla de Tickets Recientes')),
                ('mostrar_todos_clusters', models.BooleanField(default=False, help_text='Si está activo, ignora la selección manual y muestra todos', verbose_name='Mostrar Todos los Clusters')),
                ('max_clusters', models.PositiveIntegerField(default=10, verbose_name='Máximo de Clusters a Mostrar')),
                ('dias_antiguedad', models.PositiveIntegerField(default=30, help_text='Mostrar tickets de los últimos N días', verbose_name='Días de Antigüedad')),
                ('intervalo_refresh', models.PositiveIntegerField(default=60, help_text='Cada cuántos segundos se actualiza el dashboard automáticamente', verbose_name='Intervalo de Refresco (segundos)')),
                ('titulo_dashboard', models.CharField(default='Dashboard de Tickets en Tiempo Real', max_length=200, verbose_name='Título del Dashboard')),
                ('subtitulo_dashboard', models.CharField(blank=True, default='Monitoreo en vivo de la operación', max_length=300, verbose_name='Subtítulo')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clusters', models.ManyToManyField(blank=True, related_name='dashboard_configs', to='callcenter.grupoticket', verbose_name='Clusters a Mostrar')),
                ('departamento_filtro', models.ForeignKey(blank=True, help_text='Dejar vacío para mostrar todos los departamentos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departamento', verbose_name='Filtrar por Departamento')),
            ],
            options={
                'verbose_name': 'Configuración de Dashboard',
                'verbose_name_plural': 'Configuraciones de Dashboard',
            },
        ),
    ]
