# Generated by Django 6.0.6 on 2026-08-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0042_dashboard_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardconfig',
            name='auto_sync_enabled',
            field=models.BooleanField(default=False, help_text='Ejecuta el wizard de sincronización periódicamente para agregar nuevos tickets al cluster', verbose_name='Sincronización Automática'),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='auto_sync_intervalo_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Cada cuántos minutos se sincroniza el cluster automáticamente', verbose_name='Intervalo de Sincronización (minutos)'),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='auto_sync_last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronización Automática'),
        ),
    ]
