# Generated by Django 5.2.7 on 2025-12-21 20:54

import datetime
import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0011_alter_ubicacion_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(help_text='Abreviatura (ej: ELE, MEC)', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(help_text='Abreviatura para códigos (ej: PLN, MNL)', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del documento (Ej: CCG-I-T1-IAA-07-02)', max_length=50, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('estado_actual', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('OBSOLETO', 'Obsoleto')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activos', models.ManyToManyField(blank=True, related_name='documentos', to='activos.activo')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documentos.disciplina')),
                ('ubicaciones', models.ManyToManyField(blank=True, related_name='documentos', to='activos.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(help_text='Ej: A, B, 0, 1, 2...', max_length=10, verbose_name='Revisión')),
                ('archivo', models.FileField(upload_to=documentos.models.documento_upload_path)),
                ('fecha_revision', models.DateField(default=datetime.date.today)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, help_text='Descripción del cambio')),
                ('hash_archivo', models.CharField(blank=True, editable=False, max_length=64)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='documentos.documento')),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
                'ordering': ['-creado_en'],
                'unique_together': {('documento', 'revision')},
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='ultima_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_actual', to='documentos.revision', verbose_name='Última Revisión'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.tipodocumento', verbose_name='Tipo'),
        ),
    ]
