# Generated by Django 5.2.7 on 2025-12-26 17:55

import django.core.validators
import django.db.models.deletion
import documentos.models_firmas
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_documento_original', models.CharField(editable=False, help_text='Hash SHA-256 del documento en el momento de la firma', max_length=64)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Firmas'), ('PARCIAL', 'Firmado Parcialmente'), ('COMPLETO', 'Firmado Completamente'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pdf_firmado', models.FileField(blank=True, help_text='PDF con todas las firmas estampadas', null=True, upload_to='firmas/documentos_firmados/')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas_aplicadas', to='documentos.documento', verbose_name='Documento')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='documentos.revision', verbose_name='Revisión del Documento')),
            ],
            options={
                'verbose_name': 'Documento Firmado',
                'verbose_name_plural': 'Documentos Firmados',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_firma', models.ImageField(help_text='Imagen PNG de la firma estampada', upload_to=documentos.models_firmas.firma_documento_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])])),
                ('posicion_x', models.FloatField(help_text='Coordenada X (porcentaje)')),
                ('posicion_y', models.FloatField(help_text='Coordenada Y (porcentaje)')),
                ('pagina', models.IntegerField(default=1, help_text='Número de página')),
                ('ancho', models.FloatField(default=15)),
                ('alto', models.FloatField(default=8)),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('ip_firmante', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se firmó', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Navegador/dispositivo usado para firmar')),
                ('hash_firma', models.CharField(editable=False, help_text='Hash SHA-256 de la imagen de firma', max_length=64)),
                ('token_verificacion', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para verificar la autenticidad de la firma', unique=True)),
                ('firmado', models.BooleanField(default=True)),
                ('rechazado', models.BooleanField(default=False)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios del firmante')),
                ('documento_firmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='documentos.documentofirmado', verbose_name='Documento Firmado')),
                ('firmante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Firmante')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmas',
                'ordering': ['-fecha_firma'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaFirmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR_PERFIL', 'Creación de Perfil de Firma'), ('ACTUALIZAR_PERFIL', 'Actualización de Perfil'), ('SOLICITAR_FIRMA', 'Solicitud de Firma'), ('FIRMAR', 'Documento Firmado'), ('RECHAZAR', 'Firma Rechazada'), ('VERIFICAR', 'Verificación de Firma'), ('GENERAR_PDF', 'Generación de PDF Firmado')], max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documento_firmado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.documentofirmado')),
                ('firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.firma')),
            ],
            options={
                'verbose_name': 'Auditoría de Firma',
                'verbose_name_plural': 'Auditorías de Firmas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FirmaRequerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1, help_text='Orden en que debe firmarse (1 = primero). 0 = sin orden específico')),
                ('rol', models.CharField(blank=True, help_text="Ej: 'Elaboró', 'Revisó', 'Aprobó', 'Autorizó'", max_length=100)),
                ('posicion_x', models.FloatField(default=0, help_text='Posición X en el documento (porcentaje 0-100)')),
                ('posicion_y', models.FloatField(default=0, help_text='Posición Y en el documento (porcentaje 0-100)')),
                ('pagina', models.IntegerField(default=1, help_text='Número de página donde se estampará la firma')),
                ('ancho', models.FloatField(default=15, help_text='Ancho de la firma (% del ancho de página)')),
                ('alto', models.FloatField(default=8, help_text='Alto de la firma (% del alto de página)')),
                ('obligatoria', models.BooleanField(default=True, help_text='Si es obligatoria, el documento no se completa sin esta firma')),
                ('notificado', models.BooleanField(default=False, help_text='Si se ha notificado al firmante')),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('documento_firmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas_requeridas', to='documentos.documentofirmado', verbose_name='Documento')),
                ('firmante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_por_firmar', to=settings.AUTH_USER_MODEL, verbose_name='Firmante Requerido')),
            ],
            options={
                'verbose_name': 'Firma Requerida',
                'verbose_name_plural': 'Firmas Requeridas',
                'ordering': ['orden', 'firmante__last_name'],
                'unique_together': {('documento_firmado', 'firmante', 'rol')},
            },
        ),
        migrations.AddField(
            model_name='firma',
            name='firma_requerida',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firma_aplicada', to='documentos.firmarequerida', verbose_name='Firma Requerida'),
        ),
        migrations.CreateModel(
            name='PerfilFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_imagen', models.ImageField(blank=True, help_text='Imagen de la firma (PNG recomendado con fondo transparente)', null=True, upload_to=documentos.models_firmas.firma_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True, help_text='Si está activa, esta firma se usará por defecto')),
                ('cargo', models.CharField(blank=True, help_text='Cargo del firmante', max_length=200)),
                ('departamento', models.CharField(blank=True, max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_firma', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Firma',
                'verbose_name_plural': 'Perfiles de Firma',
            },
        ),
    ]
