# Generated by Django 5.2.7 on 2026-01-23 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documentos', '0002_documentofirmado_firma_auditoriafirmas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MayanDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mayan_document_id', models.IntegerField(help_text='ID del documento en Mayan EDMS')),
                ('document_label', models.CharField(help_text='Nombre/etiqueta del documento', max_length=255)),
                ('document_type', models.CharField(blank=True, help_text='Tipo de documento (Manual, Certificado, etc.)', max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo de Documento Mayan',
                'verbose_name_plural': 'Vínculos de Documentos Mayan',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='documentos__content_8bf4c2_idx'), models.Index(fields=['mayan_document_id'], name='documentos__mayan_d_74947f_idx')],
            },
        ),
    ]
