# Generated by Django 5.2.7 on 2026-02-06 01:37

import core.storage
import django.core.validators
import documentos.models
import documentos.models_firmas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_mayandocumentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='datos_extraidos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='estado_extraccion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error'), ('NO_APLICA', 'No Aplica')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentofirmado',
            name='pdf_firmado',
            field=models.FileField(blank=True, help_text='PDF con todas las firmas estampadas', null=True, storage=core.storage.MinIOStorage(), upload_to='firmas/documentos_firmados/'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='imagen_firma',
            field=models.ImageField(help_text='Imagen PNG de la firma estampada', storage=core.storage.MinIOStorage(), upload_to=documentos.models_firmas.firma_documento_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
        migrations.AlterField(
            model_name='perfilfirma',
            name='firma_imagen',
            field=models.ImageField(blank=True, help_text='Imagen de la firma (PNG recomendado con fondo transparente)', null=True, storage=core.storage.MinIOStorage(), upload_to=documentos.models_firmas.firma_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='revision',
            name='archivo',
            field=models.FileField(storage=core.storage.MinIOStorage(), upload_to=documentos.models.documento_upload_path),
        ),
    ]
