# Generated by Django 5.2.7 on 2026-02-06 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_revision_datos_extraidos_revision_estado_extraccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadatoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre interno del campo (ej: fecha_vencimiento)', max_length=50)),
                ('etiqueta', models.CharField(help_text='Nombre que verá el usuario (ej: Fecha de Vencimiento)', max_length=100)),
                ('tipo_campo', models.CharField(choices=[('TEXTO', 'Texto'), ('EMAIL', 'Email'), ('FECHA', 'Fecha'), ('HORA', 'Hora'), ('NUMERO', 'Número'), ('URL', 'URL')], default='TEXTO', max_length=20)),
                ('requerido', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadatos_config', to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Configuración de Metadato',
                'verbose_name_plural': 'Configuraciones de Metadatos',
                'ordering': ['orden'],
                'unique_together': {('tipo_documento', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='MetadatoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.metadatoconfig')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadatos_valores', to='documentos.documento')),
            ],
            options={
                'verbose_name': 'Valor de Metadato',
                'verbose_name_plural': 'Valores de Metadatos',
                'unique_together': {('documento', 'config')},
            },
        ),
    ]
