# Generated by Django 5.2.7 on 2026-02-06 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_metadatoconfig_metadatovalor'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='respuesta_a',
            field=models.ForeignKey(blank=True, help_text='Documento al que este archivo hace referencia o responde.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='documentos.documento', verbose_name='Respuesta a'),
        ),
    ]
