# Generated by Django 5.2.7 on 2026-02-10 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_documento_respuesta_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('posicion_x', models.FloatField(default=0, help_text='Posición X en porcentaje (0-100)')),
                ('posicion_y', models.FloatField(default=0, help_text='Posición Y en porcentaje (0-100)')),
                ('pagina', models.PositiveIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False, help_text='Marcar si el comentario ya ha sido atendido')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='documentos.documento')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_pines', to='documentos.revision')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de Documento',
                'verbose_name_plural': 'Comentarios de Documentos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
