# Generated by Django 5.2.7 on 2026-02-10 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_comentariodocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado_actual',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('COMPLETADO', 'Completado')], default='BORRADOR', max_length=20),
        ),
    ]
