# Generated by Django 5.2.7 on 2026-02-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_documento_responsable_alter_documento_estado_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariodocumento',
            name='vinculos',
            field=models.ManyToManyField(blank=True, help_text='Pines relacionados en otros documentos', to='documentos.comentariodocumento'),
        ),
    ]
