# Generated by Django 5.2.7 on 2026-02-11 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_comentariodocumento_vinculos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariodocumento',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Usuario asignado para resolver este comentario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
