# Generated by Django 5.2.7 on 2026-02-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_comentariodocumento_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariodocumento',
            name='alto',
            field=models.FloatField(default=0, help_text='Alto en porcentaje (0-100) para áreas'),
        ),
        migrations.AddField(
            model_name='comentariodocumento',
            name='ancho',
            field=models.FloatField(default=0, help_text='Ancho en porcentaje (0-100) para áreas'),
        ),
        migrations.AddField(
            model_name='comentariodocumento',
            name='tipo',
            field=models.CharField(choices=[('PIN', 'Pin (Punto)'), ('AREA', 'Área (Rectángulo)')], default='PIN', max_length=10),
        ),
    ]
