# Generated by Django 5.2.7 on 2026-02-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0011_comentariodocumento_alto_comentariodocumento_ancho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='contenido_texto',
            field=models.TextField(blank=True, help_text='Texto extraído del documento para búsquedas.', null=True, verbose_name='Contenido Texto'),
        ),
    ]
