# Generated by Django 5.2.7 on 2026-02-16 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0012_documento_contenido_texto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='N8nChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='ID de sesión para agrupar mensajes de una conversación', max_length=100)),
                ('mensaje_usuario', models.TextField(help_text='Pregunta o mensaje del usuario')),
                ('respuesta_ia', models.TextField(help_text='Respuesta generada por la IA')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tokens_usados', models.IntegerField(blank=True, help_text='Tokens consumidos en esta interacción', null=True)),
                ('modelo', models.CharField(blank=True, help_text='Modelo de IA utilizado (ej: gpt-4)', max_length=50)),
                ('documento', models.ForeignKey(blank=True, help_text='Documento sobre el que se está conversando (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_histories', to='documentos.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Chat IA',
                'verbose_name_plural': 'Historiales de Chat IA',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session_id', '-timestamp'], name='documentos__session_846f0c_idx'), models.Index(fields=['usuario', '-timestamp'], name='documentos__usuario_1e4af8_idx')],
            },
        ),
    ]
