# Generated by Django 5.2.7 on 2026-02-17 20:57

from django.conf import settings
from django.db import migrations, models
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension, BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0046_bienafecto_plano_alter_activo_foto_and_more'),
        ('documentos', '0014_enable_fulltext_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
        migrations.RenameIndex(
            model_name='documento',
            new_name='documentos__codigo_9263f0_idx',
            old_name='documentos_d_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='documento',
            new_name='documentos__estado__8f0803_idx',
            old_name='documentos_d_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='documento',
            new_name='documentos__creado__e752ba_idx',
            old_name='documentos_d_creado_idx',
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio o emisión del documento.', null=True, verbose_name='Fecha Inicio/Emisión'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha en que expira la validez del documento.', null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
