# Generated by Django 5.2.7 on 2026-02-17 20:58

from django.db import migrations


from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0015_rename_documentos_d_codigo_idx_documentos__codigo_9263f0_idx_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
