# Generated by Django 5.2.7 on 2026-02-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0016_auto_20260217_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MayanDocumentLink',
        ),
    ]
