# Generated by Django 5.2.7 on 2026-02-18 07:10

import core.storage
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0017_delete_mayandocumentlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='archivo',
            field=models.FileField(max_length=255, storage=core.storage.MinIOStorage(), upload_to=documentos.models.documento_upload_path),
        ),
    ]
