# Generated by Django 5.1.15 on 2026-02-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0019_add_biblioteca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado_actual',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En Proceso'), ('NO_CONTESTADO', 'No Contestado'), ('COMPLETADO', 'Completado')], default='RECIBIDO', max_length=20),
        ),
    ]
