# Generated by Django 5.1.15 on 2026-03-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0020_alter_documento_estado_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatoconfig',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text="Instrucciones para la IA: dónde o cómo extraer este campo del documento (ej: 'Buscar en el encabezado, después de Asunto:')"),
        ),
    ]
