# Generated by Django 5.2.7 on 2026-03-03 16:07

import core.storage
import django.db.models.deletion
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0021_add_descripcion_to_metadatoconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(storage=core.storage.MinIOStorage(), upload_to=documentos.models.comentario_imagen_path)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='documentos.comentariodocumento')),
            ],
            options={
                'verbose_name': 'Imagen de Comentario',
                'verbose_name_plural': 'Imágenes de Comentarios',
            },
        ),
    ]
