# Generated by Django 5.1.15 on 2026-03-03 23:24

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0022_comentarioimagen'),
    ]

    operations = [
        # Habilitar la extensión pgvector antes de crear columnas de tipo vector.
        # Idempotente: IF NOT EXISTS no falla si ya está instalada.
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='documento',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
