# Generated by Django 5.1.15 on 2026-03-03 23:24

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0022_comentarioimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
