# Generated by Django 5.2.7 on 2026-03-04 00:34

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0023_documento_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFragmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='documentos.documento')),
            ],
            options={
                'verbose_name': 'Fragmento de Documento',
                'verbose_name_plural': 'Fragmentos de Documentos',
                'ordering': ['documento', 'orden'],
                'indexes': [models.Index(fields=['documento'], name='documentos__documen_8a37dd_idx')],
            },
        ),
    ]
