# Generated by Django 5.2.7 on 2026-03-04 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documentos', '0024_documentofragmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatoconfig',
            name='modelo_relativo',
            field=models.ForeignKey(blank=True, help_text='Si el tipo es RELACION, seleccione a qué tabla apunta.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='metadatovalor',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='metadatovalor',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
