# Generated by Django 5.2.7 on 2026-03-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0025_metadatoconfig_modelo_relativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatoconfig',
            name='tipo_campo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('EMAIL', 'Email'), ('FECHA', 'Fecha'), ('HORA', 'Hora'), ('NUMERO', 'Número'), ('URL', 'URL'), ('RELACION', 'Relación con otro Modelo')], default='TEXTO', max_length=20),
        ),
    ]
