# Generated by Django 5.2.7 on 2026-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0026_alter_metadatoconfig_tipo_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatoconfig',
            name='campo_visualizacion',
            field=models.CharField(blank=True, default='', help_text="Si el tipo es RELACION, nombre del campo a mostrar (ej: 'nombre', 'codigo'). Dejar vacío para usar el valor por defecto.", max_length=50),
        ),
    ]
