# Generated by Django 5.2.12 on 2026-03-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0027_metadatoconfig_campo_visualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='resumen_ia',
            field=models.TextField(blank=True, help_text='Resultado guardado del análisis automatizado de todos los documentos.', null=True, verbose_name='Resumen IA'),
        ),
    ]
