# Generated by Django 5.2.12 on 2026-03-10 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0028_biblioteca_resumen_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='documentos.biblioteca')),
            ],
            options={
                'verbose_name': 'Comentario de Biblioteca',
                'verbose_name_plural': 'Comentarios de Biblioteca',
                'ordering': ['-fecha'],
            },
        ),
    ]
