# Generated by Django 5.2.12 on 2026-04-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0029_comentariobiblioteca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariodocumento',
            name='tipo',
            field=models.CharField(choices=[('PIN', 'Pin (Punto)'), ('AREA', 'Área (Rectángulo)'), ('TAREA', 'Tarea (Checkbox)')], default='PIN', max_length=10),
        ),
    ]
