# Generated by Django 5.2.12 on 2026-04-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_seed_elementoapp'),
        ('documentos', '0031_carpeta_documento_carpeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='departamentos',
            field=models.ManyToManyField(blank=True, help_text='Si se asignan departamentos, solo los usuarios de esos departamentos verán esta carpeta.', related_name='carpetas_documentos', to='core.departamento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='departamentos',
            field=models.ManyToManyField(blank=True, help_text='Si se asignan departamentos, solo los usuarios de esos departamentos verán este documento.', related_name='documentos_asignados', to='core.departamento'),
        ),
    ]
