# Generated by Django 5.2.12 on 2026-05-11 22:02

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0032_carpeta_departamentos_documento_departamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='documentofragmento',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
