# Generated by Django 6.0.6 on 2026-06-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0033_alter_documento_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroqApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Ej: Producción, Desarrollo, Cliente A', max_length=100, verbose_name='Nombre')),
                ('api_key', models.CharField(max_length=200, verbose_name='API Key')),
                ('modelo', models.CharField(default='llama-3.3-70b-versatile', max_length=100, verbose_name='Modelo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Las claves activas se rotan en orden', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Key de Groq',
                'verbose_name_plural': 'API Keys de Groq',
                'ordering': ['orden', 'created_at'],
            },
        ),
    ]
