# Generated by Django 6.0.6 on 2026-07-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0034_groqapikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groqapikey',
            options={'ordering': ['orden', 'created_at'], 'verbose_name': 'API Key de IA', 'verbose_name_plural': 'API Keys de IA'},
        ),
        migrations.AddField(
            model_name='groqapikey',
            name='proveedor',
            field=models.CharField(choices=[('groq', 'Groq'), ('google', 'Google (Gemini)'), ('cohere', 'Cohere'), ('openrouter', 'OpenRouter')], default='groq', max_length=20, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='groqapikey',
            name='modelo',
            field=models.CharField(default='llama-3.3-70b-versatile', help_text='Groq: llama-3.3-70b-versatile | Google: gemini-1.5-flash | Cohere: command-r-08-2024', max_length=100, verbose_name='Modelo'),
        ),
    ]
