# Generated by Django 5.2.12 on 2026-03-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(default='fas fa-question-circle', help_text='Clase de FontAwesome (ej. fas fa-warehouse)', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de Ayuda',
                'verbose_name_plural': 'Categorías de Ayuda',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ArticuloAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('contenido', models.TextField(help_text='Contenido en formato Markdown')),
                ('video_url', models.URLField(blank=True, help_text='URL opcional de video (YouTube/Vimeo)', null=True)),
                ('app_label', models.CharField(blank=True, help_text='App label del admin (ej. callcenter)', max_length=100)),
                ('model_name', models.CharField(blank=True, help_text='Nombre del modelo (ej. solicitudticket)', max_length=100)),
                ('es_contextual', models.BooleanField(default=False, help_text='Priorizar este artículo cuando se navega en el modelo indicado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='ayuda.categoriaayuda')),
            ],
            options={
                'verbose_name': 'Artículo de Ayuda',
                'verbose_name_plural': 'Artículos de Ayuda',
            },
        ),
    ]
