# Generated by Django 5.2.12 on 2026-05-30 14:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0023_alter_solicitudmaterial_estado'),
        ('proyectos', '0010_alter_documentoproyecto_carpeta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCostoUnitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código único (se genera auto: ACU-YYYY-NNNN)', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre / Concepto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del análisis')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('OBSOLETO', 'Obsoleto')], default='BORRADOR', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_costos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_costos_creados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_costos', to='proyectos.proyecto', verbose_name='Proyecto asociado')),
                ('unidad', models.ForeignKey(help_text='Ej: m², m³, pieza, hora, global', on_delete=django.db.models.deletion.PROTECT, related_name='analisis_costos', to='inventarios.unidadmedida', verbose_name='Unidad de Medida del ACU')),
            ],
            options={
                'verbose_name': 'Análisis de Costo Unitario',
                'verbose_name_plural': 'Análisis de Costos Unitarios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCostoUnitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(choices=[('MATERIAL', 'Material'), ('REPUESTO', 'Repuesto'), ('MANO_OBRA', 'Mano de Obra'), ('EQUIPO', 'Equipo / Maquinaria'), ('HERRAMIENTA', 'Herramienta'), ('SUBCONTRATO', 'Subcontrato'), ('OTRO', 'Otro')], default='MATERIAL', max_length=20, verbose_name='Tipo de Recurso')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='Descripción (si no es del catálogo)')),
                ('cantidad', models.DecimalField(decimal_places=4, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Cantidad por unidad de obra')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Unitario')),
                ('factor_rendimiento', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='1.0 = rendimiento nominal. <1 = más eficiente. >1 = desperdicio/ineficiencia.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Factor de Rendimiento')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='costos.analisiscostounitario')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_acu', to='inventarios.material', verbose_name='Material / Repuesto (del catálogo)')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_acu', to='inventarios.unidadmedida', verbose_name='Unidad del recurso')),
            ],
            options={
                'verbose_name': 'Detalle de Recurso',
                'verbose_name_plural': 'Detalles de Recursos',
                'ordering': ['analisis', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FactorCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del factor')),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('MONTO_FIJO', 'Monto Fijo')], default='PORCENTAJE', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, help_text='% si es porcentaje, monto si es fijo', max_digits=10, verbose_name='Valor')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores', to='costos.analisiscostounitario')),
            ],
            options={
                'verbose_name': 'Factor de Costo Indirecto',
                'verbose_name_plural': 'Factores de Costo Indirecto',
                'ordering': ['analisis', 'orden', 'id'],
            },
        ),
    ]
