# Generated by Django 5.2.7 on 2026-01-08 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0027_activo_padre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada')], default='BORRADOR', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='auditorias', to='activos.categoria')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ubicaciones', models.ManyToManyField(blank=True, related_name='auditorias', to='activos.ubicacion')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
            },
        ),
        migrations.CreateModel(
            name='ResultadoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENCONTRADO', 'Encontrado (Correcto)'), ('UBICACION_ERRONEA', 'Ubicación Errónea'), ('EXTRAVIADO', 'Extraviado'), ('NO_PERTENECE', 'No pertenece a la Auditoría')], default='PENDIENTE', max_length=30)),
                ('fecha_escaneo', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_participadas', to='activos.activo')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='auditorias.auditoria')),
                ('ubicacion_encontrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_reales', to='activos.ubicacion')),
                ('ubicacion_esperada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_esperados', to='activos.ubicacion')),
            ],
            options={
                'verbose_name': 'Resultado de Auditoría',
                'verbose_name_plural': 'Resultados de Auditoría',
            },
        ),
    ]
