# Generated by Django 5.2.7 on 2026-01-23 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoauditoria',
            name='fecha_sincronizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadoauditoria',
            name='sincronizado',
            field=models.BooleanField(default=False, verbose_name='¿Movimiento Sincronizado?'),
        ),
        migrations.AddField(
            model_name='resultadoauditoria',
            name='sincronizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizaciones_auditoria', to=settings.AUTH_USER_MODEL),
        ),
    ]
