# Generated by Django 5.2.12 on 2026-04-27 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0070_downtimeactivo_aviso_and_more'),
        ('auditorias', '0002_resultadoauditoria_fecha_sincronizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='tipo',
            field=models.CharField(choices=[('ACTIVOS', 'Por Activo (Escaneo Individual)'), ('CONTEO', 'Por Conteo (Masivo por Categoría)')], default='ACTIVOS', max_length=20),
        ),
        migrations.CreateModel(
            name='ConteoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_esperada', models.PositiveIntegerField(default=0)),
                ('cantidad_encontrada', models.PositiveIntegerField(default=0)),
                ('fecha_conteo', models.DateTimeField(blank=True, null=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos', to='auditorias.auditoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.categoria')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.ubicacion')),
                ('usuario_conteo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conteo de Auditoría',
                'verbose_name_plural': 'Conteos de Auditoría',
                'unique_together': {('auditoria', 'ubicacion', 'categoria')},
            },
        ),
    ]
