# Generated by Django 5.2.12 on 2026-04-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0003_auditoria_tipo_conteoauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteoauditoria',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
