# Generated by Django 5.2.12 on 2026-04-27 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0070_downtimeactivo_aviso_and_more'),
        ('auditorias', '0004_conteoauditoria_observaciones'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conteoauditoria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conteoauditoria',
            name='modelo',
            field=models.ForeignKey(blank=True, help_text='Modelo específico de activo (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteos_auditoria', to='activos.modelo'),
        ),
        migrations.AlterUniqueTogether(
            name='conteoauditoria',
            unique_together={('auditoria', 'ubicacion', 'categoria', 'modelo')},
        ),
    ]
