# Generated by Django 5.2.7 on 2026-02-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='valor_actual',
        ),
        migrations.AddField(
            model_name='kpi',
            name='categoria',
            field=models.CharField(choices=[('MEJORA', 'Mejora'), ('MAYOR', 'Mayor')], default='MAYOR', max_length=20),
        ),
        migrations.AddField(
            model_name='kpi',
            name='forma_de_cumplimiento',
            field=models.TextField(default='Migrado', help_text='Forma de cumplimiento (Texto)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpi',
            name='metodo_de_supervision',
            field=models.TextField(default='Migrado', help_text='Método de Supervisión (Texto)'),
            preserve_default=False,
        ),
    ]
