# Generated by Django 5.2.7 on 2026-02-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_remove_kpi_descripcion_remove_kpi_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='nombre',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
