# Generated by Django 5.2.7 on 2026-02-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_add_nombre_to_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
