# Generated by Django 5.2.7 on 2026-02-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_add_descripcion_to_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='forma_de_cumplimiento',
            field=models.TextField(blank=True, default='', help_text='Forma de cumplimiento (Texto)'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='metodo_de_supervision',
            field=models.TextField(blank=True, default='', help_text='Método de Supervisión (Texto)'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
