# Generated by Django 5.1.15 on 2026-02-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_kpi_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='estado',
            field=models.CharField(choices=[('CUMPLIMIENTO', 'En Cumplimiento'), ('PARCIAL', 'Cumplimiento Parcial'), ('INCUMPLIMIENTO', 'Incumplimiento')], default='CUMPLIMIENTO', max_length=20),
        ),
    ]
