# Generated by Django 5.1.15 on 2026-02-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_kpi_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='categoria',
            field=models.CharField(choices=[('MAYOR', 'Mayor'), ('MEDIA', 'Media'), ('MENOR', 'Menor')], default='MAYOR', max_length=20),
        ),
    ]
