# Generated by Django 5.1.15 on 2026-02-27 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_alter_kpi_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('completado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='servicios.kpi')),
            ],
            options={
                'verbose_name': 'Elemento de Checklist',
                'verbose_name_plural': 'Elementos de Checklist',
                'ordering': ['orden'],
            },
        ),
    ]
