# Generated by Django 5.2.12 on 2026-03-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0058_fotoaviso_descripcion'),
        ('servicios', '0008_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='rutinas',
            field=models.ManyToManyField(blank=True, help_text='Rutinas de mantenimiento vinculadas a este KPI', related_name='kpis', to='mantenimiento.rutina'),
        ),
    ]
