# Generated by Django 5.2.12 on 2026-03-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_add_rutinas_m2m_to_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='comentarios',
            field=models.TextField(blank=True, default='', verbose_name='Comentarios adicionales'),
        ),
    ]
