# Generated by Django 5.2.12 on 2026-03-25 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_add_comentarios_to_kpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la auditoría (Ej: Auditoría Trimestral Q1 2026)', max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumple', models.BooleanField(default=True, verbose_name='¿Cumple?')),
                ('plan_de_accion', models.TextField(blank=True, default='', verbose_name='Plan de Acción')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='servicios.auditoria')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_auditoria', to='servicios.kpi')),
            ],
            options={
                'verbose_name': 'Resultado de Auditoría',
                'verbose_name_plural': 'Resultados de Auditoría',
                'unique_together': {('auditoria', 'kpi')},
            },
        ),
    ]
