# Generated by Django 5.2.12 on 2026-05-08 16:06

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_add_auditoria_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.CreateModel(
            name='KPIFragmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Texto compuesto del KPI para búsqueda semántica')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='servicios.kpi')),
            ],
            options={
                'verbose_name': 'Fragmento de KPI',
                'verbose_name_plural': 'Fragmentos de KPIs',
                'ordering': ['kpi', 'orden'],
                'indexes': [models.Index(fields=['kpi'], name='servicios_k_kpi_id_5a1750_idx')],
            },
        ),
    ]
