# Generated by Django 6.0.6 on 2026-06-26 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0082_ordentrabajo_proyecto'),
        ('servicios', '0013_kpiarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='frecuencia_supervision',
            field=models.ForeignKey(blank=True, help_text='Frecuencia con la que se supervisa este KPI', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.frecuencia', verbose_name='Frecuencia de Supervisión'),
        ),
    ]
