# Generated by Django 6.0.6 on 2026-07-30 22:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_kpi_frecuencia_supervision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRiesgoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apetito_riesgo', models.IntegerField(default=9, help_text='Nivel de riesgo máximo aceptable (1-25)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('tolerancia_offset', models.IntegerField(default=3, help_text='Offset de tolerancia por encima del apetito (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_riesgo', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Configuración de Riesgo por Servicio',
                'verbose_name_plural': 'Configuraciones de Riesgo por Servicio',
            },
        ),
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrategia', models.CharField(choices=[('MITIGAR', 'Mitigar'), ('TRANSFERIR', 'Transferir'), ('EVITAR', 'Evitar'), ('ACEPTAR', 'Aceptar')], max_length=15)),
                ('descripcion_acciones', models.TextField(max_length=2000)),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('recursos_requeridos', models.TextField(max_length=1000)),
                ('justificacion_aceptacion', models.TextField(blank=True, default='', max_length=2000)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('EN_EJECUCION', 'En Ejecución'), ('IMPLEMENTADO', 'Implementado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=15)),
                ('nivel_riesgo_esperado', models.IntegerField(blank=True, help_text='Nivel de riesgo esperado tras implementación del plan (1-25)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_tratamiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Tratamiento',
                'verbose_name_plural': 'Planes de Tratamiento',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AccionTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_tratamiento', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='servicios.plantratamiento')),
            ],
            options={
                'verbose_name': 'Acción de Tratamiento',
                'verbose_name_plural': 'Acciones de Tratamiento',
                'ordering': ['fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=2000)),
                ('categoria', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('FINANCIERO', 'Financiero'), ('ESTRATEGICO', 'Estratégico'), ('CUMPLIMIENTO', 'Cumplimiento'), ('REPUTACIONAL', 'Reputacional')], max_length=20)),
                ('fuente_riesgo', models.CharField(max_length=500)),
                ('consecuencias', models.TextField(max_length=1000)),
                ('control_existente', models.TextField(blank=True, default='', max_length=1000)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='ACTIVO', max_length=10)),
                ('estado_apetito', models.CharField(choices=[('ACEPTABLE', 'Aceptable'), ('EN_VIGILANCIA', 'En Vigilancia'), ('REQUIERE_ACCION', 'Requiere Acción Inmediata')], default='ACEPTABLE', max_length=20)),
                ('estado_revision', models.CharField(choices=[('AL_DIA', 'Al día'), ('PROXIMA', 'Próxima revisión'), ('VENCIDA', 'Revisión vencida')], default='AL_DIA', max_length=10)),
                ('ciclo_revision', models.CharField(choices=[('MENSUAL', 'Mensual (30 días)'), ('BIMESTRAL', 'Bimestral (60 días)'), ('TRIMESTRAL', 'Trimestral (90 días)'), ('SEMESTRAL', 'Semestral (180 días)'), ('ANUAL', 'Anual (365 días)')], default='TRIMESTRAL', max_length=15)),
                ('proxima_revision', models.DateField(blank=True, null=True)),
                ('fecha_identificacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgos_creados', to=settings.AUTH_USER_MODEL)),
                ('kpis', models.ManyToManyField(blank=True, related_name='riesgos_asociados', to='servicios.kpi')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgos_asignados', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Riesgo',
                'verbose_name_plural': 'Riesgos',
                'ordering': ['-fecha_identificacion'],
                'permissions': [('approve_plantratamiento', 'Puede aprobar planes de tratamiento'), ('configure_apetito', 'Puede configurar apetito y tolerancia')],
            },
        ),
        migrations.CreateModel(
            name='RevisionRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad_anterior', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impacto_anterior', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('probabilidad_nueva', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impacto_nueva', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('justificacion', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='servicios.riesgo')),
            ],
            options={
                'verbose_name': 'Revisión de Riesgo',
                'verbose_name_plural': 'Revisiones de Riesgo',
                'ordering': ['-fecha_revision'],
            },
        ),
        migrations.AddField(
            model_name='plantratamiento',
            name='riesgo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tratamiento', to='servicios.riesgo'),
        ),
        migrations.CreateModel(
            name='EvaluacionRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INHERENTE', 'Riesgo Inherente'), ('RESIDUAL', 'Riesgo Residual')], max_length=10)),
                ('probabilidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impacto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nivel_riesgo', models.IntegerField(default=0, editable=False)),
                ('zona_riesgo', models.CharField(default='BAJO', editable=False, max_length=10)),
                ('justificacion_probabilidad', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('justificacion_impacto', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='servicios.riesgo')),
            ],
            options={
                'verbose_name': 'Evaluación de Riesgo',
                'verbose_name_plural': 'Evaluaciones de Riesgo',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='RiesgoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CREACION', 'Creación'), ('EVALUACION', 'Evaluación'), ('TRATAMIENTO', 'Cambio de tratamiento'), ('REVISION', 'Revisión periódica'), ('ESTADO', 'Cambio de estado'), ('KPI_VINCULADO', 'KPI vinculado'), ('KPI_DESVINCULADO', 'KPI desvinculado')], max_length=20)),
                ('valores_anteriores', models.JSONField(blank=True, default=dict)),
                ('valores_nuevos', models.JSONField(blank=True, default=dict)),
                ('justificacion', models.TextField(blank=True, default='')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='servicios.riesgo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Riesgo',
                'verbose_name_plural': 'Historial de Riesgos',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
