# Generated by Django 5.2.7 on 2025-12-30 22:00

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0002_documentofirmado_firma_auditoriafirmas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_proyectado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Proyectado (Anual)')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='Referencia/Nota')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_presupuestarias', to='documentos.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Partida por Disciplina',
                'verbose_name_plural': 'Partidas por Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='GastoEjecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Concepto de Gasto')),
                ('referencia', models.CharField(blank=True, help_text='N° de Factura, OC o similar', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='presupuestos.partidapresupuestaria')),
            ],
            options={
                'verbose_name': 'Gasto Ejecutado',
                'verbose_name_plural': 'Gastos Ejecutados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Plan')),
                ('anio', models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('moneda', models.CharField(choices=[('DOP', 'Peso Dominicano'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro')], default='DOP', max_length=10)),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'En Planificación'), ('APROBADO', 'Aprobado / Activo'), ('CERRADO', 'Cerrado')], default='PLANIFICACION', max_length=20)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('elaborado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_presupuestarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presupuesto Anual',
                'verbose_name_plural': 'Presupuestos Anuales',
                'ordering': ['-anio', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='partidapresupuestaria',
            name='presupuesto_anual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='presupuestos.presupuestoanual'),
        ),
        migrations.AlterUniqueTogether(
            name='partidapresupuestaria',
            unique_together={('presupuesto_anual', 'disciplina')},
        ),
    ]
