# Generated by Django 5.2.7 on 2026-01-03 06:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoanual',
            name='anio',
            field=models.PositiveIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Año'),
        ),
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto/Descripción')),
                ('ene', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('abr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jun', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sep', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('oct', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nov', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dic', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presupuestos.partidapresupuestaria')),
            ],
            options={
                'verbose_name': 'Ítem de Presupuesto',
                'verbose_name_plural': 'Ítems de Presupuesto',
            },
        ),
    ]
