# Generated by Django 5.2.7 on 2026-01-04 02:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_alter_presupuestoanual_anio_itempresupuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Contrato/OC')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Proveedor / Contratista')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='N° Referencia (OC/Contrato)')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado / Emitido'), ('CERRADO', 'Cerrado / Completado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compromiso (Contrato/OC)',
                'verbose_name_plural': 'Compromisos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='gastoejecutado',
            options={'ordering': ['-fecha'], 'verbose_name': 'Gasto Ejecutado (Factura)', 'verbose_name_plural': 'Gastos Ejecutados (Facturas)'},
        ),
        migrations.AlterField(
            model_name='partidapresupuestaria',
            name='monto_proyectado',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Original (Aprobado)'),
        ),
        migrations.CreateModel(
            name='CambioPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Use negativo para reducciones', max_digits=12)),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Interna'), ('ADICIONAL', 'Presupuesto Adicional'), ('REDUCCION', 'Reducción / Ajuste')], default='ADICIONAL', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_solicitud', models.DateField(default=datetime.datetime.now)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='presupuestos.partidapresupuestaria')),
            ],
            options={
                'verbose_name': 'Cambio de Presupuesto',
                'verbose_name_plural': 'Cambios de Presupuesto',
            },
        ),
        migrations.AddField(
            model_name='gastoejecutado',
            name='compromiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_vinculados', to='presupuestos.compromiso', verbose_name='Compromiso Relacionado'),
        ),
        migrations.CreateModel(
            name='DetalleCompromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_comprometido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('compromiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='presupuestos.compromiso')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compromiso', to='presupuestos.partidapresupuestaria')),
            ],
            options={
                'verbose_name': 'Detalle de Compromiso',
                'verbose_name_plural': 'Detalles de Compromisos',
            },
        ),
    ]
