# Generated by Django 5.2.7 on 2026-01-04 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_compromiso_alter_gastoejecutado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempresupuesto',
            name='es_recurrente',
            field=models.BooleanField(default=False, verbose_name='¿Es Recurrente?'),
        ),
        migrations.AddField(
            model_name='itempresupuesto',
            name='frecuencia',
            field=models.CharField(choices=[('MENSUAL', 'Mensual (Todos los meses)'), ('BIMESTRAL', 'Bimestral (Cada 2 meses)'), ('TRIMESTRAL', 'Trimestral (Cada 3 meses)'), ('CUATRIMESTRAL', 'Cuatrimestral (Cada 4 meses)'), ('SEMESTRAL', 'Semestral (Cada 6 meses)'), ('ANUAL', 'Anual (Una vez al año)'), ('MANUAL', 'Manual (Definir mes a mes)')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='itempresupuesto',
            name='mes_inicio',
            field=models.PositiveIntegerField(default=1, help_text='Mes de comienzo (1=Enero, 12=Diciembre)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='itempresupuesto',
            name='monto_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto para cada ocurrencia', max_digits=12),
        ),
    ]
