# Generated by Django 5.2.7 on 2026-01-04 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_itempresupuesto_es_recurrente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='abr',
        ),
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='ago',
        ),
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='dic',
        ),
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='ene',
        ),
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='feb',
        ),
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='jul',
        ),
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='jun',
        ),
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='mar',
        ),
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='may',
        ),
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='nov',
        ),
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='oct',
        ),
        migrations.RemoveField(
            model_name='itempresupuesto',
            name='sep',
        ),
        migrations.CreateModel(
            name='DetallePeriodico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='presupuestos.itempresupuesto')),
            ],
            options={
                'verbose_name': 'Detalle Periódico',
                'verbose_name_plural': 'Detalles Periódicos',
                'ordering': ['mes'],
                'unique_together': {('item', 'mes')},
            },
        ),
    ]
