# Generated by Django 5.2.7 on 2026-01-07 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0005_remove_itempresupuesto_abr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoanual',
            name='moneda',
            field=models.CharField(choices=[('DOP', 'Pesos Dominicanos (DOP)'), ('USD', 'Dólares (USD)'), ('HNL', 'Lempiras (HNL)'), ('EUR', 'Euro')], default='DOP', max_length=10),
        ),
        migrations.CreateModel(
            name='PresupuestoAgrupado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Grupo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Notas')),
                ('anio', models.PositiveIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Año de Referencia')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('presupuestos', models.ManyToManyField(related_name='agrupaciones', to='presupuestos.presupuestoanual', verbose_name='Presupuestos Incluidos')),
            ],
            options={
                'verbose_name': 'Presupuesto Agrupado',
                'verbose_name_plural': 'Presupuestos Agrupados',
                'ordering': ['-anio', 'nombre'],
            },
        ),
    ]
