# Generated by Django 5.2.7 on 2026-01-07 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0006_alter_presupuestoanual_moneda_presupuestoagrupado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempresupuesto',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='presupuestos.itempresupuesto', verbose_name='Item Padre'),
        ),
    ]
