# Generated by Django 5.2.7 on 2026-01-13 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0007_itempresupuesto_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('cr8ca_requisicionid', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID de Requisición (Dynamics)')),
                ('cr8ca_requisicion', models.CharField(max_length=100, verbose_name='N° Requisición (REQ-#####-AAAA)')),
                ('cr8ca_asunto', models.CharField(max_length=500, verbose_name='Asunto')),
                ('cr8ca_motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('cr8ca_comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('cr8ca_totalenarticulos', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total en Artículos')),
                ('cr8ca_prioridad', models.IntegerField(blank=True, null=True, verbose_name='Prioridad (Code)')),
                ('cr8ca_tipodedocumento', models.IntegerField(blank=True, null=True, verbose_name='Tipo de Documento')),
                ('cr8ca_estatusorden', models.IntegerField(blank=True, null=True, verbose_name='Estatus Orden')),
                ('cr8ca_accion', models.IntegerField(blank=True, null=True, verbose_name='Acción')),
                ('cr8ca_ejecutado', models.BooleanField(default=False)),
                ('cr8ca_cerrar', models.BooleanField(default=False)),
                ('cr8ca_cajachica', models.BooleanField(default=False)),
                ('cr8ca_solicituddetabladepago', models.BooleanField(default=False)),
                ('cr8ca_seleccionar', models.BooleanField(default=True)),
                ('_cr8ca_presupuesto_value', models.UUIDField(blank=True, null=True)),
                ('_cr8ca_proyecto_value', models.UUIDField(blank=True, null=True)),
                ('_cr8ca_area_value', models.UUIDField(blank=True, null=True)),
                ('_cr8ca_categoria_value', models.UUIDField(blank=True, null=True)),
                ('_cr8ca_departamento_value', models.UUIDField(blank=True, null=True)),
                ('_cr8ca_proveedorasignado_value', models.UUIDField(blank=True, null=True)),
                ('_cr8ca_solicita_value', models.UUIDField(blank=True, null=True)),
                ('_cr8ca_autoriza_value', models.UUIDField(blank=True, null=True)),
                ('_cr8ca_reviso_value', models.UUIDField(blank=True, null=True)),
                ('_ownerid_value', models.UUIDField(blank=True, null=True)),
                ('cr8ca_fechadegasto', models.DateTimeField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True, verbose_name='Creado en Dynamics')),
                ('modifiedon', models.DateTimeField(blank=True, null=True, verbose_name='Modificado en Dynamics')),
                ('versionnumber', models.BigIntegerField(blank=True, null=True)),
                ('statecode', models.IntegerField(blank=True, null=True)),
                ('statuscode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Requisición',
                'verbose_name_plural': 'Requisiciones',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='ArticuloRequisicion',
            fields=[
                ('cr8ca_itemderequisicionid', models.UUIDField(primary_key=True, serialize=False)),
                ('cr8ca_articulo', models.CharField(max_length=500, verbose_name='Descripción del Artículo')),
                ('cr8ca_cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cr8ca_costoaproximado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cr8ca_costoaproximado_base', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cr8ca_tipo', models.IntegerField(blank=True, null=True)),
                ('_cr8ca_edificiozona_value', models.UUIDField(blank=True, null=True)),
                ('_cr8ca_activo_value', models.UUIDField(blank=True, null=True)),
                ('_cr8ca_catalogo_value', models.UUIDField(blank=True, null=True)),
                ('_cr8ca_unidad_value', models.UUIDField(blank=True, null=True)),
                ('versionnumber', models.BigIntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('modifiedon', models.DateTimeField(blank=True, null=True)),
                ('exchangerate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='presupuestos.requisicion', verbose_name='Requisición')),
            ],
            options={
                'verbose_name': 'Artículo de Requisición',
                'verbose_name_plural': 'Artículos de Requisición',
            },
        ),
    ]
