# Generated by Django 5.2.7 on 2026-01-13 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_alter_movimientoinventario_options_and_more'),
        ('presupuestos', '0008_requisicion_articulorequisicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulorequisicion',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones', to='inventarios.material', verbose_name='Material vinculado'),
        ),
    ]
