# Generated by Django 5.2.7 on 2026-01-27 18:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0009_articulorequisicion_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicion',
            name='cr8ca_requisicion',
            field=models.CharField(editable=False, max_length=100, verbose_name='N° Requisición (REQ-#####-AAAA)'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='cr8ca_requisicionid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID de Requisición (Dynamics)'),
        ),
    ]
