# Generated by Django 5.2.7 on 2026-01-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0010_alter_requisicion_cr8ca_requisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicion',
            name='cr8ca_prioridad',
            field=models.IntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgencia'), (5, 'Emerencia')], default=2, null=True, verbose_name='Prioridad'),
        ),
    ]
