# Generated by Django 5.2.7 on 2026-01-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0011_alter_requisicion_cr8ca_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRequisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='requisiciones/%Y/%m/', verbose_name='Archivo')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre/Descripción del Documento')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='presupuestos.requisicion', verbose_name='Requisición')),
            ],
            options={
                'verbose_name': 'Documento de Requisición',
                'verbose_name_plural': 'Documentos de Requisición',
                'ordering': ['-creado_en'],
            },
        ),
    ]
