# Generated by Django 5.2.7 on 2026-02-02 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0012_documentorequisicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulorequisicion',
            name='cr8ca_cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='articulorequisicion',
            name='cr8ca_costoaproximado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Costo Aprox.'),
        ),
        migrations.AlterField(
            model_name='articulorequisicion',
            name='cr8ca_itemderequisicionid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
