# Generated by Django 5.2.7 on 2026-02-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0013_alter_articulorequisicion_cr8ca_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='cr8ca_id_oc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID OC (Orden de Compra)'),
        ),
    ]
