# Generated by Django 5.2.7 on 2026-02-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0014_requisicion_cr8ca_id_oc'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
