# Generated by Django 5.2.7 on 2026-02-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0015_requisicion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicion',
            name='cr8ca_requisicion',
            field=models.CharField(max_length=100, unique=True, verbose_name='N° Requisición (REQ-#####-AAAA)'),
        ),
    ]
