# Generated by Django 5.2.7 on 2026-02-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0016_alter_requisicion_cr8ca_requisicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulorequisicion',
            name='wizard_step',
            field=models.IntegerField(default=1, verbose_name='Paso del Wizard'),
        ),
    ]
