# Generated by Django 5.2.7 on 2026-02-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0017_articulorequisicion_wizard_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulorequisicion',
            name='wizard_step',
        ),
        migrations.AddField(
            model_name='requisicion',
            name='wizard_step',
            field=models.IntegerField(default=1, verbose_name='Paso del Wizard'),
        ),
    ]
