# Generated by Django 5.2.7 on 2026-02-05 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0019_requisicion_usuario_solicitante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='usuario_en_nombre_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_en_nombre_de', to=settings.AUTH_USER_MODEL, verbose_name='En nombre de'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='usuario_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
    ]
