# Generated by Django 5.2.7 on 2026-02-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0020_requisicion_usuario_en_nombre_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='estado_requisicion',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'En espera de autorización'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=50, verbose_name='Estado de la Requisición'),
        ),
    ]
