# Generated by Django 5.2.7 on 2026-02-06 03:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0021_requisicion_estado_requisicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulorequisicion',
            name='cr8ca_itemderequisicionid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
