# Generated by Django 5.2.7 on 2026-02-06 14:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0022_alter_articulorequisicion_cr8ca_itemderequisicionid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción Global/Referencia')),
                ('fecha_solicitud', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Solicitud')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_pago', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Pago',
                'verbose_name_plural': 'Solicitudes de Pago',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitudPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Solicitado')),
                ('descripcion', models.CharField(help_text='Ej: Anticipo, Pago Parcial, Pago Final', max_length=500, verbose_name='Descripción del Pago')),
                ('estatus', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('PAGADO', 'Pagado'), ('POSPUESTO', 'Pospuesto'), ('RECHAZADO', 'Rechazado')], default='SOLICITADO', max_length=20, verbose_name='Estatus del Item')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pago', to='presupuestos.requisicion', verbose_name='Requisición Vinculada')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presupuestos.solicitudpago', verbose_name='Solicitud Padre')),
            ],
            options={
                'verbose_name': 'Ítem de Solicitud de Pago',
                'verbose_name_plural': 'Ítems de Solicitud de Pago',
            },
        ),
    ]
