# Generated by Django 5.2.7 on 2026-02-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0023_solicitudpago_itemsolicitudpago'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemsolicitudpago',
            unique_together={('solicitud', 'requisicion')},
        ),
    ]
