# Generated by Django 5.2.7 on 2026-02-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0024_alter_itemsolicitudpago_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolicitudpago',
            name='condicion_pago',
            field=models.CharField(blank=True, choices=[('CONTADO', 'Al Contado'), ('ANTICIPO', 'Anticipo'), ('DIFERIDO', 'Diferido'), ('CREDITO', 'A Plazos / Crédito'), ('CONTRA_ENTREGA', 'Contra Entrega')], max_length=20, null=True, verbose_name='Condición de Pago'),
        ),
    ]
