# Generated by Django 5.2.7 on 2026-02-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0025_itemsolicitudpago_condicion_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpago',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_REVISION', 'En Revisión'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20),
        ),
    ]
