# Generated by Django 5.2.7 on 2026-02-06 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0043_alter_tecnicopuesto_puesto'),
        ('presupuestos', '0026_alter_solicitudpago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_asignadas', to='mantenimiento.empresa', verbose_name='Proveedor Asignado'),
        ),
    ]
