# Generated by Django 5.2.7 on 2026-02-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0027_requisicion_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicion',
            name='_cr8ca_area_value',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='_cr8ca_autoriza_value',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='_cr8ca_categoria_value',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='_cr8ca_departamento_value',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='_cr8ca_presupuesto_value',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='_cr8ca_proveedorasignado_value',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='_cr8ca_proyecto_value',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='_cr8ca_reviso_value',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='_cr8ca_solicita_value',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='cr8ca_accion',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='cr8ca_estatusorden',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='cr8ca_tipodedocumento',
        ),
    ]
