# Generated by Django 5.2.7 on 2026-02-09 20:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0028_remove_requisicion__cr8ca_area_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulorequisicion',
            name='cr8ca_itemderequisicionid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
