# Generated by Django 5.2.7 on 2026-02-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0029_alter_articulorequisicion_cr8ca_itemderequisicionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='proveedores_sugeridos',
            field=models.TextField(blank=True, null=True, verbose_name='Proveedores Sugeridos'),
        ),
    ]
