# Generated by Django 5.2.7 on 2026-02-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0043_alter_tecnicopuesto_puesto'),
        ('presupuestos', '0030_requisicion_proveedores_sugeridos'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='proveedores_sugeridos_notas',
            field=models.TextField(blank=True, help_text='Especifique qué artículos corresponden a cada proveedor sugerido.', null=True, verbose_name='Detalle por Proveedor'),
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='proveedores_sugeridos',
        ),
        migrations.AddField(
            model_name='requisicion',
            name='proveedores_sugeridos',
            field=models.ManyToManyField(blank=True, related_name='requisiciones_sugeridas', to='mantenimiento.empresa', verbose_name='Proveedores Sugeridos'),
        ),
    ]
