# Generated by Django 5.2.7 on 2026-02-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0043_alter_tecnicopuesto_puesto'),
        ('presupuestos', '0031_requisicion_proveedores_sugeridos_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulorequisicion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_requisicion', to='mantenimiento.empresa', verbose_name='Proveedor sugerido para este artículo'),
        ),
    ]
