# Generated by Django 5.2.7 on 2026-02-24 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0032_articulorequisicion_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
