# Generated by Django 5.2.7 on 2026-02-24 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0033_alter_requisicion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicion',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha'),
        ),
    ]
