# Generated by Django 5.2.7 on 2026-03-04 16:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0051_ubicacion_es_almacen'),
        ('presupuestos', '0034_alter_requisicion_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='REPEX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Plan')),
                ('anio', models.PositiveIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Notas')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('EJECUCION', 'En Ejecución'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_repex', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan REPEX',
                'verbose_name_plural': 'Planes REPEX',
                'ordering': ['-anio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='REPEXItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, help_text='Motivo de la reposición', max_length=500)),
                ('costo_original', models.DecimalField(blank=True, decimal_places=2, help_text='Costo original del sistema', max_digits=12, null=True)),
                ('costo_reposicion', models.DecimalField(decimal_places=2, default=0, help_text='Costo estimado de la nueva unidad', max_digits=12)),
                ('fecha_proyectada', models.DateField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta (Crítico)'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('justificacion', models.TextField(blank=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repex_items', to='activos.activo')),
                ('repex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presupuestos.repex')),
            ],
            options={
                'verbose_name': 'Ítem REPEX',
                'verbose_name_plural': 'Ítems REPEX',
            },
        ),
    ]
