# Generated by Django 5.2.7 on 2026-03-05 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0054_archivoaltabaja'),
        ('presupuestos', '0035_repex_repexitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='repexitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Cantidad de unidades', max_digits=10),
        ),
        migrations.AddField(
            model_name='repexitem',
            name='categoria_manual',
            field=models.CharField(blank=True, help_text='Categoría del ítem (ej: Iluminación, Plomería)', max_length=300),
        ),
        migrations.AddField(
            model_name='repexitem',
            name='nombre_item',
            field=models.CharField(blank=True, help_text='Nombre descriptivo cuando no hay activo vinculado', max_length=300),
        ),
        migrations.AddField(
            model_name='repexitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio por unidad', max_digits=12),
        ),
        migrations.AddField(
            model_name='repexitem',
            name='ubicacion_manual',
            field=models.CharField(blank=True, help_text='Ubicación manual (ej: Edificio A → Nivel 2)', max_length=300),
        ),
        migrations.AddField(
            model_name='repexitem',
            name='unidades',
            field=models.CharField(blank=True, help_text='Unidad de medida (ej: pieza, metro, lote)', max_length=50),
        ),
        migrations.AlterField(
            model_name='repexitem',
            name='activo',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío para ítems manuales', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repex_items', to='activos.activo'),
        ),
        migrations.AlterField(
            model_name='repexitem',
            name='costo_reposicion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total (cantidad × precio unitario)', max_digits=12),
        ),
    ]
