# Generated by Django 5.2.7 on 2026-03-05 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0055_modelo_unidad_medida'),
        ('presupuestos', '0036_repexitem_cantidad_repexitem_categoria_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repexitem',
            name='modelo',
            field=models.ForeignKey(blank=True, help_text='Modelo asociado para ítems manuales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repex_items_manuales', to='activos.modelo'),
        ),
    ]
