# Generated by Django 5.2.12 on 2026-03-09 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0037_repexitem_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones', to='presupuestos.partidapresupuestaria', verbose_name='Partida Presupuestaria'),
        ),
    ]
