# Generated by Django 5.2.12 on 2026-03-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0038_requisicion_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='item_presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones', to='presupuestos.itempresupuesto', verbose_name='Ítem de Presupuesto'),
        ),
    ]
