# Generated by Django 5.2.12 on 2026-03-09 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0049_remove_pasoprocedimiento_procedimiento_and_more'),
        ('presupuestos', '0039_requisicion_item_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='tipo_rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones', to='mantenimiento.tipo', verbose_name='Tipo de Rutina'),
        ),
    ]
