# Generated by Django 5.2.12 on 2026-03-16 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0040_requisicion_tipo_rutina'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprobado el'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha'),
        ),
    ]
