# Generated by Django 5.2.12 on 2026-04-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_departamento_perfilusuario_departamento'),
        ('presupuestos', '0041_requisicion_fecha_aprobacion_alter_requisicion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidapresupuestaria',
            name='departamentos',
            field=models.ManyToManyField(blank=True, help_text='Si se seleccionan departamentos, solo los usuarios de estos departamentos verán esta partida. Si está vacío, será visible para todos (Global).', related_name='partidas_permitidas', to='core.departamento', verbose_name='Departamentos Permitidos'),
        ),
    ]
