# Generated by Django 5.2.12 on 2026-06-09 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0042_partidapresupuestaria_departamentos'),
        ('proyectos', '0010_alter_documentoproyecto_carpeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones', to='proyectos.proyecto', verbose_name='Proyecto'),
        ),
    ]
