# Generated by Django 6.0.6 on 2026-06-12 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0043_requisicion_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaRequisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Nota')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='presupuestos.requisicion', verbose_name='Requisición')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Nota de Requisición',
                'verbose_name_plural': 'Notas de Requisición',
                'ordering': ['-creado_en'],
            },
        ),
    ]
