# Generated by Django 6.0.6 on 2026-06-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0044_add_nota_requisicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulorequisicion',
            name='cr8ca_articulo',
            field=models.CharField(max_length=1000, verbose_name='Descripción del Artículo'),
        ),
    ]
