# Generated by Django 6.0.6 on 2026-06-23 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_aprobador_to_departamento'),
        ('presupuestos', '0047_add_aprobador_to_requisicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoanual',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='core.departamento', verbose_name='Departamento'),
        ),
    ]
