# Generated by Django 6.0.6 on 2026-06-23 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0048_add_departamento_to_presupuestoanual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código (Siglas)')),
                ('simbolo', models.CharField(default='$', max_length=10, verbose_name='Símbolo')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='presupuestoanual',
            name='moneda_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='presupuestos.moneda', verbose_name='Moneda (FK)'),
        ),
    ]
