# Generated by Django 6.0.6 on 2026-06-23 22:08

from django.db import migrations

def migrate_monedas(apps, schema_editor):
    Moneda = apps.get_model('presupuestos', 'Moneda')
    PresupuestoAnual = apps.get_model('presupuestos', 'PresupuestoAnual')
    
    # 1. Crear las monedas básicas
    currencies_data = [
        {'codigo': 'DOP', 'nombre': 'Pesos Dominicanos', 'simbolo': 'RD$'},
        {'codigo': 'USD', 'nombre': 'Dólares', 'simbolo': '$'},
        {'codigo': 'HNL', 'nombre': 'Lempiras', 'simbolo': 'L'},
        {'codigo': 'EUR', 'nombre': 'Euro', 'simbolo': '€'},
    ]
    
    currency_objs = {}
    for data in currencies_data:
        obj, created = Moneda.objects.get_or_create(
            codigo=data['codigo'],
            defaults={'nombre': data['nombre'], 'simbolo': data['simbolo']}
        )
        currency_objs[data['codigo']] = obj

    # 2. Asociar los presupuestos existentes con su correspondiente Moneda
    for p in PresupuestoAnual.objects.all():
        old_code = p.moneda
        if old_code in currency_objs:
            p.moneda_fk = currency_objs[old_code]
            p.save(update_fields=['moneda_fk'])
        else:
            # Por si acaso hay algún valor extraño, por defecto DOP
            if 'DOP' in currency_objs:
                p.moneda_fk = currency_objs['DOP']
                p.save(update_fields=['moneda_fk'])

def reverse_migrate_monedas(apps, schema_editor):
    PresupuestoAnual = apps.get_model('presupuestos', 'PresupuestoAnual')
    # Regresar el valor de moneda_fk.codigo al charfield moneda
    for p in PresupuestoAnual.objects.all():
        if p.moneda_fk:
            p.moneda = p.moneda_fk.codigo
            p.save(update_fields=['moneda'])

class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0049_add_moneda_and_temp_fk'),
    ]

    operations = [
        migrations.RunPython(migrate_monedas, reverse_migrate_monedas),
    ]

