# Generated by Django 6.0.6 on 2026-06-23 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0050_migrate_existing_monedas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestoanual',
            name='moneda',
        ),
        migrations.RenameField(
            model_name='presupuestoanual',
            old_name='moneda_fk',
            new_name='moneda',
        ),
        migrations.AlterField(
            model_name='presupuestoanual',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='presupuestos.moneda', verbose_name='Moneda'),
        ),
    ]

