# Generated by Django 6.0.6 on 2026-06-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0051_rename_moneda_fk_to_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='fecha_probable_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Probable de Entrega'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='recepcion_notificada',
            field=models.BooleanField(default=False, verbose_name='Notificación de Recepción Enviada'),
        ),
    ]
