# Generated by Django 6.0.6 on 2026-06-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0052_add_recepcion_notificada_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicion',
            name='estado_requisicion',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'En espera de autorización'), ('AUTORIZADO', 'Autorizado'), ('VISTO_PROCURA', 'Visto por Procura'), ('EN_ORDEN_COMPRA', 'En Orden de Compra'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=50, verbose_name='Estado de la Requisición'),
        ),
    ]
