# Generated by Django 6.0.6 on 2026-06-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0054_add_ordencompra_procura_procesando'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='tipo_documento',
            field=models.CharField(choices=[('OC', 'OC'), ('DOIH', 'DOIH')], default='OC', max_length=10, verbose_name='Tipo Documento'),
        ),
    ]
