# Generated by Django 6.0.6 on 2026-06-24 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0055_add_tipo_documento_ordencompra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicionHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(max_length=50, verbose_name='Estado Nuevo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='presupuestos.requisicion', verbose_name='Requisición')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Requisición',
                'verbose_name_plural': 'Historial de Requisiciones',
                'ordering': ['creado_en'],
            },
        ),
    ]
