# Generated by Django 6.0.6 on 2026-06-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0057_add_choices_historial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Centro de Costo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='anticipo',
            field=models.BooleanField(default=False, verbose_name='Anticipo'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='anticipo_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Anticipo'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='contraentrega',
            field=models.BooleanField(default=False, verbose_name='Contraentrega'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='credito',
            field=models.BooleanField(default=False, verbose_name='Crédito'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='credito_dias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Días de crédito'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='doc_estimacion',
            field=models.BooleanField(default=False, verbose_name='Estimación'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='doc_factura',
            field=models.BooleanField(default=False, verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='doc_garantia',
            field=models.BooleanField(default=False, verbose_name='Garantía'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='doc_respaldo',
            field=models.BooleanField(default=False, verbose_name='Respaldo'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='presupuestos.centrocosto', verbose_name='Centro de Costo'),
        ),
    ]
