# Generated by Django 6.0.6 on 2026-07-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0059_cotizacion_itempredefinido_itemcotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versión'),
        ),
    ]
