# Generated by Django 6.0.6 on 2026-07-03 16:16

import django.db.models.deletion
from django.db import migrations, models


def fill_disciplina_from_predefinido(apps, schema_editor):
    ItemCotizacion = apps.get_model('presupuestos', 'ItemCotizacion')
    for item in ItemCotizacion.objects.filter(disciplina__isnull=True, item_predefinido__isnull=False).select_related('item_predefinido__disciplina'):
        item.disciplina_id = item.item_predefinido.disciplina_id
        item.save(update_fields=['disciplina'])
    # Items sin predefinido: heredar la disciplina de la cotización
    for item in ItemCotizacion.objects.filter(disciplina__isnull=True).select_related('cotizacion'):
        item.disciplina_id = item.cotizacion.disciplina_id
        item.save(update_fields=['disciplina'])


def reverse_fill_disciplina(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0034_groqapikey'),
        ('presupuestos', '0060_add_version_to_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_cotizacion', to='documentos.disciplina', verbose_name='Disciplina'),
        ),
        migrations.RunPython(fill_disciplina_from_predefinido, reverse_fill_disciplina),
    ]
