# Generated by Django 6.0.6 on 2026-07-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0034_groqapikey'),
        ('presupuestos', '0061_add_disciplina_to_itemcotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='documentos.disciplina', verbose_name='Disciplina'),
        ),
    ]
