# Generated by Django 6.0.6 on 2026-07-03 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0034_groqapikey'),
        ('presupuestos', '0062_cotizacion_disciplina_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempredefinido',
            options={'ordering': ['disciplina__nombre', 'familia__nombre', 'codigo'], 'verbose_name': 'Artículo Predefinido', 'verbose_name_plural': 'Artículos Predefinidos'},
        ),
        migrations.AddField(
            model_name='itempredefinido',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas / Especificaciones técnicas'),
        ),
        migrations.CreateModel(
            name='FamiliaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Familia')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familias_items', to='documentos.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Familia de Artículos',
                'verbose_name_plural': 'Familias de Artículos',
                'ordering': ['disciplina__nombre', 'orden', 'nombre'],
                'unique_together': {('disciplina', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='itempredefinido',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='presupuestos.familiaitem', verbose_name='Familia'),
        ),
    ]
