# Generated by Django 6.0.6 on 2026-07-04 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0063_familia_item_y_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempredefinido',
            name='es_compuesto',
            field=models.BooleanField(default=False, help_text='Si está marcado, el precio se calcula desde sus componentes.', verbose_name='¿Es artículo compuesto?'),
        ),
        migrations.AlterField(
            model_name='itempredefinido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Si es compuesto se calcula automáticamente desde los componentes.', max_digits=15, verbose_name='Precio Unitario'),
        ),
        migrations.CreateModel(
            name='ComponenteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en', to='presupuestos.itempredefinido', verbose_name='Componente')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='presupuestos.itempredefinido', verbose_name='Artículo Compuesto')),
            ],
            options={
                'verbose_name': 'Componente de Artículo',
                'verbose_name_plural': 'Componentes de Artículos',
                'ordering': ['orden', 'id'],
                'unique_together': {('padre', 'componente')},
            },
        ),
    ]
