# Generated by Django 5.2.12 on 2026-07-08 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0073_modelo_documentos'),
        ('presupuestos', '0064_articulo_compuesto_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='activos.ubicacion', verbose_name='Área'),
        ),
    ]
