# Generated by Django 5.2.12 on 2026-07-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0065_add_area_to_cotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='area',
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='area',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Área'),
        ),
    ]
