# Generated by Django 6.0.6 on 2026-07-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0066_refactor_area_manual_en_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='tipo',
            field=models.CharField(choices=[('BIEN', 'Bien'), ('SERVICIO', 'Servicio')], default='BIEN', max_length=10, verbose_name='Tipo'),
        ),
    ]
