# Generated by Django 6.0.6 on 2026-07-21 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_nav_config_to_perfil'),
        ('inventarios', '0033_disponibilidaddiaria'),
        ('presupuestos', '0067_requisicion_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del paquete')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_materiales', to='core.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Paquete de Materiales',
                'verbose_name_plural': 'Paquetes de Materiales',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=1000, verbose_name='Descripción / Detalle')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Cantidad')),
                ('costo_aproximado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Costo Aproximado')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_items', to='inventarios.material', verbose_name='Material')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presupuestos.paquetematerial', verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Item del Paquete',
                'verbose_name_plural': 'Items del Paquete',
                'ordering': ['orden'],
            },
        ),
    ]
