# Generated by Django 6.0.6 on 2026-07-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0068_paquetematerial_paquetematerialitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado para ejecución'),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprobado el'),
        ),
    ]
