# Generated by Django 6.0.6 on 2026-07-23 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0069_itemcotizacion_aprobado_itemcotizacion_aprobado_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoExoneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('dai', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='DAI (%)')),
                ('isc', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ISC (%)')),
                ('ipc', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='IPC (%)')),
                ('isv', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ISV (%)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='presupuestos.codigoexoneracion', verbose_name='Partida Padre')),
            ],
            options={
                'verbose_name': 'Código de Exoneración',
                'verbose_name_plural': 'Códigos de Exoneración',
                'ordering': ['codigo'],
            },
        ),
    ]
