# Generated by Django 6.0.6 on 2026-07-29 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0035_add_codigo_exoneracion_material'),
        ('presupuestos', '0070_codigoexoneracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialExoneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Cantidad a Solicitar')),
                ('notas', models.CharField(blank=True, max_length=500, verbose_name='Notas / Justificación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo_exoneracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_solicitud', to='presupuestos.codigoexoneracion', verbose_name='Código de Exoneración')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exoneraciones_solicitud', to='inventarios.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Material en Exoneración',
                'verbose_name_plural': 'Materiales en Exoneración',
                'ordering': ['codigo_exoneracion', 'material__nombre'],
                'unique_together': {('codigo_exoneracion', 'material')},
            },
        ),
    ]
