# Generated by Django 6.0.6 on 2026-07-29 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0071_add_material_exoneracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoRequisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Grupo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(choices=[('#0a6ed1', 'Azul'), ('#107e3e', 'Verde'), ('#e9730c', 'Naranja'), ('#bb0000', 'Rojo'), ('#354a5f', 'Gris Oscuro'), ('#6a6d70', 'Gris')], default='#0a6ed1', max_length=10, verbose_name='Color')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_requisicion_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de Requisiciones',
                'verbose_name_plural': 'Grupos de Requisiciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='requisicion',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones', to='presupuestos.gruporequisicion', verbose_name='Grupo'),
        ),
    ]
