# Generated by Django 6.0.6 on 2026-08-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0072_add_grupo_requisicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleperiodico',
            options={'ordering': ['anio', 'mes'], 'verbose_name': 'Detalle Periódico', 'verbose_name_plural': 'Detalles Periódicos'},
        ),
        migrations.AlterUniqueTogether(
            name='detalleperiodico',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='detalleperiodico',
            name='anio',
            field=models.PositiveIntegerField(blank=True, help_text='Año del período. Si vacío usa el año del presupuesto padre.', null=True, verbose_name='Año'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleperiodico',
            unique_together={('item', 'mes', 'anio')},
        ),
    ]
