# Generated by Django 6.0.6 on 2026-08-07 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0073_add_anio_to_detalle_periodico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la vista')),
                ('columns', models.JSONField(default=list, help_text='Lista ordenada de IDs de columnas visibles', verbose_name='Columnas visibles')),
                ('sort_column', models.CharField(blank=True, max_length=50, null=True, verbose_name='Columna de ordenamiento')),
                ('sort_direction', models.CharField(blank=True, choices=[('asc', 'Ascendente'), ('desc', 'Descendente')], max_length=4, null=True, verbose_name='Dirección de ordenamiento')),
                ('is_last_used', models.BooleanField(default=False, verbose_name='Es la última vista utilizada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vista del Dashboard',
                'verbose_name_plural': 'Vistas del Dashboard',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
