# Generated by Django 6.0.6 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0074_dashboard_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='forma_pago',
            field=models.CharField(choices=[('CONTADO', 'Al Contado'), ('ANTICIPO', 'Anticipo'), ('DIFERIDO', 'Diferido'), ('CREDITO', 'A Plazos / Crédito'), ('CONTRA_ENTREGA', 'Contra Entrega')], default='CONTADO', help_text='Forma de pago heredada de la requisición.', max_length=20, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='forma_pago',
            field=models.CharField(choices=[('CONTADO', 'Al Contado'), ('ANTICIPO', 'Anticipo'), ('DIFERIDO', 'Diferido'), ('CREDITO', 'A Plazos / Crédito'), ('CONTRA_ENTREGA', 'Contra Entrega')], default='CONTADO', help_text='Condición de pago que se transferirá a la Orden de Compra.', max_length=20, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='estado_requisicion',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'En espera de autorización'), ('AUTORIZADO', 'Autorizado'), ('VISTO_PROCURA', 'Visto por Procura'), ('PROCURA_PROCESANDO', 'Procura Procesando'), ('SOLICITUD_INFORMACION', 'Solicitud de Información'), ('EN_ORDEN_COMPRA', 'En Orden de Compra'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=50, verbose_name='Estado de la Requisición'),
        ),
    ]