# Generated by Django 6.0.6 on 2026-08-13

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def crear_grupo_procura_tecnica(apps, schema_editor):
    from django.contrib.contenttypes.models import ContentType
    from inventarios.models import Material, MovimientoInventario
    from presupuestos.models import Requisicion, OrdenCompra, ArticuloRequisicion

    group, created = Group.objects.get_or_create(name='Procura_Tecnica')
    if not created and group.permissions.exists():
        return

    permisos_nombres = set()

    for modelo in (Material, MovimientoInventario):
        ct = ContentType.objects.get_for_model(modelo)
        for perm in Permission.objects.filter(content_type=ct):
            permisos_nombres.add(perm.pk)

    for modelo in (Requisicion, OrdenCompra, ArticuloRequisicion):
        ct = ContentType.objects.get_for_model(modelo)
        for perm in Permission.objects.filter(content_type=ct):
            if perm.codename.startswith(('view', 'change', 'add')):
                permisos_nombres.add(perm.pk)

    group.permissions.add(*permisos_nombres)


def eliminar_grupo_procura_tecnica(apps, schema_editor):
    Group.objects.filter(name='Procura_Tecnica').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0075_add_forma_pago_solicitud_informacion'),
    ]

    operations = [
        migrations.RunPython(crear_grupo_procura_tecnica, eliminar_grupo_procura_tecnica),
    ]