# Generated by Django 6.0.6 on 2026-08-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0076_crear_grupo_procura_tecnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicionhistorial',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'En espera de autorización'), ('AUTORIZADO', 'Autorizado'), ('VISTO_PROCURA', 'Visto por Procura'), ('PROCURA_PROCESANDO', 'Procura Procesando'), ('SOLICITUD_INFORMACION', 'Solicitud de Información'), ('EN_ORDEN_COMPRA', 'En Orden de Compra'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], max_length=50, null=True, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='requisicionhistorial',
            name='estado_nuevo',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'En espera de autorización'), ('AUTORIZADO', 'Autorizado'), ('VISTO_PROCURA', 'Visto por Procura'), ('PROCURA_PROCESANDO', 'Procura Procesando'), ('SOLICITUD_INFORMACION', 'Solicitud de Información'), ('EN_ORDEN_COMPRA', 'En Orden de Compra'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], max_length=50, verbose_name='Estado Nuevo'),
        ),
    ]
