# Generated by Django 6.0.6 on 2026-09-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0077_alter_requisicionhistorial_estado_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='forma_pago',
            field=models.CharField(choices=[('CONTADO', 'Al Contado'), ('ANTICIPO', 'Anticipo'), ('DIFERIDO', 'Diferido'), ('CREDITO', 'A Plazos / Crédito'), ('CONTRA_ENTREGA', 'Contra Entrega'), ('PLAN_PAGO', 'Plan de Pago')], default='CONTADO', help_text='Forma de pago heredada de la requisición.', max_length=20, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='forma_pago',
            field=models.CharField(choices=[('CONTADO', 'Al Contado'), ('ANTICIPO', 'Anticipo'), ('DIFERIDO', 'Diferido'), ('CREDITO', 'A Plazos / Crédito'), ('CONTRA_ENTREGA', 'Contra Entrega'), ('PLAN_PAGO', 'Plan de Pago')], default='CONTADO', help_text='Condición de pago que se transferirá a la Orden de Compra.', max_length=20, verbose_name='Forma de Pago'),
        ),
    ]
