# Generated by Django 6.0.6 on 2026-09-01 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0078_alter_ordencompra_forma_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitoPagoOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150, verbose_name='Concepto / Hito')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos_pago', to='presupuestos.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Hito de Plan de Pago',
                'verbose_name_plural': 'Hitos de Plan de Pago',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
