# Generated by Django 6.0.6 on 2026-09-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0079_hitopagoordencompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitopagoordencompra',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Porcentaje (%)'),
        ),
    ]
