# Generated by Django 6.0.6 on 2026-09-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0080_hitopagoordencompra_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('SUMINISTRO_INSTALACION', 'Suministro e Instalación'), ('CONTRATO_SERVICIO', 'Contrato de Servicio')], max_length=30, null=True, verbose_name='Tipo de Contrato'),
        ),
    ]
