# Generated by Django 5.2.7 on 2025-12-21 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(help_text='Prefijo para consecutivo (ej: RFI, MEMO)', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Comunicado',
                'verbose_name_plural': 'Tipos de Comunicado',
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField(help_text='Contenido del mensaje')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='comunicaciones.comunicado')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados_enviados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comunicaciones.tipocomunicado')),
            ],
        ),
        migrations.CreateModel(
            name='AdjuntoComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='comunicados/adjuntos/')),
                ('documento_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documentos.revision')),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='comunicaciones.comunicado')),
            ],
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PARA', 'Para'), ('CC', 'CC'), ('CCO', 'CCO')], default='PARA', max_length=10)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_leido', models.DateTimeField(blank=True, null=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='comunicaciones.comunicado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': 'Destinatarios',
                'unique_together': {('comunicado', 'usuario')},
            },
        ),
    ]
