# Generated by Django 5.2.7 on 2025-12-29 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0018_remove_activo_categoria'),
        ('comunicaciones', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntocomunicado',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmittals', to='activos.activo'),
        ),
    ]
