# Generated by Django 5.2.12 on 2026-03-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0003_adjuntocomunicado_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(default='IDLE', max_length=50)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sesión de Bot',
                'verbose_name_plural': 'Sesiones de Bot',
                'db_table': 'bot_sessions',
            },
        ),
    ]
