# Generated by Django 5.2.12 on 2026-03-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0004_botsession'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE bot_sessions ALTER COLUMN last_update SET DEFAULT CURRENT_TIMESTAMP;",
            reverse_sql="ALTER TABLE bot_sessions ALTER COLUMN last_update DROP DEFAULT;"
        ),
    ]
