# Generated by Django 5.2.12 on 2026-04-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0005_set_bot_sessions_default_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsession',
            name='context',
            field=models.JSONField(blank=True, default=dict, help_text='Datos temporales de la sesión (ej. en medio de un wizard)'),
        ),
    ]
