# Generated by Django 6.0.6 on 2026-08-17 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0006_botsession_context'),
        ('proyectos', '0020_elementos_disciplina_area_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados', to='proyectos.proyecto'),
        ),
    ]
