# Generated by Django 6.0.6 on 2026-07-01 19:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagen de portada')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de asignación')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_curso', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asignados', to='auth.group', verbose_name='Grupo de usuarios')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='courses.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Asignación de Curso',
                'verbose_name_plural': 'Asignaciones de Cursos',
                'unique_together': {('curso', 'grupo'), ('curso', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('contenido_html', models.TextField(blank=True, help_text='Puedes usar HTML, incluir imágenes <img> y videos <iframe>', verbose_name='Contenido HTML')),
                ('duracion_minutos', models.PositiveIntegerField(default=0, verbose_name='Duración (min)')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='courses.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('completado_en', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='courses.asignacioncurso', verbose_name='Asignación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_cursos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='courses.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Progreso de Sección',
                'verbose_name_plural': 'Progresos de Secciones',
                'unique_together': {('asignacion', 'seccion', 'usuario')},
            },
        ),
    ]
