# Generated by Django 6.0.6 on 2026-07-01 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('contenido_html', models.TextField(blank=True, help_text='Puedes usar HTML, incluir imágenes <img> y videos <iframe>', verbose_name='Contenido HTML')),
                ('duracion_minutos', models.PositiveIntegerField(default=0, verbose_name='Duración (min)')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='courses.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['orden'],
            },
        ),
    ]
