# Generated by Django 6.0.6 on 2026-07-01 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_pagina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='disponible_para_todos',
            field=models.BooleanField(default=False, help_text='Cualquier usuario puede acceder sin necesidad de asignación', verbose_name='Disponible para todos'),
        ),
        migrations.CreateModel(
            name='RegistroTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('duracion_segundos', models.PositiveIntegerField(default=0, verbose_name='Duración (segundos)')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos', to='courses.curso', verbose_name='Curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempo_cursos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Tiempo',
                'verbose_name_plural': 'Registros de Tiempo',
                'ordering': ['-inicio'],
            },
        ),
    ]
