# Generated by Django 6.0.6 on 2026-07-02 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_curso_disponible_para_todos_registrotiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden dentro del pensum'),
        ),
        migrations.AddField(
            model_name='curso',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='courses.curso', verbose_name='Curso padre (pensum)'),
        ),
    ]
