# Generated by Django 6.0.6 on 2026-07-17 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_curso_padre_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenInteractiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cursos/interactivas/', verbose_name='Imagen base')),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='Título descriptivo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_interactivas', to='courses.pagina', verbose_name='Página')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_interactivas', to='courses.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Imagen Interactiva',
                'verbose_name_plural': 'Imágenes Interactivas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1, verbose_name='Número de burbuja')),
                ('pos_x', models.FloatField(help_text='Porcentaje horizontal (0-100)', verbose_name='Posición X (%)')),
                ('pos_y', models.FloatField(help_text='Porcentaje vertical (0-100)', verbose_name='Posición Y (%)')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del hotspot')),
                ('contenido_html', models.TextField(blank=True, help_text='Contenido que se muestra al hacer clic en la burbuja', verbose_name='Contenido HTML')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='courses.imageninteractiva', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Hotspot',
                'verbose_name_plural': 'Hotspots',
                'ordering': ['numero'],
            },
        ),
    ]
