# Generated by Django 6.0.6 on 2026-07-17 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_hotspots_interactivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotspot',
            options={'verbose_name': 'Hotspot', 'verbose_name_plural': 'Hotspots'},
        ),
        migrations.CreateModel(
            name='Acordeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('contenido_html', models.TextField(blank=True, help_text='Contenido que se muestra al expandir', verbose_name='Contenido HTML')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acordeones', to='courses.pagina', verbose_name='Página')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acordeones', to='courses.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Acordeón',
                'verbose_name_plural': 'Acordeones',
                'ordering': ['orden'],
            },
        ),
    ]
