# Generated by Django 6.0.6 on 2026-07-17 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_acordeones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='Título del carrusel')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carruseles', to='courses.pagina', verbose_name='Página')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carruseles', to='courses.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Carrusel',
                'verbose_name_plural': 'Carruseles',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('contenido_html', models.TextField(blank=True, verbose_name='Contenido HTML')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/carrusel/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('carrusel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='courses.carrusel', verbose_name='Carrusel')),
            ],
            options={
                'verbose_name': 'Tarjeta de Carrusel',
                'verbose_name_plural': 'Tarjetas de Carrusel',
                'ordering': ['orden'],
            },
        ),
    ]
