# Generated by Django 6.0.6 on 2026-07-21 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_carruseles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('MULTIPLE', 'Opción Múltiple'), ('V_F', 'Verdadero/Falso'), ('MIXTA', 'Mixta')], default='MULTIPLE', max_length=10, verbose_name='Tipo')),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Puntaje máximo')),
                ('puntaje_aprobacion', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Puntaje para aprobar')),
                ('tiempo_limite_minutos', models.PositiveIntegerField(default=0, help_text='0 = sin límite', verbose_name='Tiempo límite (min)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='courses.curso', verbose_name='Curso')),
                ('pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='courses.pagina', verbose_name='Página')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='courses.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='IntentoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Puntaje obtenido')),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Puntaje máximo')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('intento_numero', models.PositiveIntegerField(default=1, verbose_name='Número de intento')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos', to='courses.asignacioncurso', verbose_name='Asignación')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='courses.evaluacion', verbose_name='Evaluación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_evaluaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Intento de Evaluación',
                'verbose_name_plural': 'Intentos de Evaluación',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('evaluacion', 'usuario', 'intento_numero')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la pregunta')),
                ('tipo', models.CharField(choices=[('MULTIPLE', 'Opción Múltiple'), ('V_F', 'Verdadero/Falso')], default='MULTIPLE', max_length=10, verbose_name='Tipo de respuesta')),
                ('puntaje', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Puntaje')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('explicacion', models.TextField(blank=True, help_text='Se muestra después de responder', verbose_name='Explicación')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='courses.evaluacion', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto de la opción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='Correcta')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='courses.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='Correcta')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje obtenido')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='courses.intentoevaluacion', verbose_name='Intento')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_usuarios', to='courses.opcion', verbose_name='Opción seleccionada')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_usuarios', to='courses.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Usuario',
                'verbose_name_plural': 'Respuestas de Usuarios',
                'unique_together': {('intento', 'pregunta')},
            },
        ),
    ]
