# Generated by Django 6.0.6 on 2026-07-21 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_evaluacion_intentoevaluacion_pregunta_opcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del curso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('institucion', models.CharField(blank=True, max_length=255, verbose_name='Institución / Plataforma')),
                ('diploma', models.FileField(blank=True, null=True, upload_to='diplomas/', verbose_name='Diploma / Certificado')),
                ('fecha_diploma', models.DateField(verbose_name='Fecha del diploma')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_externos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Curso externo',
                'verbose_name_plural': 'Cursos externos',
                'ordering': ['-fecha_diploma'],
            },
        ),
    ]
