# Generated by Django 6.0.6 on 2026-07-28 04:50

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo para identificar este chat', max_length=255, verbose_name='Nombre de la consulta')),
                ('archivo', models.FileField(help_text='Archivo de texto exportado del chat', upload_to='consultas/%Y/%m/', verbose_name='Archivo TXT')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False, verbose_name='¿Procesado?')),
                ('total_mensajes', models.IntegerField(default=0, verbose_name='Total de mensajes')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_str', models.CharField(help_text='Fecha en formato original (ej: 22/2/22)', max_length=20, verbose_name='Fecha')),
                ('hora_str', models.CharField(help_text='Hora en formato original (ej: 10:15 a. m.)', max_length=20, verbose_name='Hora')),
                ('remitente', models.CharField(help_text='Nombre o número del remitente', max_length=255, verbose_name='Remitente')),
                ('texto', models.TextField(verbose_name='Texto del mensaje')),
                ('linea_original', models.TextField(help_text='Texto completo sin parsear para referencia', verbose_name='Línea original')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='consultas.consulta')),
            ],
            options={
                'verbose_name': 'Mensaje de Consulta',
                'verbose_name_plural': 'Mensajes de Consulta',
                'ordering': ['consulta', 'id'],
                'indexes': [models.Index(fields=['consulta', 'remitente'], name='consultas_m_consult_dbcd8b_idx'), models.Index(fields=['remitente'], name='consultas_m_remiten_4a1c10_idx')],
            },
        ),
    ]
