# Generated by Django 6.0.6 on 2026-07-28 07:09

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='ID de sesión para agrupar una conversación', max_length=64)),
                ('pregunta', models.TextField(verbose_name='Pregunta del usuario')),
                ('respuesta', models.TextField(verbose_name='Respuesta de la IA')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='consultas.consulta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación IA',
                'verbose_name_plural': 'Conversaciones IA',
                'ordering': ['session_id', 'creado_en'],
                'indexes': [models.Index(fields=['consulta', 'session_id'], name='consultas_c_consult_b18bf8_idx')],
            },
        ),
    ]
