# Generated by Django 6.0.6 on 2026-07-28 07:14

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_add_conversacion_ia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaContexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Nota de contexto')),
                ('categoria', models.CharField(choices=[('PERSONA', 'Persona / Rol'), ('LUGAR', 'Lugar / Ubicación'), ('TERMINO', 'Término / Acrónimo'), ('PROCESO', 'Proceso / Procedimiento'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_contexto', to='consultas.consulta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Contexto',
                'verbose_name_plural': 'Notas de Contexto',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
