# Generated by Django 5.2.7 on 2026-01-03 19:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0025_categoria_padre'),
        ('mantenimiento', '0029_aviso_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Material')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU / Código Interno')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'Unidad'), ('LITRO', 'Litro'), ('GALON', 'Galón'), ('KG', 'Kilogramo'), ('METRO', 'Metro'), ('CAJA', 'Caja')], default='UNIDAD', max_length=20)),
                ('precio_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Alerta cuando el stock total baje de este nivel', max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material / Repuesto',
                'verbose_name_plural': 'Materiales y Repuestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Carga)'), ('SALIDA', 'Salida (Uso/Retiro)'), ('AJUSTE', 'Ajuste de Inventario'), ('TRASLADO', 'Traslado entre Ubicaciones')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventarios.material')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_usados', to='mantenimiento.ordentrabajo')),
                ('ubicacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_entrada', to='activos.ubicacion')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_salida', to='activos.ubicacion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='CompatibilidadMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sugerida', models.DecimalField(decimal_places=2, default=1, help_text='Cantidad usual requerida para este modelo', max_digits=10)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_sugeridos', to='activos.modelo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_compatibles', to='inventarios.material')),
            ],
            options={
                'verbose_name': 'Compatibilidad de Repuesto',
                'verbose_name_plural': 'Compatibilidades de Repuestos',
                'unique_together': {('material', 'modelo')},
            },
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='inventarios.material')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='activos.ubicacion')),
            ],
            options={
                'verbose_name': 'Existencia por Ubicación',
                'verbose_name_plural': 'Existencias por Ubicación',
                'unique_together': {('material', 'ubicacion')},
            },
        ),
    ]
