# Generated by Django 5.2.7 on 2026-01-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nombre del Material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='sku',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='SKU / Código Interno'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha_movimiento',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Carga)'), ('SALIDA', 'Salida (Uso/Retiro)'), ('AJUSTE', 'Ajuste de Inventario'), ('TRASLADO', 'Traslado entre Ubicaciones')], db_index=True, max_length=15),
        ),
    ]
