# Generated by Django 5.2.7 on 2026-01-14 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0032_ubicacion_categoria'),
        ('inventarios', '0004_categoriamaterial_material_categoria'),
        ('mantenimiento', '0038_fotoaviso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado / Completado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('comentarios_solicitud', models.TextField(blank=True, null=True)),
                ('comentarios_almacen', models.TextField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_despachadas', to=settings.AUTH_USER_MODEL)),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_material', to='mantenimiento.ordentrabajo')),
                ('ubicacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_salida', to='activos.ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Material (Orden)',
                'verbose_name_plural': 'Solicitudes de Material (Órdenes)',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventarios.solicitudmaterial'),
        ),
    ]
