# Generated by Django 5.2.7 on 2026-01-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0032_ubicacion_categoria'),
        ('inventarios', '0005_solicitudmaterial_movimientoinventario_solicitud'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='ubicacion_especifica',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ubicación Específica (Destino)'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='ubicacion_especifica',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ubicación Específica (Pasillo/Estante)'),
        ),
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together={('material', 'ubicacion', 'ubicacion_especifica')},
        ),
    ]
