# Generated by Django 5.2.7 on 2026-01-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0032_ubicacion_categoria'),
        ('inventarios', '0006_alter_stockrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='activos.marca', verbose_name='Marca'),
        ),
    ]
