# Generated by Django 5.2.7 on 2026-02-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0007_material_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tipo_material',
            field=models.CharField(choices=[('INSUMO', 'Insumo'), ('REPUESTO', 'Repuesto'), ('CONSUMIBLE', 'Consumible'), ('MEDICAMENTO', 'Medicamento'), ('HERRAMIENTA', 'Herramienta'), ('EPP', 'Equipo de Protección (EPP)'), ('OTRO', 'Otro')], default='INSUMO', max_length=20, verbose_name='Tipo de Material'),
        ),
    ]
