# Generated by Django 5.2.7 on 2026-02-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0046_bienafecto_plano_alter_activo_foto_and_more'),
        ('inventarios', '0008_material_tipo_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de Lote')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_fabricacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventarios.material')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['fecha_vencimiento'],
                'unique_together': {('material', 'codigo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventarios.lote'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='existencias_lote', to='inventarios.lote'),
        ),
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together={('material', 'lote', 'ubicacion', 'ubicacion_especifica')},
        ),
    ]
