# Generated by Django 5.2.7 on 2026-02-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0009_lote_alter_stockrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='materiales/', verbose_name='Imagen del Material'),
        ),
    ]
