# Generated by Django 5.1.15 on 2026-02-27 16:04

import django.db.models.deletion
from django.db import migrations, models


def create_units(apps, schema_editor):
    UnidadMedida = apps.get_model('inventarios', 'UnidadMedida')
    Material = apps.get_model('inventarios', 'Material')
    
    # Crear unidades estándar basadas en lo que había en Choices
    units = {
        'UNIDAD': ('Unidad', 'UND'),
        'LITRO': ('Litro', 'LT'),
        'GALON': ('Galón', 'GL'),
        'KG': ('Kilogramo', 'KG'),
        'METRO': ('Metro', 'M'),
        'CAJA': ('Caja', 'CJ'),
    }
    
    for key, (nombre, abrev) in units.items():
        u_obj, _ = UnidadMedida.objects.get_or_create(nombre=nombre, defaults={'abreviatura': abrev})
        # Actualizar materiales que tengan este texto
        Material.objects.filter(unidad_medida=key).update(unidad_medida_new=u_obj)

class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0010_material_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Unidad')),
                ('abreviatura', models.CharField(max_length=10, unique=True, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['nombre'],
            },
        ),
        # 1. Agregar campo temporal
        migrations.AddField(
            model_name='material',
            name='unidad_medida_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiales_new', to='inventarios.unidadmedida'),
        ),
        # 2. Migrar datos
        migrations.RunPython(create_units),
        # 3. Quitar campo viejo
        migrations.RemoveField(
            model_name='material',
            name='unidad_medida',
        ),
        # 4. Renombrar campo nuevo
        migrations.RenameField(
            model_name='material',
            old_name='unidad_medida_new',
            new_name='unidad_medida',
        ),
        # 5. Ajustar meta del campo final
        migrations.AlterField(
            model_name='material',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='inventarios.unidadmedida', verbose_name='Unidad de Medida'),
        ),
    ]
