# Generated by Django 5.1.15 on 2026-02-27 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0051_ubicacion_es_almacen'),
        ('inventarios', '0011_unidadmedida_alter_material_unidad_medida'),
        ('presupuestos', '0034_alter_requisicion_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('requisicion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_asociados', to='presupuestos.requisicion')),
                ('ubicacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_recibidos', to='activos.ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_materiales', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Ingreso de Material',
                'verbose_name_plural': 'Ingresos de Materiales',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventarios.ingresoinventario', verbose_name='Ingreso relacionado'),
        ),
    ]
