# Generated by Django 5.2.7 on 2026-03-06 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0012_ingresoinventario_movimientoinventario_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ingresos/fotos/', verbose_name='Foto del Ingreso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventarios.ingresoinventario', verbose_name='Ingreso')),
            ],
            options={
                'verbose_name': 'Foto de Ingreso',
                'verbose_name_plural': 'Fotos de Ingresos',
            },
        ),
    ]
