# Generated by Django 5.2.12 on 2026-04-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_departamento_perfilusuario_departamento'),
        ('inventarios', '0013_fotoingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='departamentos',
            field=models.ManyToManyField(blank=True, help_text='Si se seleccionan departamentos, solo los usuarios de estos departamentos podrán utilizar este material. Si está vacío, cualquier usuario podrá utilizarlo (Global).', related_name='materiales_permitidos', to='core.departamento', verbose_name='Departamentos Permitidos'),
        ),
    ]
