# Generated by Django 5.2.12 on 2026-04-10 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0061_fix_puntos_3d_data_modelo_nullable'),
        ('inventarios', '0014_material_departamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmaterial',
            name='edificio_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_edificio', to='activos.ubicacion', verbose_name='Edificio Destino'),
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='nivel_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_nivel', to='activos.ubicacion', verbose_name='Nivel Destino'),
        ),
    ]
