# Generated by Django 5.2.12 on 2026-04-10 16:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0015_solicitudmaterial_edificio_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='cantidad_solicitada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad Solicitada'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad Entregada/Real'),
        ),
    ]
