# Generated by Django 5.2.12 on 2026-04-13 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0016_movimientoinventario_cantidad_solicitada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='materiales/fotos/', verbose_name='Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_adicionales', to='inventarios.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Foto de Material',
                'verbose_name_plural': 'Fotos de Materiales',
            },
        ),
    ]
