# Generated by Django 5.2.12 on 2026-04-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0017_fotomaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='es_inconsistente',
            field=models.BooleanField(default=False, verbose_name='Inconsistente (Sin Stock)'),
        ),
    ]
