# Generated by Django 5.2.12 on 2026-04-24 17:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0070_downtimeactivo_aviso_and_more'),
        ('inventarios', '0018_movimientoinventario_es_inconsistente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_devuelve', models.CharField(max_length=200, verbose_name='Persona que Devuelve')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Devolución')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios / Observaciones')),
                ('ubicacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_destino', to='activos.ubicacion', verbose_name='Ubicación de Destino')),
                ('usuario_recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Devolución de Material',
                'verbose_name_plural': 'Devoluciones de Materiales',
                'ordering': ['-fecha_devolucion'],
            },
        ),
        migrations.CreateModel(
            name='FotoDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inventarios/devoluciones/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventarios.devolucionmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado_fisico', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado')], default='NUEVO', max_length=20)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventarios.devolucionmaterial')),
                ('material_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_devueltos', to='inventarios.material')),
                ('material_recibido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_como_recibido', to='inventarios.material')),
            ],
        ),
    ]
