# Generated by Django 5.2.12 on 2026-04-24 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0019_devolucionmaterial_fotodevolucion_itemdevolucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucionmaterial',
            name='persona_devuelve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_devueltos', to=settings.AUTH_USER_MODEL, verbose_name='Persona que Devuelve'),
        ),
    ]
