# Generated by Django 5.2.12 on 2026-04-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0020_alter_devolucionmaterial_persona_devuelve'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_relacionados', to='inventarios.devolucionmaterial', verbose_name='Devolución relacionada'),
        ),
    ]
