# Generated by Django 5.2.12 on 2026-04-24 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0021_movimientoinventario_devolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='despachos/fotos/', verbose_name='Foto del Despacho')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventarios.solicitudmaterial', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Foto de Despacho',
                'verbose_name_plural': 'Fotos de Despachos',
            },
        ),
    ]
