# Generated by Django 5.2.12 on 2026-05-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0022_fotodespacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_AUTORIZACION', 'Pendiente de Autorización'), ('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado / Completado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=30),
        ),
    ]
