# Generated by Django 5.2.12 on 2026-07-09 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0023_alter_solicitudmaterial_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('campo', models.CharField(max_length=50, verbose_name='Campo modificado')),
                ('valor_anterior', models.TextField(blank=True, default='', verbose_name='Valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, default='', verbose_name='Valor nuevo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='inventarios.material')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cambio de Material',
                'verbose_name_plural': 'Historial de Cambios de Material',
                'ordering': ['-fecha'],
            },
        ),
    ]
