# Generated by Django 6.0.6 on 2026-07-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0073_modelo_documentos'),
        ('inventarios', '0024_historial_cambio_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Rack')),
                ('largo', models.DecimalField(decimal_places=2, help_text='Largo total del rack en cm', max_digits=8, verbose_name='Largo (cm)')),
                ('alto', models.DecimalField(decimal_places=2, help_text='Altura total del rack en cm', max_digits=8, verbose_name='Altura (cm)')),
                ('num_niveles', models.PositiveIntegerField(default=4, verbose_name='Número de Niveles')),
                ('num_secciones', models.PositiveIntegerField(default=4, verbose_name='Secciones por Nivel')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(limit_choices_to={'tipo': 'BODEGA'}, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='activos.ubicacion', verbose_name='Bodega')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'ordering': ['bodega', 'orden', 'nombre'],
                'unique_together': {('bodega', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RackPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField(verbose_name='Nivel')),
                ('seccion', models.PositiveIntegerField(verbose_name='Sección')),
                ('codigo', models.CharField(help_text='Ej: A01-03-04', max_length=20, verbose_name='Código')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.lote', verbose_name='Lote')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.material', verbose_name='Material')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='inventarios.rack')),
            ],
            options={
                'verbose_name': 'Posición de Rack',
                'verbose_name_plural': 'Posiciones de Rack',
                'ordering': ['rack', 'nivel', 'seccion'],
                'unique_together': {('rack', 'nivel', 'seccion')},
            },
        ),
    ]
