# Generated by Django 6.0.6 on 2026-07-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0025_rack_rackposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura del material en cm', max_digits=8, null=True, verbose_name='Alto (cm)'),
        ),
        migrations.AddField(
            model_name='material',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ancho del material en cm', max_digits=8, null=True, verbose_name='Ancho (cm)'),
        ),
        migrations.AddField(
            model_name='material',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en libras', max_digits=8, null=True, verbose_name='Peso (lb)'),
        ),
    ]
