# Generated by Django 6.0.6 on 2026-07-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0026_material_alto_material_ancho_material_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='pos_x_m',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distancia desde pared lateral izquierda', max_digits=8, verbose_name='Posición X (m)'),
        ),
        migrations.AddField(
            model_name='rack',
            name='pos_y_m',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distancia desde pared frontal', max_digits=8, verbose_name='Posición Y (m)'),
        ),
    ]
