# Generated by Django 6.0.6 on 2026-07-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0027_rack_bodega_area'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rackposition',
            unique_together=set(),
        ),
    ]
