# Generated by Django 6.0.6 on 2026-07-10 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0074_rack_bodega_area'),
        ('inventarios', '0028_multiple_materiales_por_celda'),
        ('mantenimiento', '0083_aviso_cierre_campos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['material', 'fecha_movimiento'], name='idx_mov_mat_fecha'),
        ),
    ]
