# Generated by Django 5.2.12 on 2026-07-10 20:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0029_idx_mov_mat_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='profundidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profundidad del material en cm', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Profundidad (cm)'),
        ),
    ]
