# Generated by Django 6.0.6 on 2026-07-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0030_material_profundidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='no_afecta_stock',
            field=models.BooleanField(default=False, help_text='Activar para materiales de ingreso que no deben afectar inventario (ej. compra de agua, servicios, etc.)', verbose_name='No Afecta Stock'),
        ),
    ]
