# Generated by Django 6.0.6 on 2026-07-21 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0031_material_no_afecta_stock'),
        ('presupuestos', '0066_refactor_area_manual_en_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tipo_material',
            field=models.CharField(choices=[('INSUMO', 'Insumo'), ('REPUESTO', 'Repuesto'), ('CONSUMIBLE', 'Consumible'), ('MEDICAMENTO', 'Medicamento'), ('HERRAMIENTA', 'Herramienta'), ('EPP', 'Equipo de Protección (EPP)'), ('SERVICIO', 'Servicio'), ('OTRO', 'Otro')], default='INSUMO', max_length=20, verbose_name='Tipo de Material'),
        ),
        migrations.CreateModel(
            name='SlotAlmacenCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('tipo', models.CharField(choices=[('ENTREGA', 'Entrega de materiales'), ('RECOLECCION', 'Recolección'), ('INVENTARIO', 'Conteo de inventario'), ('CAPACITACION', 'Capacitación'), ('OTRO', 'Otro')], default='ENTREGA', max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots_almacen_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_almacen_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('requisicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuestos.requisicion', verbose_name='Requisición')),
            ],
            options={
                'verbose_name': 'Slot de calendario de almacén',
                'verbose_name_plural': 'Slots de calendario de almacén',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_almacen', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Horario de almacén',
                'verbose_name_plural': 'Horarios de almacén',
                'unique_together': {('usuario', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
