# Generated by Django 6.0.6 on 2026-07-21 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0032_alter_material_tipo_material_slotalmacencalendario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disp_diaria_almacen', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Disponibilidad diaria',
                'verbose_name_plural': 'Disponibilidades diarias',
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('usuario', 'fecha', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
