# Generated by Django 6.0.6 on 2026-07-27 22:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0074_rack_bodega_area'),
        ('inventarios', '0033_disponibilidaddiaria'),
        ('mantenimiento', '0088_tecnicopuesto_puesto_en_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialUtilizadoOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad Utilizada')),
                ('comentario', models.CharField(blank=True, max_length=255, verbose_name='Comentario')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(blank=True, help_text='Activo al cual se le aplicó/instaló este material (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_aplicados', to='activos.activo', verbose_name='Activo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_en_ot', to='inventarios.material', verbose_name='Material')),
                ('movimiento', models.ForeignKey(blank=True, help_text='Movimiento de salida que respalda este consumo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_detallados', to='inventarios.movimientoinventario', verbose_name='Movimiento de Inventario')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_utilizados_detalle', to='mantenimiento.ordentrabajo', verbose_name='Orden de Trabajo')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_ot_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Utilizado en OT',
                'verbose_name_plural': 'Materiales Utilizados en OT',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
