# Generated by Django 6.0.6 on 2026-07-29 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0034_material_utilizado_ot'),
        ('presupuestos', '0070_codigoexoneracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='codigo_exoneracion',
            field=models.ForeignKey(blank=True, help_text='Código arancelario para calcular impuestos de importación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='presupuestos.codigoexoneracion', verbose_name='Código de Exoneración'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo_material',
            field=models.CharField(choices=[('INSUMO', 'Insumo'), ('REPUESTO', 'Repuesto'), ('CONSUMIBLE', 'Consumible'), ('MEDICAMENTO', 'Medicamento'), ('HERRAMIENTA', 'Herramienta'), ('EPP', 'Equipo de Protección (EPP)'), ('SERVICIO', 'Servicio'), ('ACTIVO', 'Activo'), ('OTRO', 'Otro')], default='INSUMO', max_length=20, verbose_name='Tipo de Material'),
        ),
    ]
