# Generated by Django 6.0.6 on 2026-07-29 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0035_add_codigo_exoneracion_material'),
        ('presupuestos', '0072_add_grupo_requisicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamaterial',
            name='codigo_exoneracion',
            field=models.ForeignKey(blank=True, help_text='Código arancelario asociado a esta categoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_material', to='presupuestos.codigoexoneracion', verbose_name='Código de Exoneración'),
        ),
    ]
