# Generated by Django 6.0.6 on 2026-08-07 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0041_add_embedding_local'),
        ('inventarios', '0036_add_codigo_exoneracion_to_categoriamaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmaterial',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_material', to='callcenter.solicitudticket', verbose_name='Ticket vinculado'),
        ),
    ]
