# Generated by Django 6.0.6 on 2026-08-21 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0075_add_codigo_exoneracion_fk_categoria'),
        ('inventarios', '0037_solicitudmaterial_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteMasivoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Ajuste')),
                ('archivo_csv', models.FileField(upload_to='inventarios/ajustes_masivos/', verbose_name='Archivo CSV')),
                ('total_procesados', models.PositiveIntegerField(default=0, verbose_name='Total Procesados')),
                ('total_ajustados', models.PositiveIntegerField(default=0, verbose_name='Total Ajustados')),
                ('total_errores', models.PositiveIntegerField(default=0, verbose_name='Total Errores')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('log_resultado', models.JSONField(blank=True, default=list, verbose_name='Log de Resultado')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_masivos', to='activos.ubicacion', verbose_name='Ubicación/Bodega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_masivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste Masivo de Inventario',
                'verbose_name_plural': 'Ajustes Masivos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
