# Generated by Django 6.0.6 on 2026-08-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0038_ajuste_masivo_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_AUTORIZACION', 'Pendiente de Autorización'), ('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado / Completado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=30),
        ),
    ]
