# Generated by Django 6.0.6 on 2026-08-25 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0075_add_codigo_exoneracion_fk_categoria'),
        ('inventarios', '0039_add_borrador_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='ubicacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_salida', to='activos.ubicacion'),
        ),
    ]
