# Generated by Django 6.0.6 on 2026-08-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0040_ubicacion_origen_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='es_tecnico',
            field=models.BooleanField(default=False, help_text='Si está activo, al despachar este material se debe vincular obligatoriamente con una Orden de Trabajo.', verbose_name='Material Técnico'),
        ),
    ]
