# Generated by Django 6.0.6 on 2026-08-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0042_add_entregar_a_to_solicitudmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, help_text='Código de barras físico del producto (EAN, UPC, etc.)', max_length=100, null=True, verbose_name='Código de Barras'),
        ),
    ]
