# Generated by Django 6.0.6 on 2026-09-01 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0043_add_codigo_barras_to_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmaterial',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por'),
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de autorización'),
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de rechazo'),
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_rechazadas', to=settings.AUTH_USER_MODEL, verbose_name='Rechazado por'),
        ),
    ]
