# Generated by Django 6.0.6 on 2026-09-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0044_solicitudmaterial_autorizado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_AUTORIZACION', 'Pendiente de Autorización'), ('PENDIENTE', 'Pendiente'), ('LISTO_RECOLECCION', 'Lista para Recolección'), ('ENTREGADO', 'Entregado / Completado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=30),
        ),
    ]
