# Generated by Django 6.0.6 on 2026-09-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0045_alter_solicitudmaterial_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmaterial',
            name='foto_entrega',
            field=models.ImageField(blank=True, null=True, upload_to='entregas/', verbose_name='Foto de entrega'),
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='recibe_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Recibido por (nombre)'),
        ),
    ]
