# Generated by Django 6.0.6 on 2026-09-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0046_solicitudmaterial_foto_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmaterial',
            name='fecha_despacho',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de despacho (listo para recolección)'),
        ),
    ]
