# Generated by Django 5.2.3 on 2025-12-18 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Diario, Semanal, Mensual', max_length=100, unique=True)),
                ('dias', models.PositiveIntegerField(help_text='Cantidad de días para el intervalo')),
            ],
            options={
                'verbose_name': 'Frecuencia',
                'verbose_name_plural': 'Frecuencias',
                'ordering': ['dias'],
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo_estimado', models.DurationField(blank=True, help_text='Tiempo estimado de ejecución (HH:MM:SS)', null=True)),
                ('cantidad_tecnicos', models.PositiveIntegerField(default=1, help_text='Cantidad de técnicos sugerida')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('frecuencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas', to='mantenimiento.frecuencia')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
            },
        ),
        migrations.CreateModel(
            name='PasoRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(help_text='Descripción detallada del paso a realizar')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='mantenimiento.rutina')),
            ],
            options={
                'verbose_name': 'Paso de Rutina',
                'verbose_name_plural': 'Pasos de Rutina',
                'ordering': ['rutina', 'orden'],
            },
        ),
    ]
