# Generated by Django 5.2.3 on 2025-12-18 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_horario_diahorario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestriccionCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha no laborable o restringida', unique=True)),
                ('motivo', models.CharField(help_text='Razón de la restricción (ej. Feriado, Vacaciones)', max_length=200)),
            ],
            options={
                'verbose_name': 'Restricción de Calendario',
                'verbose_name_plural': 'Restricciones de Calendario',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio para la generación de órdenes')),
                ('fecha_fin', models.DateField(blank=True, help_text='Opcional: Fecha límite (un año por defecto si está vacío)', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('horario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones', to='mantenimiento.horario')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='mantenimiento.rutina')),
            ],
            options={
                'verbose_name': 'Programación',
                'verbose_name_plural': 'Programaciones',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EJECUCION', 'En Ejecución'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='mantenimiento.rutina')),
                ('programacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='mantenimiento.programacion')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['fecha_programada'],
            },
        ),
    ]
