# Generated by Django 5.2.3 on 2025-12-18 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_marca_rename_marca_activo_marca_legacy_and_more'),
        ('mantenimiento', '0003_restriccioncalendario_programacion_ordentrabajo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['fecha_programada', 'activo'], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='activos.activo'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='activos',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los activos (hijos del área) a programar', related_name='programaciones', to='activos.activo'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones', to='activos.ubicacion'),
        ),
    ]
