# Generated by Django 5.2.3 on 2025-12-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_marca_rename_marca_activo_marca_legacy_and_more'),
        ('mantenimiento', '0004_alter_ordentrabajo_options_ordentrabajo_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='area',
        ),
        migrations.AddField(
            model_name='programacion',
            name='areas',
            field=models.ManyToManyField(blank=True, help_text='Seleccione las áreas para filtrar los activos', related_name='programaciones', to='activos.ubicacion'),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='activos',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los activos específicos a programar', related_name='programaciones', to='activos.activo'),
        ),
    ]
