# Generated by Django 5.2.3 on 2025-12-18 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_remove_programacion_area_programacion_areas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['inicio_programado', 'activo'], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fecha_programada',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fin_programado',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 18, 0, 26, 46, 106345), help_text='Fecha y hora de fin prevista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='inicio_programado',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 18, 0, 26, 46, 106574), help_text='Fecha y hora de inicio prevista'),
            preserve_default=False,
        ),
    ]
