# Generated by Django 5.2.3 on 2025-12-18 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_marca_rename_marca_activo_marca_legacy_and_more'),
        ('mantenimiento', '0006_alter_ordentrabajo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['inicio_programado', 'ubicacion'], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='activos.ubicacion'),
        ),
    ]
