# Generated by Django 5.2.3 on 2025-12-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_alter_ordentrabajo_options_ordentrabajo_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='procesada',
            field=models.BooleanField(default=False, help_text='Indica si ya se han generado las órdenes para esta programación'),
        ),
    ]
