# Generated by Django 5.2.3 on 2025-12-18 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0009_disciplina_subdisciplina_rutina_sub_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.disciplina', verbose_name='Filtrar por Disciplina'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='sub_disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.subdisciplina', verbose_name='Filtrar por Sub-Disciplina'),
        ),
    ]
