# Generated by Django 5.2.3 on 2025-12-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0010_programacion_disciplina_programacion_sub_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='sub_disciplina',
        ),
    ]
