# Generated by Django 5.2.3 on 2025-12-19 07:45

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0011_remove_disciplina_filters'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='subdisciplina',
        #     name='disciplina',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='subdisciplina',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='rutina',
        #     name='sub_disciplina',
        # ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('padre', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='mantenimiento.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría de la rutina (puede ser de cualquier nivel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas', to='mantenimiento.categoria'),
        ),
        # migrations.DeleteModel(
        #     name='Disciplina',
        # ),
        # migrations.DeleteModel(
        #     name='SubDisciplina',
        # ),
    ]
