# Generated by Django 5.2.3 on 2025-12-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0012_remove_subdisciplina_disciplina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='sub_disciplina',
        ),
        migrations.DeleteModel(
            name='SubDisciplina',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
