# Generated by Django 5.2.3 on 2025-12-20 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0010_categoria_icono'),
        ('mantenimiento', '0013_remove_subdisciplina_disciplina_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo',
            field=models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRECTIVA', 'Correctiva')], default='PREVENTIVA', max_length=15),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='mantenimiento.rutina'),
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la falla o solicitud')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('PROCESO', 'En Proceso'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avisos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to='activos.activo')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_reportados', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='activos.ubicacion')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='aviso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='mantenimiento.aviso'),
        ),
    ]
