# Generated by Django 5.2.7 on 2025-12-22 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0014_ordentrabajo_prioridad_ordentrabajo_tecnico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('anio', models.PositiveIntegerField(default=2025)),
                ('nombre', models.CharField(help_text='Ej: Mantenimiento Preventivo Enero 2024', max_length=200)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('EJECUCION', 'En Ejecución'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planificación Mensual',
                'verbose_name_plural': 'Planificaciones Mensuales',
                'unique_together': {('mes', 'anio')},
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='planificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='mantenimiento.planificacionmensual', verbose_name='Plan Mensual'),
        ),
    ]
