# Generated by Django 5.2.7 on 2025-12-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0015_planificacionmensual_ordentrabajo_planificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('PROCESO', 'En Proceso'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], db_index=True, default='ABIERTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], db_index=True, default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EJECUCION', 'En Ejecución'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PROGRAMADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='inicio_programado',
            field=models.DateTimeField(db_index=True, help_text='Fecha y hora de inicio prevista'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], db_index=True, default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tipo',
            field=models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRECTIVA', 'Correctiva')], db_index=True, default='PREVENTIVA', max_length=15),
        ),
        migrations.AlterField(
            model_name='planificacionmensual',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('EJECUCION', 'En Ejecución'), ('CERRADO', 'Cerrado')], db_index=True, default='BORRADOR', max_length=20),
        ),
    ]
