# Generated by Django 5.2.7 on 2025-12-22 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0016_alter_aviso_estado_alter_aviso_prioridad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='level',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='mantenimiento.categoria'),
        ),
    ]
