# Generated by Django 5.2.7 on 2025-12-23 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0018_remove_activo_categoria'),
        ('mantenimiento', '0017_remove_categoria_level_remove_categoria_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='categoria_activo',
            field=models.ForeignKey(blank=True, help_text='Tipo de equipo al que aplica esta rutina (ej: Motores, Bombas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas', to='activos.categoria'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Clasificación de mantenimiento (ej: Mecánica, Eléctrica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas', to='mantenimiento.categoria'),
        ),
    ]
