# Generated by Django 5.2.7 on 2025-12-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0018_remove_activo_categoria'),
        ('mantenimiento', '0018_rutina_categoria_activo_alter_rutina_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='activo',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='activos',
            field=models.ManyToManyField(blank=True, related_name='ordenes_trabajo', to='activos.activo'),
        ),
    ]
