# Generated by Django 5.2.3 on 2025-12-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0019_remove_ordentrabajo_activo_ordentrabajo_activos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='categoria_activo',
        ),
    ]
