# Generated by Django 5.2.7 on 2025-12-29 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0020_remove_categoria_mantenimiento_categoria'),
        ('mantenimiento', '0020_remove_rutina_categoria_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_activo',
            field=models.OneToOneField(blank=True, help_text='Vincular con una categoría de activo particular', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimiento_categoria', to='activos.categoria'),
        ),
    ]
