# Generated by Django 5.2.7 on 2025-12-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0021_categoria_categoria_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='herramientas',
            field=models.TextField(blank=True, help_text='Herramientas y materiales necesarios', null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='procedimiento',
            field=models.TextField(blank=True, help_text='Pasos detallados de la rutina', null=True),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='cantidad_tecnicos',
            field=models.IntegerField(default=1, help_text='Número de técnicos requeridos'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='tiempo_estimado',
            field=models.DurationField(blank=True, help_text='Tiempo estimado para completar la rutina (ej: 02:00:00)', null=True),
        ),
    ]
