# Generated by Django 5.2.7 on 2025-12-29 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0022_rutina_herramientas_rutina_procedimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
            },
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='procedimiento',
        ),
        migrations.CreateModel(
            name='PasoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(help_text='Descripción de la tarea a realizar')),
                ('verificacion', models.CharField(blank=True, help_text='¿Qué debe verificar el técnico?', max_length=100, null=True)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='mantenimiento.procedimiento')),
            ],
            options={
                'verbose_name': 'Paso de Procedimiento',
                'verbose_name_plural': 'Pasos de Procedimiento',
                'ordering': ['procedimiento', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='procedimiento_estandar',
            field=models.ForeignKey(blank=True, help_text='Elija el manual de pasos a seguir', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas', to='mantenimiento.procedimiento'),
        ),
        migrations.DeleteModel(
            name='PasoRutina',
        ),
    ]
