# Generated by Django 5.2.7 on 2025-12-30 22:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0023_procedimiento_remove_rutina_procedimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='color',
            field=colorfield.fields.ColorField(default='#3b82f6', help_text='Color para identificar este horario en el cronograma', image_field=None, max_length=25, samples=None),
        ),
    ]
