# Generated by Django 5.2.7 on 2026-01-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0024_horario_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacionmensual',
            name='anio',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
