# Generated by Django 5.2.7 on 2026-01-02 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0025_alter_planificacionmensual_anio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('SUCCESS', 'Éxito'), ('ERROR', 'Error'), ('INFO', 'Información'), ('WARNING', 'Advertencia')], default='INFO', max_length=10)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_mantenimiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de Mantenimiento',
                'verbose_name_plural': 'Notificaciones de Mantenimiento',
                'ordering': ['-creado_en'],
            },
        ),
    ]
