# Generated by Django 5.2.7 on 2026-01-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0026_notificacionmantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('ESPERA', 'En Espera de Programación'), ('PROGRAMADA', 'Programada'), ('EJECUCION', 'En Ejecución'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ESPERA', max_length=20),
        ),
    ]
