# Generated by Django 5.2.7 on 2026-01-02 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0027_alter_ordentrabajo_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_real', models.DateTimeField(verbose_name='Inicio Real')),
                ('fecha_fin_real', models.DateTimeField(verbose_name='Fin Real')),
                ('horas_hombre', models.FloatField(default=0, help_text='Total de Horas-Hombre (HH) consumidas', verbose_name='HH Totales')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios Técnicos / Hallazgos')),
                ('materiales_utilizados', models.TextField(blank=True, help_text='Listado de materiales o repuestos utilizados', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden_trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cierre', to='mantenimiento.ordentrabajo', verbose_name='Orden de Trabajo')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_ot', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsable')),
            ],
            options={
                'verbose_name': 'Cierre de Orden de Trabajo',
                'verbose_name_plural': 'Cierres de Órdenes de Trabajo',
            },
        ),
    ]
