# Generated by Django 5.2.7 on 2026-01-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0028_cierreordentrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='tipo',
            field=models.CharField(choices=[('AVERIA', 'Avería / Falla (M2)'), ('SOLICITUD', 'Solicitud de Servicio (M1)'), ('MEJORA', 'Mejora / Modificación'), ('LEGAL', 'Requerimiento Legal / Seguridad')], db_index=True, default='SOLICITUD', max_length=15),
        ),
    ]
