# Generated by Django 5.2.7 on 2026-01-07 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mantenimiento', '0029_aviso_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='equipo',
            field=models.ForeignKey(blank=True, help_text='Equipo o Grupo de trabajo asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_equipo', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tecnico',
            field=models.ForeignKey(blank=True, help_text='Técnico específico asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
