# Generated by Django 5.2.7 on 2026-01-09 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0030_ordentrabajo_equipo_alter_ordentrabajo_tecnico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuestoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Puesto de Trabajo',
                'verbose_name_plural': 'Puestos de Trabajo',
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='puesto_trabajo',
            field=models.ForeignKey(blank=True, help_text='Puesto de trabajo responsable de esta rutina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas', to='mantenimiento.puestotrabajo'),
        ),
        migrations.CreateModel(
            name='TecnicoPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tecnicos', to='mantenimiento.puestotrabajo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal de Mantenimiento',
                'verbose_name_plural': 'Personal de Mantenimiento',
            },
        ),
    ]
