# Generated by Django 5.2.7 on 2026-01-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0031_puestotrabajo_rutina_puesto_trabajo_tecnicopuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicopuesto',
            name='horas_semanales_max',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Capacidad máxima de horas por semana', max_digits=5, max_length=5),
        ),
    ]
