# Generated by Django 5.2.7 on 2026-01-09 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0032_tecnicopuesto_horas_semanales_max'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pasoprocedimiento',
            name='rango_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pasoprocedimiento',
            name='rango_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pasoprocedimiento',
            name='tipo_respuesta',
            field=models.CharField(choices=[('INSTRUCCION', 'Instrucción (Solo lectura)'), ('CHECK', 'Check (Si/No/NA)'), ('NUMERICO', 'Valor Numérico'), ('TEXTO', 'Texto Libre')], default='INSTRUCCION', max_length=20),
        ),
        migrations.AddField(
            model_name='pasoprocedimiento',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Ej: Bar, °C, Amperios', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pasoprocedimiento',
            name='valor_objetivo',
            field=models.FloatField(blank=True, help_text='Valor ideal esperado', null=True),
        ),
        migrations.CreateModel(
            name='ValorPasoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numerico', models.FloatField(blank=True, null=True)),
                ('valor_bool', models.BooleanField(blank=True, help_text='Para tipos CHECK', null=True)),
                ('no_aplica', models.BooleanField(default=False)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios adicionales del técnico para este paso', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('capturado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_checklist', to='mantenimiento.ordentrabajo')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.pasoprocedimiento')),
            ],
            options={
                'verbose_name': 'Valor de Checklist',
                'verbose_name_plural': 'Valores de Checklist',
                'unique_together': {('orden_trabajo', 'paso')},
            },
        ),
    ]
