# Generated by Django 5.2.7 on 2026-01-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0029_documentomedicion_activo'),
        ('mantenimiento', '0033_pasoprocedimiento_rango_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasoprocedimiento',
            name='punto_medicion_codigo',
            field=models.CharField(blank=True, help_text="Vincular por código (ej: 'NIVEL_ACEITE') para procedimientos genéricos", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pasoprocedimiento',
            name='punto_medicion_exacto',
            field=models.ForeignKey(blank=True, help_text='Vincular a un punto específico (procedimientos detallados)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_procedimiento', to='activos.puntomedicion'),
        ),
        migrations.AlterField(
            model_name='pasoprocedimiento',
            name='tipo_respuesta',
            field=models.CharField(choices=[('INSTRUCCION', 'Instrucción (Solo lectura)'), ('CHECK', 'Check (Si/No/NA)'), ('NUMERICO', 'Valor Numérico'), ('TEXTO', 'Texto Libre'), ('MEDICION', 'Punto de Medición (SAP)')], default='INSTRUCCION', max_length=20),
        ),
    ]
