# Generated by Django 5.2.7 on 2026-01-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0034_pasoprocedimiento_punto_medicion_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(blank=True, help_text='Deje vacío para generar un nombre automático basado en frecuencia y categoría', max_length=200),
        ),
    ]
