# Generated by Django 5.2.7 on 2026-01-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0035_alter_rutina_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='mantenimiento.falla')),
                ('puesto_trabajo', models.ForeignKey(blank=True, help_text='Vincular a un puesto si es el nodo raíz', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogo_fallas', to='mantenimiento.puestotrabajo')),
            ],
            options={
                'verbose_name': 'Falla',
                'verbose_name_plural': 'Catálogo de Fallas',
                'unique_together': {('nombre', 'padre')},
            },
        ),
        migrations.AddField(
            model_name='aviso',
            name='falla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to='mantenimiento.falla'),
        ),
    ]
