# Generated by Django 5.2.7 on 2026-01-13 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0036_falla_aviso_falla'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='falla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='mantenimiento.falla'),
        ),
    ]
