# Generated by Django 5.2.7 on 2026-01-13 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0037_ordentrabajo_falla'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='avisos/fotos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='mantenimiento.aviso')),
            ],
            options={
                'verbose_name': 'Foto de Aviso',
                'verbose_name_plural': 'Fotos de Aviso',
            },
        ),
    ]
