# Generated by Django 5.2.7 on 2026-01-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0038_fotoaviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='codigo_rutina',
            field=models.CharField(blank=True, help_text='Código identificador de la rutina', max_length=50, null=True, unique=True),
        ),
    ]
