# Generated by Django 5.2.7 on 2026-01-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0039_rutina_codigo_rutina'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='codigo_de_orden',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Código de Orden'),
        ),
    ]
