# Generated by Django 5.2.7 on 2026-01-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0040_ordentrabajo_codigo_de_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción Corta'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='descripcion_detallada',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Detallada'),
        ),
    ]
