# Generated by Django 5.2.7 on 2026-02-02 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0041_ordentrabajo_descripcion_corta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AddField(
            model_name='tecnicopuesto',
            name='dni',
            field=models.CharField(blank=True, help_text='Ej: 0501-1986-06985', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tecnicopuesto',
            name='fecha_alta',
            field=models.DateField(blank=True, help_text='Fecha de ingreso a la empresa', null=True),
        ),
        migrations.AddField(
            model_name='tecnicopuesto',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnicopuesto',
            name='tipo_sangre',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tecnicopuesto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='mantenimiento.empresa'),
        ),
    ]
