# Generated by Django 5.2.7 on 2026-02-04 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0042_empresa_tecnicopuesto_dni_tecnicopuesto_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnicopuesto',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicos', to='mantenimiento.puestotrabajo'),
        ),
    ]
