# Generated by Django 5.2.7 on 2026-02-24 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0043_alter_tecnicopuesto_puesto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tecnicopuesto',
            options={'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.AddField(
            model_name='tecnicopuesto',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido(s)'),
        ),
        migrations.AddField(
            model_name='tecnicopuesto',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='tecnicopuesto',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_tecnico', to=settings.AUTH_USER_MODEL),
        ),
    ]
