# Generated by Django 5.1.15 on 2026-02-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0044_alter_tecnicopuesto_options_tecnicopuesto_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='codigo_de_orden',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Código de Orden'),
        ),
    ]
