# Generated by Django 5.1.15 on 2026-03-03 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0051_ubicacion_es_almacen'),
        ('mantenimiento', '0045_alter_ordentrabajo_codigo_de_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(blank=True, help_text='Deje vacío para generar un nombre automático basado en frecuencia y tipo', max_length=200),
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria_activo', models.OneToOneField(blank=True, help_text='Vincular con una categoría de activo particular', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimiento_tipo', to='activos.categoria')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='mantenimiento.tipo')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Clasificación de mantenimiento (ej: Mecánica, Eléctrica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas', to='mantenimiento.tipo'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
