# Generated by Django 5.1.15 on 2026-03-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0046_remove_rutina_categoria_alter_rutina_nombre_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
    ]
