# Generated by Django 5.2.7 on 2026-03-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0047_tipo_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='es_invasiva',
            field=models.BooleanField(default=False, help_text='¿Requiere apagar equipos o realizarse en horarios no operativos?'),
        ),
    ]
