# Generated by Django 5.2.7 on 2026-03-04 20:37

import django.db.models.deletion
from django.db import migrations, models


def clear_valorpasoorden(apps, schema_editor):
    ValorPasoOrden = apps.get_model('mantenimiento', 'ValorPasoOrden')
    ValorPasoOrden.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0054_archivoaltabaja'),
        ('mantenimiento', '0048_rutina_es_invasiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasoRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(help_text='Descripción de la tarea a realizar')),
                ('tipo_respuesta', models.CharField(choices=[('INSTRUCCION', 'Instrucción (Solo lectura)'), ('CHECK', 'Check (Si/No/NA)'), ('NUMERICO', 'Valor Numérico'), ('TEXTO', 'Texto Libre'), ('MEDICION', 'Punto de Medición (SAP)')], default='INSTRUCCION', max_length=20)),
                ('verificacion', models.CharField(blank=True, help_text='¿Qué debe verificar el técnico?', max_length=100, null=True)),
                ('unidad_medida', models.CharField(blank=True, help_text='Ej: Bar, °C, Amperios', max_length=20, null=True)),
                ('valor_objetivo', models.FloatField(blank=True, help_text='Valor ideal esperado', null=True)),
                ('rango_min', models.FloatField(blank=True, null=True)),
                ('rango_max', models.FloatField(blank=True, null=True)),
                ('punto_medicion_codigo', models.CharField(blank=True, help_text="Vincular por código (ej: 'NIVEL_ACEITE') para procedimientos genéricos", max_length=50, null=True)),
                ('punto_medicion_exacto', models.ForeignKey(blank=True, help_text='Vincular a un punto específico (procedimientos detallados)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_procedimiento', to='activos.puntomedicion')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='mantenimiento.rutina')),
            ],
            options={
                'verbose_name': 'Paso de Rutina',
                'verbose_name_plural': 'Pasos de Rutina',
                'ordering': ['rutina', 'orden'],
            },
        ),
        migrations.RunPython(clear_valorpasoorden, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='valorpasoorden',
            name='paso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.pasorutina'),
        ),
        migrations.RemoveField(
            model_name='pasoprocedimiento',
            name='procedimiento',
        ),
        migrations.RemoveField(
            model_name='pasoprocedimiento',
            name='punto_medicion_exacto',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='procedimiento_estandar',
        ),
        migrations.DeleteModel(
            name='Procedimiento',
        ),
        migrations.DeleteModel(
            name='PasoProcedimiento',
        ),
    ]
