# Generated by Django 5.2.12 on 2026-03-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0049_remove_pasoprocedimiento_procedimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasorutina',
            name='tipo_respuesta',
            field=models.CharField(choices=[('INSTRUCCION', 'Instrucción (Solo lectura)'), ('CHECK', 'Check (Si/No/NA)'), ('NUMERICO', 'Valor Numérico'), ('TEXTO', 'Texto Libre'), ('MEDICION', 'Punto de Medición (SAP)'), ('HEADER', 'ENCABEZADO / GRUPO')], default='INSTRUCCION', max_length=20),
        ),
    ]
