# Generated by Django 5.2.12 on 2026-03-20 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0050_alter_pasorutina_tipo_respuesta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor asignado a la orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_supervisadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
