# Generated by Django 5.2.12 on 2026-03-23 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0051_ordentrabajo_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ot_archivos/')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('IMAGEN', 'Imagen Fotográfica'), ('DOCUMENTO', 'Documento/PDF'), ('OTRO', 'Otro Archivo')], default='OTRO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='mantenimiento.ordentrabajo')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de OT',
                'verbose_name_plural': 'Archivos de OT',
                'ordering': ['-creado_en'],
            },
        ),
    ]
