# Generated by Django 5.2.12 on 2026-03-24 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0052_archivoordentrabajo'),
        ('proyectos', '0007_actividad_predecesora'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to='proyectos.proyecto', verbose_name='Proyecto'),
        ),
    ]
