# Generated by Django 5.2.12 on 2026-03-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0053_aviso_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='falla',
            name='tipo_aviso',
            field=models.CharField(blank=True, choices=[('AVERIA', 'Avería / Falla (M2)'), ('SOLICITUD', 'Solicitud de Servicio (M1)'), ('MEJORA', 'Mejora / Modificación'), ('LEGAL', 'Requerimiento Legal / Seguridad')], db_index=True, help_text='Filtrar por este tipo de aviso en la App móvil', max_length=20, null=True),
        ),
    ]
