# Generated by Django 5.2.12 on 2026-03-24 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0054_falla_tipo_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='falla',
            name='puestos_trabajo',
            field=models.ManyToManyField(blank=True, help_text='Vincular a puestos si es el nodo raíz', related_name='catalogos_fallas', to='mantenimiento.puestotrabajo'),
        ),
        migrations.AlterField(
            model_name='falla',
            name='padre',
            field=models.ForeignKey(blank=True, help_text='Dejar en blanco si es nivel superior', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='mantenimiento.falla'),
        ),
    ]
