# Generated by Django 5.2.12 on 2026-03-24 02:50

from django.db import migrations


def copy_puestos(apps, schema_editor):
    Falla = apps.get_model('mantenimiento', 'Falla')
    for falla in Falla.objects.all():
        if falla.puesto_trabajo_id:
            falla.puestos_trabajo.add(falla.puesto_trabajo_id)

class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0055_falla_m2m_puestos'),
    ]

    operations = [
        migrations.RunPython(copy_puestos, reverse_code=migrations.RunPython.noop),
    ]
