# Generated by Django 5.2.12 on 2026-03-24 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0056_copy_puestos_trabajo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falla',
            name='puesto_trabajo',
        ),
    ]
