# Generated by Django 5.2.12 on 2026-03-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0057_remove_falla_puesto_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoaviso',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
    ]
