# Generated by Django 5.2.12 on 2026-03-26 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0058_fotoaviso_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Reporte'),
        ),
    ]
