# Generated by Django 5.2.12 on 2026-03-27 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0059_aviso_fecha_cierre_alter_aviso_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoordentrabajo',
            name='paso',
            field=models.ForeignKey(blank=True, help_text='Paso del checklist al que pertenece esta foto (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_evidencia', to='mantenimiento.pasorutina'),
        ),
        migrations.AlterField(
            model_name='pasorutina',
            name='tipo_respuesta',
            field=models.CharField(choices=[('INSTRUCCION', 'Instrucción (Solo lectura)'), ('CHECK', 'Check (Si/No/NA)'), ('NUMERICO', 'Valor Numérico'), ('TEXTO', 'Texto Libre'), ('MEDICION', 'Punto de Medición (SAP)'), ('FOTO', 'Registro Fotográfico'), ('HEADER', 'ENCABEZADO / GRUPO')], default='INSTRUCCION', max_length=20),
        ),
    ]
