# Generated by Django 5.2.12 on 2026-04-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0060_add_foto_tipo_and_paso_to_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='tipo',
            field=models.CharField(choices=[('AVERIA', 'Avería / Falla (M2)'), ('SOLICITUD', 'Solicitud de Servicio (M1)'), ('MEJORA', 'Mejora / Modificación'), ('LEGAL', 'Requerimiento Legal / Seguridad'), ('MAL_USO', 'Mal Uso de las Instalaciones')], db_index=True, default='SOLICITUD', max_length=15),
        ),
        migrations.AlterField(
            model_name='falla',
            name='tipo_aviso',
            field=models.CharField(blank=True, choices=[('AVERIA', 'Avería / Falla (M2)'), ('SOLICITUD', 'Solicitud de Servicio (M1)'), ('MEJORA', 'Mejora / Modificación'), ('LEGAL', 'Requerimiento Legal / Seguridad'), ('MAL_USO', 'Mal Uso de las Instalaciones')], db_index=True, help_text='Filtrar por este tipo de aviso en la App móvil', max_length=20, null=True),
        ),
    ]
