# Generated by Django 5.2.12 on 2026-04-16 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_seed_elementoapp'),
        ('mantenimiento', '0061_alter_aviso_tipo_alter_falla_tipo_aviso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to='core.departamento', verbose_name='Departamento Asignado'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Asignado'),
        ),
    ]
