# Generated by Django 5.2.12 on 2026-04-20 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0062_aviso_departamento_aviso_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicopuesto',
            name='codigo_asistencia',
            field=models.CharField(blank=True, help_text='ID del carnet físico (ej. PERSONAL0001)', max_length=50, null=True, unique=True, verbose_name='Código QR Carnet'),
        ),
        migrations.AddField(
            model_name='tecnicopuesto',
            name='esta_vigente',
            field=models.BooleanField(default=True, help_text='Si no está vigente, no podrá ingresar al recinto', verbose_name='Vigente'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, db_index=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.empresa', verbose_name='Empresa en Registro')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='mantenimiento.tecnicopuesto', verbose_name='Técnico')),
                ('usuario_estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operador Estación')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencias',
                'ordering': ['-fecha', '-hora_entrada'],
                'unique_together': {('tecnico', 'fecha')},
            },
        ),
    ]
