# Generated by Django 5.2.12 on 2026-04-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0063_tecnicopuesto_codigo_asistencia_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tecnicopuesto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tecnicos/', verbose_name='Foto de Perfil'),
        ),
    ]
