# Generated by Django 5.2.12 on 2026-04-21 18:17

import django.db.models.deletion
import mantenimiento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0064_alter_asistencia_unique_together_tecnicopuesto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('RTN', 'RTN / Identidad Tributaria'), ('ACTA_CONST', 'Acta Constitutiva / Poder'), ('CONSTANCIA_RIESGO', 'Constancia de Prevención de Riesgos'), ('POLIZA_SEGURO', 'Póliza de Seguro de Vida/Daños'), ('CONTRATO', 'Contrato Marco / Licitación'), ('OTRO', 'Otro (Aclarar en descripción)')], max_length=50)),
                ('archivo', models.FileField(help_text='Archivo físico (PDF/Imagen) subido a MinIO en la carpeta de la empresa', upload_to=mantenimiento.models.empresa_directory_path)),
                ('descripcion', models.CharField(blank=True, help_text="Aclaración adicional si es 'OTRO'", max_length=200, null=True)),
                ('es_valido', models.BooleanField(default=True, help_text='Marcar para validar formalmente que el documento está en regla. Si no es válido, no contará para la autorización de QR.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='mantenimiento.empresa')),
            ],
            options={
                'verbose_name': 'Expediente de Empresa',
                'verbose_name_plural': 'Expedientes de Empresas',
                'unique_together': {('empresa', 'tipo_documento')},
            },
        ),
    ]
