# Generated by Django 5.2.12 on 2026-04-22 09:49

import django.db.models.deletion
import mantenimiento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0065_documentoempresa'),
        ('servicios', '0011_add_auditoria_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoempresa',
            options={'verbose_name': 'Documento de Subcontratista', 'verbose_name_plural': 'Documentos de Subcontratistas'},
        ),
        migrations.AlterUniqueTogether(
            name='documentoempresa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentoempresa',
            name='anio',
            field=models.PositiveIntegerField(blank=True, help_text='Año de aplicación (ej. 2026)', null=True),
        ),
        migrations.AddField(
            model_name='documentoempresa',
            name='mes',
            field=models.PositiveIntegerField(blank=True, help_text='Mes de aplicación (1-12). Dejar vacío si es DOC ÚNICO.', null=True),
        ),
        migrations.AddField(
            model_name='tipo',
            name='servicio',
            field=models.ForeignKey(blank=True, help_text='Servicio al que pertenece esta categoría (se hereda a rutinas e hijos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_mantenimiento', to='servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='documentoempresa',
            name='archivo',
            field=models.FileField(help_text='Archivo físico a subir a MinIO', upload_to=mantenimiento.models.empresa_directory_path),
        ),
        migrations.AlterField(
            model_name='documentoempresa',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Aclaración adicional', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='documentoempresa',
            name='es_valido',
            field=models.BooleanField(default=True, help_text='Si no es válido, no contará para la autorización de QR.'),
        ),
        migrations.AlterField(
            model_name='documentoempresa',
            name='tipo_documento',
            field=models.CharField(choices=[('RTN', 'RTN / Identidad Tributaria (Único)'), ('ACTA_CONST', 'Acta Constitutiva / Poder (Único)'), ('CONTRATO', 'Contrato Marco (Único)'), ('PLANILLA_IHSS', 'Planilla IHSS'), ('ALTAS_BAJAS', 'Altas y Bajas'), ('EXPEDIENTE_MENSUAL', 'Expediente Mensual'), ('REPORTES', 'Reportes / Otros Entregables'), ('OTRO', 'Otro (Especificar)')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='documentoempresa',
            unique_together={('empresa', 'tipo_documento', 'mes', 'anio')},
        ),
    ]
