# Generated by Django 5.2.12 on 2026-04-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0066_tipo_add_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='equipo_parado',
            field=models.BooleanField(default=False, help_text="Si se marca, el activo pasará a 'Fuera de Servicio' mientras la orden esté abierta", verbose_name='¿Equipo Parado?'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tipo',
            field=models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRECTIVA', 'Correctiva'), ('NO_PROGRAMADA', 'No Programada')], db_index=True, default='PREVENTIVA', max_length=15),
        ),
    ]
