# Generated by Django 5.2.12 on 2026-04-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0067_ordentrabajo_equipo_parado_alter_ordentrabajo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='equipo_parado',
            field=models.BooleanField(default=False, help_text='Marque esta opción si la avería ha detenido el funcionamiento del equipo.', verbose_name='¿Equipo Parado?'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='fecha_fin_parada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de Parada'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='fecha_inicio_parada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de Parada'),
        ),
    ]
