# Generated by Django 5.2.12 on 2026-04-24 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0070_downtimeactivo_aviso_and_more'),
        ('mantenimiento', '0068_aviso_equipo_parado_aviso_fecha_fin_parada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='ubicacion_predeterminada',
            field=models.ForeignKey(blank=True, help_text='Ubicación física predeterminada donde se suele realizar esta rutina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_predeterminadas', to='activos.ubicacion'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='equipo_parado',
            field=models.BooleanField(blank=True, default=False, help_text='Marque esta opción si la avería ha detenido el funcionamiento del equipo.', null=True, verbose_name='¿Equipo Parado?'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='equipo_parado',
            field=models.BooleanField(blank=True, default=False, help_text="Si se marca, el activo pasará a 'Fuera de Servicio' mientras la orden esté abierta", null=True, verbose_name='¿Equipo Parado?'),
        ),
    ]
