# Generated by Django 5.2.12 on 2026-04-24 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0070_downtimeactivo_aviso_and_more'),
        ('mantenimiento', '0069_rutina_ubicacion_predeterminada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='categoria_activo',
            field=models.ForeignKey(blank=True, help_text='Categoría de activo a la que aplica esta rutina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_categoria', to='activos.categoria'),
        ),
    ]
