# Generated by Django 5.2.12 on 2026-04-24 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0070_rutina_categoria_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='horario_predeterminado',
            field=models.ForeignKey(blank=True, help_text='Horario predeterminado sugerido para la ejecución de esta rutina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_predeterminadas', to='mantenimiento.horario'),
        ),
    ]
