# Generated by Django 5.2.12 on 2026-04-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0071_rutina_horario_predeterminado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='horario',
        ),
        migrations.AddField(
            model_name='programacion',
            name='horarios',
            field=models.ManyToManyField(blank=True, help_text='Seleccione uno o más horarios para la programación', related_name='programaciones', to='mantenimiento.horario'),
        ),
    ]
