# Generated by Django 5.2.12 on 2026-04-27 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0072_remove_programacion_horario_programacion_horarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='empresa_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_responsables', to='mantenimiento.empresa'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tecnicos',
            field=models.ManyToManyField(blank=True, help_text='Equipo de técnicos asignados', related_name='ordenes_colaboracion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tecnico',
            field=models.ForeignKey(blank=True, help_text='Técnico líder/responsable principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
