# Generated by Django 5.2.12 on 2026-05-05 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0073_ordentrabajo_empresa_responsable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='tecnico_puesto',
            field=models.ForeignKey(blank=True, help_text='Técnico asignado (con o sin usuario)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to='mantenimiento.tecnicopuesto', verbose_name='Personal Responsable'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tecnico',
            field=models.ForeignKey(blank=True, help_text='Usuario líder (requiere cuenta de sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
