# Generated by Django 5.2.12 on 2026-05-05 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0074_ordentrabajo_tecnico_puesto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='colaboradores_puesto',
            field=models.ManyToManyField(blank=True, help_text='Equipo de técnicos asignados (Personal)', related_name='ordenes_colaboradas', to='mantenimiento.tecnicopuesto'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tecnicos',
            field=models.ManyToManyField(blank=True, help_text='Equipo de técnicos asignados (Usuarios)', related_name='ordenes_colaboracion', to=settings.AUTH_USER_MODEL),
        ),
    ]
