# Generated by Django 5.2.12 on 2026-05-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0075_ordentrabajo_colaboradores_puesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoordentrabajo',
            name='momento',
            field=models.CharField(choices=[('INICIO', 'Al Iniciar'), ('DURANTE', 'Durante la Tarea'), ('CIERRE', 'Al Finalizar')], db_index=True, default='DURANTE', max_length=10),
        ),
    ]
