# Generated by Django 5.2.12 on 2026-05-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0076_archivoordentrabajo_momento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dynamics_guid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='GUID de Dynamics'),
        ),
    ]
