# Generated by Django 5.2.12 on 2026-05-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0077_empresa_dynamics_guid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPasoRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Foto o video de referencia', upload_to='rutinas/pasos/media/')),
                ('tipo', models.CharField(choices=[('IMAGEN', 'Imagen'), ('VIDEO', 'Video')], default='IMAGEN', max_length=10)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción breve del archivo', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='mantenimiento.pasorutina')),
            ],
            options={
                'verbose_name': 'Media de Paso',
                'verbose_name_plural': 'Media de Pasos',
                'ordering': ['paso', 'orden'],
            },
        ),
    ]
