# Generated by Django 5.2.12 on 2026-05-12 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0070_downtimeactivo_aviso_and_more'),
        ('mantenimiento', '0078_add_mediapaso_rutina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='categoria_activo',
            field=models.ForeignKey(blank=True, help_text='Vincular con una categoría de activo particular', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimiento_tipo', to='activos.categoria'),
        ),
    ]
