# Generated by Django 5.2.12 on 2026-05-13 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0079_alter_tipo_categoria_activo'),
        ('seguridad', '0016_add_conditional_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='requiere_permiso',
            field=models.BooleanField(default=False, help_text='Si se marca, se exigirá un permiso de trabajo vinculado', verbose_name='¿Requiere Permiso?'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo_permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asociadas', to='seguridad.tipopermiso', verbose_name='Tipo de Permiso Sugerido'),
        ),
    ]
