# Generated by Django 5.2.12 on 2026-06-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0080_ordentrabajo_requiere_permiso_and_more'),
        ('servicios', '0012_kpifragmento_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='kpis',
            field=models.ManyToManyField(blank=True, help_text='KPIs vinculados a esta categoría (se heredan a todas las rutinas hijas)', related_name='categorias_mantenimiento', to='servicios.kpi'),
        ),
    ]
