# Generated by Django 6.0.6 on 2026-07-01 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0082_ordentrabajo_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='acciones',
            field=models.TextField(blank=True, null=True, verbose_name='Acciones Realizadas'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_cerrados', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado Por'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AddField(
            model_name='fotoaviso',
            name='tipo',
            field=models.CharField(choices=[('APERTURA', 'Apertura'), ('CIERRE', 'Cierre')], default='APERTURA', max_length=10, verbose_name='Tipo'),
        ),
    ]
