# Generated by Django 6.0.6 on 2026-07-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0083_aviso_cierre_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contacto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
