# Generated by Django 6.0.6 on 2026-07-16 05:04

import mantenimiento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0084_empresa_contacto_empresa_email_empresa_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoempresa',
            name='archivo',
            field=models.FileField(help_text='Archivo físico a subir a MinIO', max_length=500, upload_to=mantenimiento.models.empresa_directory_path),
        ),
    ]
