# Generated by Django 6.0.6 on 2026-07-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0085_alter_documentoempresa_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicopuesto',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='tecnicopuesto',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de emergencia'),
        ),
    ]
