# Generated by Django 6.0.6 on 2026-07-21 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_nav_config_to_perfil'),
        ('mantenimiento', '0086_tecnicopuesto_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicopuesto',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_tecnico', to='core.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='tecnicopuesto',
            name='jefe_inmediato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='mantenimiento.tecnicopuesto', verbose_name='Jefe Inmediato'),
        ),
    ]
