# Generated by Django 6.0.6 on 2026-07-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0087_add_departamento_jefe_inmediato_to_tecnicopuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicopuesto',
            name='puesto_en_empresa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Puesto en la empresa'),
        ),
    ]
