# Generated by Django 6.0.6 on 2026-07-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0088_tecnicopuesto_puesto_en_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicopuesto',
            name='ultima_verificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última verificación'),
        ),
    ]
