# Generated by Django 6.0.6 on 2026-07-28 06:59

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0089_tecnicopuesto_ultima_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
