# Generated by Django 6.0.6 on 2026-08-04 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_puesto_trabajo_to_perfil'),
        ('mantenimiento', '0090_add_embedding_ordentrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='puestotrabajo',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos_trabajo', to='core.departamento', verbose_name='Departamento'),
        ),
    ]
