# Generated by Django 6.0.6 on 2026-09-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0091_add_departamento_to_puestotrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='domicilio',
            field=models.TextField(blank=True, null=True, verbose_name='Domicilio del Proveedor'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_proveedor',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='No. de Proveedor'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rtn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='R.T.N.'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre del Proveedor'),
        ),
    ]
