# Generated by Django 5.2.7 on 2026-01-15 17:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0035_activo_plano'),
        ('inventarios', '0007_material_marca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TipoIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion_trabajo', models.TextField(verbose_name='Descripción del Trabajo')),
                ('firmado', models.BooleanField(default=False)),
                ('ejecutantes', models.ManyToManyField(related_name='asts_participante', to=settings.AUTH_USER_MODEL)),
                ('lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asts_lider', to=settings.AUTH_USER_MODEL, verbose_name='Líder del Trabajo')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionEPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(blank=True, default='Entrega Inicial', max_length=100)),
                ('fecha_proxima_entrega', models.DateField(blank=True, help_text='Fecha sugerida para renovación', null=True)),
                ('entregado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epps_entregados', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(help_text='Debe ser un material de categoría EPP', on_delete=django.db.models.deletion.CASCADE, to='inventarios.material')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('resultado_global', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CON_HALLAZGOS', 'Con Hallazgos')], default='APROBADO', max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.activo')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.ubicacion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.tipoinspeccion')),
            ],
        ),
        migrations.CreateModel(
            name='PasoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='seguridad.analisisriesgo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CUMPLE', 'Cumple'), ('NO_CUMPLE', 'No Cumple'), ('NO_APLICA', 'No Aplica')], default='CUMPLE', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='inspecciones/')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='seguridad.inspeccion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.iteminspeccion')),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Peligro/Riesgo')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='seguridad.pasotrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Medida de Control')),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='seguridad.riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_ocurrencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('ubicacion_texto', models.CharField(blank=True, help_text='Descripción manual si no hay ubicación registrada', max_length=200)),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='BAJA', max_length=20)),
                ('estado', models.CharField(choices=[('REPORTADO', 'Reportado'), ('EN_PROCESO', 'En Proceso'), ('CERRADO', 'Cerrado')], default='REPORTADO', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='incidentes/')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.ubicacion')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.tipoincidente')),
            ],
        ),
        migrations.AddField(
            model_name='iteminspeccion',
            name='tipo_inspeccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seguridad.tipoinspeccion'),
        ),
        migrations.CreateModel(
            name='RequisitoPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('es_critico', models.BooleanField(default=False, help_text='Si es crítico, no se puede proceder sin este requisito')),
                ('tipo_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='seguridad.tipopermiso')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_trabajo', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('CERRADO', 'Cerrado/Finalizado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('ast_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.analisisriesgo', verbose_name='AST Vinculado')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.ubicacion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.tipopermiso')),
            ],
        ),
        migrations.CreateModel(
            name='VerificacionRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumple', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones', to='seguridad.permisotrabajo')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.requisitopermiso')),
            ],
        ),
    ]
