# Generated by Django 5.2.7 on 2026-01-15 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0038_fotoaviso'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisotrabajo',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos', to='mantenimiento.ordentrabajo', verbose_name='Orden de Trabajo'),
        ),
    ]
