# Generated by Django 5.2.7 on 2026-01-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_permisotrabajo_orden_trabajo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitopermiso',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='requisitopermiso',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
