# Generated by Django 5.2.12 on 2026-04-20 22:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0068_reportegenerado_task_id_alter_reportegenerado_estado'),
        ('seguridad', '0003_alter_requisitopermiso_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Objeto de Catálogo',
                'verbose_name_plural': 'Catálogo de Objetos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='verificacionrequisito',
            name='cumple',
        ),
        migrations.RemoveField(
            model_name='verificacionrequisito',
            name='observacion',
        ),
        migrations.CreateModel(
            name='LevantamientoConfiscacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('folio', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Levantamiento de Objetos',
                'verbose_name_plural': 'Levantamientos de Objetos',
            },
        ),
        migrations.CreateModel(
            name='ObjetoConfiscado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100, unique=True, verbose_name='Código de Barras/Etiqueta')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ALMACENADO', 'Almacenado'), ('RETIRADO', 'Retirado'), ('DEVUELTO', 'Devuelto/Regularizado')], default='ALMACENADO', max_length=20)),
                ('fecha_confiscacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_retiro', models.DateTimeField(blank=True, null=True)),
                ('catalogo_objeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.objetocatalogo', verbose_name='Tipo de Objeto')),
                ('levantamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='seguridad.levantamientoconfiscacion')),
            ],
            options={
                'verbose_name': 'Objeto Confiscado',
                'verbose_name_plural': 'Objetos Confiscados',
            },
        ),
        migrations.CreateModel(
            name='FotoObjetoConfiscado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='confiscaciones/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='seguridad.objetoconfiscado')),
            ],
            options={
                'verbose_name': 'Foto de Objeto',
                'verbose_name_plural': 'Fotos de Objetos',
            },
        ),
    ]
