# Generated by Django 5.2.12 on 2026-04-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_objetocatalogo_remove_verificacionrequisito_cumple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='levantamientoconfiscacion',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AddField(
            model_name='levantamientoconfiscacion',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='¿Finalizado?'),
        ),
    ]
