# Generated by Django 5.2.12 on 2026-04-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_levantamientoconfiscacion_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoconfiscado',
            name='status',
            field=models.CharField(choices=[('LEVANTADO', 'Registrado/Levantado'), ('TRANSITO', 'En Tránsito/Movilizando'), ('ALMACENADO', 'Almacenado en Bodega'), ('RETIRADO', 'Retirado por Tercero'), ('DEVUELTO', 'Devuelto/Regularizado')], default='LEVANTADO', max_length=20),
        ),
    ]
