# Generated by Django 5.2.12 on 2026-04-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_alter_objetoconfiscado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetoconfiscado',
            name='comentario_almacen',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario de Almacén/Discrepancia'),
        ),
        migrations.AddField(
            model_name='objetoconfiscado',
            name='ubicacion_almacen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación en Bodega'),
        ),
    ]
