# Generated by Django 5.2.12 on 2026-04-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_objetoconfiscado_comentario_almacen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoobjetoconfiscado',
            name='etapa',
            field=models.CharField(choices=[('LEVANTE', 'Levantamiento'), ('ALMACEN', 'Recepción Almacén'), ('RETIRO', 'Retiro/Cierre')], default='LEVANTE', max_length=20),
        ),
    ]
