# Generated by Django 5.2.12 on 2026-04-20 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0008_fotoobjetoconfiscado_etapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaConfiscacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_retirante', models.CharField(max_length=200, verbose_name='Nombre de quien recibe')),
                ('dni_retirante', models.CharField(blank=True, max_length=50, null=True, verbose_name='DNI/Identidad')),
                ('foto_identidad', models.ImageField(blank=True, null=True, upload_to='confiscaciones/entregas/id/')),
                ('foto_entrega', models.ImageField(blank=True, null=True, upload_to='confiscaciones/entregas/evidencia/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('entregado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega de Confiscación',
                'verbose_name_plural': 'Entregas de Confiscación',
            },
        ),
        migrations.AddField(
            model_name='objetoconfiscado',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_entregados', to='seguridad.entregaconfiscacion'),
        ),
    ]
