# Generated by Django 5.2.12 on 2026-04-27 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0009_entregaconfiscacion_objetoconfiscado_entrega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificacionrequisito',
            options={'verbose_name': 'Verificación de Requisito', 'verbose_name_plural': 'Verificaciones de Requisitos'},
        ),
        migrations.AddField(
            model_name='requisitopermiso',
            name='rango_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitopermiso',
            name='rango_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitopermiso',
            name='tipo_respuesta',
            field=models.CharField(choices=[('INSTRUCCION', 'Instrucción (Solo lectura)'), ('CHECK', 'Check (Si/No/NA)'), ('NUMERICO', 'Valor Numérico'), ('TEXTO', 'Texto Libre'), ('FOTO', 'Registro Fotográfico'), ('HEADER', 'ENCABEZADO / GRUPO')], default='CHECK', max_length=20),
        ),
        migrations.AddField(
            model_name='requisitopermiso',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Ej: ppm, %, LEL', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requisitopermiso',
            name='valor_objetivo',
            field=models.FloatField(blank=True, help_text='Valor ideal esperado', null=True),
        ),
        migrations.AddField(
            model_name='requisitopermiso',
            name='verificacion',
            field=models.CharField(blank=True, help_text='¿Qué debe verificar el solicitante/autorizador?', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verificacionrequisito',
            name='capturado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificacionrequisito',
            name='comentarios',
            field=models.TextField(blank=True, help_text='Observaciones adicionales', null=True),
        ),
        migrations.AddField(
            model_name='verificacionrequisito',
            name='creado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificacionrequisito',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='permisos/verificaciones/'),
        ),
        migrations.AddField(
            model_name='verificacionrequisito',
            name='no_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificacionrequisito',
            name='valor_bool',
            field=models.BooleanField(blank=True, help_text='Para tipos CHECK', null=True),
        ),
        migrations.AddField(
            model_name='verificacionrequisito',
            name='valor_numerico',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificacionrequisito',
            name='valor_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='verificacionrequisito',
            unique_together={('permiso', 'requisito')},
        ),
    ]
