# Generated by Django 5.2.12 on 2026-04-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0010_alter_verificacionrequisito_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacionrequisito',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
