# Generated by Django 5.2.12 on 2026-04-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0011_alter_verificacionrequisito_creado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoconfiscado',
            name='status',
            field=models.CharField(choices=[('IDENTIFICADO', 'Identificado'), ('TRANSITO', 'En Tránsito/Movilizando'), ('ALMACENADO', 'Almacenado en Bodega'), ('RETIRADO', 'Retirado por Tercero'), ('DEVUELTO', 'Devuelto/Regularizado')], default='IDENTIFICADO', max_length=20),
        ),
    ]
