# Generated by Django 5.2.12 on 2026-04-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0012_alter_objetoconfiscado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetoconfiscado',
            name='ubicacion_especifica',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación Específica'),
        ),
    ]
