# Generated by Django 5.2.12 on 2026-05-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0013_objetoconfiscado_ubicacion_especifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitopermiso',
            name='tabla_relacionada',
            field=models.CharField(blank=True, choices=[('auth.User', 'Usuarios del Sistema'), ('activos.Activo', 'Activos / Equipos'), ('activos.Ubicacion', 'Ubicaciones (Áreas/Edificios)')], help_text='Modelo relacionado si el tipo es TABLA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requisitopermiso',
            name='tipo_respuesta',
            field=models.CharField(choices=[('INSTRUCCION', 'Instrucción (Solo lectura)'), ('CHECK', 'Check (Si/No/NA)'), ('NUMERICO', 'Valor Numérico'), ('TEXTO', 'Texto Libre'), ('FOTO', 'Registro Fotográfico'), ('FECHAHORA', 'Fecha y Hora'), ('TABLA', 'Tabla Relacionada'), ('HEADER', 'ENCABEZADO / GRUPO')], default='CHECK', max_length=20),
        ),
    ]
