# Generated by Django 5.2.12 on 2026-05-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0014_requisitopermiso_tabla_relacionada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitopermiso',
            name='tabla_relacionada',
            field=models.CharField(blank=True, help_text='Modelo relacionado si el tipo es TABLA (ej: auth.User, activos.Activo)', max_length=100, null=True),
        ),
    ]
