# Generated by Django 5.2.12 on 2026-05-05 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0015_remove_tabla_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitopermiso',
            name='depende_condicion',
            field=models.CharField(blank=True, choices=[('TRUE', 'Si es Verdadero / Marcado'), ('FALSE', 'Si es Falso / No marcado'), ('FILLED', 'Si tiene algún valor'), ('EMPTY', 'Si está vacío')], help_text='Condición sobre el requisito padre para mostrar este', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requisitopermiso',
            name='depende_de',
            field=models.ForeignKey(blank=True, help_text='Si se define, este requisito solo se muestra si la condición del requisito padre se cumple', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependientes', to='seguridad.requisitopermiso'),
        ),
    ]
