# Generated by Django 5.2.12 on 2026-05-13 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0080_ordentrabajo_requiere_permiso_and_more'),
        ('seguridad', '0016_add_conditional_logic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaControlCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('ELIMINACION', 'Eliminación'), ('SUSTITUCION', 'Sustitución'), ('INGENIERIA', 'Control de Ingeniería'), ('ADMINISTRATIVO', 'Control Administrativo'), ('EPP', 'Equipo de Protección Personal')], default='ADMINISTRATIVO', max_length=50)),
            ],
            options={
                'verbose_name': 'Control de Catálogo',
                'verbose_name_plural': 'Catálogo de Controles',
            },
        ),
        migrations.CreateModel(
            name='PeligroCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('FISICO', 'Físico'), ('QUIMICO', 'Químico'), ('BIOLOGICO', 'Biológico'), ('ERGONOMICO', 'Ergonómico'), ('PSICOSOCIAL', 'Psicosocial'), ('MECANICO', 'Mecánico'), ('ELECTRICO', 'Eléctrico'), ('LOCATIVO', 'Locativo')], default='FISICO', max_length=50)),
            ],
            options={
                'verbose_name': 'Peligro de Catálogo',
                'verbose_name_plural': 'Catálogo de Peligros',
            },
        ),
        migrations.AddField(
            model_name='analisisriesgo',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asts', to='mantenimiento.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='control',
            name='verificado',
            field=models.BooleanField(default=False, verbose_name='¿Control Implementado?'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='consecuencia',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='probabilidad',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='control',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Medida de Control (Manual)'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Peligro/Riesgo (Manual)'),
        ),
        migrations.AddField(
            model_name='control',
            name='control_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.medidacontrolcatalogo'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='peligro_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.peligrocatalogo'),
        ),
    ]
