# Generated by Django 5.2.12 on 2026-05-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0017_medidacontrolcatalogo_peligrocatalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidacontrolcatalogo',
            name='peligros_asociados',
            field=models.ManyToManyField(blank=True, related_name='controles_recomendados', to='seguridad.peligrocatalogo'),
        ),
    ]
