# Generated by Django 5.2.12 on 2026-05-14 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0080_ordentrabajo_requiere_permiso_and_more'),
        ('seguridad', '0018_medidacontrolcatalogo_peligros_asociados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisisriesgo',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, limit_choices_to={'requiere_permiso': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asts', to='mantenimiento.ordentrabajo'),
        ),
    ]
