"""
Django settings for energia project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# IMPORTANTE! En produccion, esta clave DEBE obtenerse de una variable de entorno.
# No la dejes codificada aqui.
SECRET_KEY = 'django-insecure-t5a&grl!cy%k)x6=r8i9b$^g3w5q&schghtp1-001#3+j8o7aj'

# SECURITY WARNING: don't run with debug turned on in production!
# IMPORTANTE! En produccion, DEBUG debe ser False por seguridad.
# Por defecto False para seguridad. Solo True si se especifica explícitamente.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

# Detección de entorno: Si hay COOLIFY_FQDN, definitivamente NO es local.
IS_LOCAL = DEBUG and not os.environ.get('COOLIFY_FQDN')


# ALLOWED_HOSTS
_env_hosts = os.environ.get('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [h.strip() for h in _env_hosts.split(',') if h.strip()]

# Automatizacion para Coolify: agregar dominios detectados dinamicamente
coolify_fqdn = os.environ.get('COOLIFY_FQDN')
if coolify_fqdn:
    if coolify_fqdn not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(coolify_fqdn)

if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['*']

# Diagnostico en el log
print(f"[DEBUG] ALLOWED_HOSTS final: {ALLOWED_HOSTS}")

# URL base para el sitio
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')

# Configuracion CSRF para produccion
_csrf_env = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_env.split(',') if origin.strip()]

# Agregar tambien el FQDN de Coolify a la confianza de CSRF
if coolify_fqdn and not any(coolify_fqdn in o for o in CSRF_TRUSTED_ORIGINS):
    CSRF_TRUSTED_ORIGINS.append(f"http://{coolify_fqdn}")
    CSRF_TRUSTED_ORIGINS.append(f"https://{coolify_fqdn}")

# Dominios adicionales explícitos
extra_hosts = ['softcom.ccg.hn', '10.30.1.11']
for host in extra_hosts:
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# CSRF Trusted Origins adicionales
extra_origins = [
    'https://softcom.ccg.hn', 
    'http://softcom.ccg.hn',
    'https://*.ccg.hn',
    'http://10.30.1.11'
]
for origin in extra_origins:
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

print(f"[DEBUG] CSRF_TRUSTED_ORIGINS final: {CSRF_TRUSTED_ORIGINS}")

# Configuracion para Proxy Inverso (Coolify/Nginx/Traefik)
# Confía en la cabecera X-Forwarded-Proto para determinar si la conexión es segura
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Mayan EDMS Configuration
MAYAN_EDMS_URL = 'http://181.115.47.107:8090'
MAYAN_EDMS_API_URL = f'{MAYAN_EDMS_URL}/api/v4/'
# Credenciales actualizadas por el usuario para Coolify
MAYAN_EDMS_USERNAME = os.environ.get('MAYAN_USERNAME', 'admin')
MAYAN_EDMS_TOKEN = os.environ.get('MAYAN_API_TOKEN', '')
MAYAN_EDMS_PASSWORD = os.environ.get('MAYAN_PASSWORD', '3vPW7RPyUk')

# n8n Automation Configuration
# n8n Automation Configuration
# Webhook para notificar nuevo documento
N8N_WEBHOOK_URL = os.environ.get('N8N_WEBHOOK_URL', 'http://181.115.47.107:5678/webhook/nuevo-documento')

# Webhook para el Chat con IA (Documentos)
# Por defecto usa la IP pública, pero permite override para usar la red interna (ej: http://n8n:5678/webhook/...)
N8N_CHAT_WEBHOOK_URL = os.environ.get('N8N_CHAT_WEBHOOK_URL', 'http://181.115.47.107:5678/webhook/chat-documento')

# Configuracion de subida de archivos
# Aumentar limites para evitar errores en subidas grandes (Proxy Error / Request Too Large)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB (Default 2.5 MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 MB



INSTALLED_APPS = [
    'storages',
    'core',  # Mover al inicio para que sus templates (overrides) tengan prioridad
    'documentos', # Nueva gestión documental
    'comunicaciones', # Nuevo sistema de mail/transmittals
    'proyectos', # Gestión de proyectos y actividades
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # Siempre debe estar
    'import_export',
    'django_celery_results',  # Para almacenar resultados de tareas Celery
    'colorfield',
    'activos',
    'mantenimiento',
    'presupuestos.apps.PresupuestosConfig',
    'inventarios',
    'auditorias',
    'almacen',
    'seguridad',
    'django.contrib.humanize',
    'callcenter',
    'corsheaders',
    'servicios',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'energia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'core' / 'templates'], # Ruta relativa a BASE_DIR
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.ui_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'energia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import dj_database_url

# En producción (Coolify), usa DATABASE_URL de variables de entorno
# En desarrollo local, usa la configuración hardcodeada
if os.environ.get('DATABASE_URL'):
    # Producción: Coolify proporciona DATABASE_URL automáticamente
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Desarrollo local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'db',
            'USER': 'postgres',
            'PASSWORD': 'PasswordRoot07',
            'HOST': '181.115.47.107',
            'PORT': '5432',
            'CONN_MAX_AGE': 600,
            'CONN_HEALTH_CHECKS': True,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-hn' # Cambiado a español de Honduras, o el que prefieras
TIME_ZONE = 'America/Tegucigalpa' # Cambiado a la zona horaria de Honduras

USE_I18N = True # Habilita la internacionalización

USE_TZ = True # Habilita zonas horarias para los modelos (recomendado)

# Configuración regional para Honduras (Lempiras, Punto para decimales)
DECIMAL_SEPARATOR = '.'
THOUSAND_SEPARATOR = ','
USE_THOUSAND_SEPARATOR = True
NUMBER_GROUPING = 3


# --- Static files (CSS, JavaScript, Images) ---
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# La URL para servir los archivos estáticos en el navegador.
STATIC_URL = '/static/'

# El directorio donde `collectstatic` recolectará *todos* los archivos estáticos
# de tus aplicaciones y de STATICFILES_DIRS. Este es el directorio que tu servidor web
# (como Nginx o el que Coolify use) debe servir directamente.
# Es crucial que este directorio sea accesible por tu servidor web.
STATIC_ROOT = BASE_DIR / 'staticfiles' # Un directorio llamado 'staticfiles' en la raíz de tu proyecto


# Dónde Django debe buscar *archivos estáticos adicionales* (no de una app específica).
# Esto incluye tu carpeta 'static' global en la raíz del proyecto.
STATICFILES_DIRS = []
_static_global = BASE_DIR / 'static'
if _static_global.exists():
    STATICFILES_DIRS.append(_static_global)

_static_core = BASE_DIR / 'core' / 'static'
if _static_core.exists():
    STATICFILES_DIRS.append(_static_core)


# --- Media files (User-uploaded files) ---
# La URL para servir los archivos subidos por los usuarios en el navegador.
MEDIA_URL = '/media/'

# El directorio donde se guardarán físicamente los archivos subidos por los usuarios.
# Asegúrate de que este directorio tenga permisos de escritura para tu aplicación.
MEDIA_ROOT = BASE_DIR / 'media'

# --- MinIO / S3 Storage Configuration ---
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', 'rootminio')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', 'PasswordRoot07')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'energia-media')

# Configuración de comunicación interna vs pública
if IS_LOCAL:
    # EN DESARROLLO: Usamos la IP directa (Sin Custom Domain para evitar errores)
    MEDIA_URL = f'http://181.115.47.107:9000/{AWS_STORAGE_BUCKET_NAME}/'
    AWS_S3_ENDPOINT_URL = 'http://181.115.47.107:9000'
    AWS_S3_CUSTOM_DOMAIN = None 
    AWS_S3_URL_PROTOCOL = 'http:' # Importante el :
    AWS_S3_USE_SSL = False
    AWS_QUERYSTRING_AUTH = True
else:
    # EN PRODUCCIÓN: Proxy de Django para evitar Mixed Content
    MEDIA_URL = '/media-proxy/'
    # CUSTOM_DOMAIN se usa para generar URLs públicas. 
    # Apuntamos al proxy de Django para evitar problemas de SSL/CORS.
    AWS_S3_CUSTOM_DOMAIN = 'softcom.ccg.hn/media-proxy'
    AWS_S3_URL_PROTOCOL = 'https:' 
    # Usamos el nombre del servicio interno de Coolify (minio) para UPLOADS
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', 'http://minio:9000')
    AWS_S3_USE_SSL = False
    AWS_QUERYSTRING_AUTH = False

# Configuración general de S3/MinIO
AWS_S3_VERIFY = False 
AWS_S3_REGION_NAME = 'us-east-1'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_FILE_OVERWRITE = False
AWS_S3_ADDRESSING_STYLE = 'path' # Crítico para compatibilidad con MinIO
AWS_S3_SECURE_URLS = not IS_LOCAL # Generar https:// en producción

# Configuración de Import-Export
# 'utf-8-sig' es más robusto para archivos CSV generados por Excel con BOM
IMPORT_EXPORT_ENCODING = 'utf-8-sig'

# Configuración de Storage
# SIEMPRE usar MinIO/S3 para archivos de media (imágenes de modelos, fotos de activos, etc.)
# Esto asegura que las imágenes estén centralizadas y accesibles desde cualquier entorno
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración para aumentar el límite de campos y tamaño en solicitudes POST
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB

# Configuración de Logging (ejemplo básico, puedes expandir según necesites)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

JAZZMIN_SETTINGS = {
    "site_title": "SoftCom-CCG Admin",
    "site_header": "SoftCom-CCG",
    "site_brand": "SoftCom-CCG",
    "welcome_sign": "Bienvenido al panel de administración",
    "copyright": "SoftCom-CCG Ltd",
    "search_model": ["auth.User"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "📦 Dashboard Requisiciones", "url": "/presupuestos/requisiciones/dashboard/", "permissions": ["presupuestos.view_requisicion"]},
        {"model": "auth.User"},
        {"name": "Asistente AI", "url": "/admin/chatbot_trigger/", "new_window": False},
        {"name": "🔄 Sincronizar SIG", "url": "/admin/callcenter/solicitudticket/sync-tickets/", "permissions": ["callcenter.view_solicitudticket"]},
    ],
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "presupuestos": "fas fa-file-invoice-dollar",
        "presupuestos.presupuesto": "fas fa-file-invoice-dollar",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": "core/css/admin_custom.css",
    # "custom_js": "core/js/onboarding.js",
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-navy",
    "accent": "accent-primary",
    "navbar": "navbar-navy navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_collapse": False,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Habilitar iframes para popups y modales en el admin
X_FRAME_OPTIONS = 'SAMEORIGIN'

# ===== CELERY CONFIGURATION =====
# Detección automática de entorno

# Celery Broker URL Configuration
if IS_LOCAL:
    # Desarrollo local: Redis en Docker local
    CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
    print(f"[DEBUG] Entorno LOCAL detectado. Redis: {CELERY_BROKER_URL}")
else:
    # Producción: Redis interno de Coolify (usa nombre del servicio)
    CELERY_BROKER_URL = os.environ.get(
        'CELERY_BROKER_URL', 
        'redis://default:saul123@redis:6379/0'  # Nombre del servicio en Coolify
    )
    print(f"[DEBUG] Entorno PRODUCCION detectado. Redis: {CELERY_BROKER_URL}")

import sys
sys.stdout.flush()

CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'django-db')
CELERY_CACHE_BACKEND = 'django-cache'

# Celery Task Settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos máximo por tarea
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# TIMEOUTS AGRESIVOS para evitar hangs al enviar tareas
CELERY_BROKER_CONNECTION_TIMEOUT = 3  # Solo 3 segundos para conectar
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'socket_timeout': 3,
    'socket_connect_timeout': 3,
    'socket_keepalive': True,
}

# Caché compartida para que Celery y Django (runserver) se vean
# En ambos entornos usamos Redis si está disponible
if IS_LOCAL:
    # Local: Intentar usar el mismo Redis que Celery si está configurado
    try:
        import redis
        # Usar la URL del broker configurada (que viene de env o default)
        redis_url = CELERY_BROKER_URL
        
        # Test connection
        r = redis.from_url(redis_url, socket_connect_timeout=1)
        r.ping()
        # Si llega aquí, Redis está disponible
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': redis_url,
                'OPTIONS': {
                    'socket_timeout': 5,
                    'socket_connect_timeout': 5,
                    'retry_on_timeout': True,
                }
            }
        }
        print(f"[DEBUG] Cache: Redis conectado exitosamente en {redis_url}")
    except Exception as e:
        # Redis no disponible, usar memoria local
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'unique-snowflake',
            }
        }
        print(f"[DEBUG] Cache: LocMem (Redis no disponible en {CELERY_BROKER_URL}: {e})")
else:
    # Producción: LocMem por ahora para evitar crashes
    # Producción: Redis compartido
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': CELERY_BROKER_URL,
            'OPTIONS': {
                'socket_timeout': 5,
                'socket_connect_timeout': 5,
                'retry_on_timeout': True,
            }
        }
    }
    print(f"[DEBUG] Cache: Redis Produccion ({CELERY_BROKER_URL})")

sys.stdout.flush()

# Configuración adicional para producción
if not DEBUG:
    # En producción, usar configuración más robusta
    CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
    CELERY_BROKER_CONNECTION_RETRY = True
    CELERY_BROKER_CONNECTION_MAX_RETRIES = 10

# Configuración de Email para Desarrollo
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'notificaciones@energia.com'

# Configuración de autenticación
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/app/'
