"""
Django settings for energia project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# IMPORTANTE! En produccion, esta clave DEBE obtenerse de una variable de entorno.
# No la dejes codificada aqui.
SECRET_KEY = 'django-insecure-t5a&grl!cy%k)x6=r8i9b$^g3w5q&schghtp1-001#3+j8o7aj'

# SECURITY WARNING: don't run with debug turned on in production!
# IMPORTANTE! En produccion, DEBUG debe ser False por seguridad.
# Por defecto False para seguridad. Solo True si se especifica explícitamente.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

# Detección de entorno: Si hay COOLIFY_FQDN, definitivamente NO es local.
IS_LOCAL = DEBUG and not os.environ.get('COOLIFY_FQDN')


# ALLOWED_HOSTS
_env_hosts = os.environ.get('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [h.strip() for h in _env_hosts.split(',') if h.strip()]

# Automatizacion para Coolify: agregar dominios detectados dinamicamente
coolify_fqdn = os.environ.get('COOLIFY_FQDN')
if coolify_fqdn:
    if coolify_fqdn not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(coolify_fqdn)

if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['*']

# Diagnostico en el log
print(f"[DEBUG] ALLOWED_HOSTS final: {ALLOWED_HOSTS} ")

# URL base para el sitio
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')

# Configuracion CSRF para produccion
_csrf_env = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_env.split(',') if origin.strip()]

# Agregar tambien el FQDN de Coolify a la confianza de CSRF
if coolify_fqdn and not any(coolify_fqdn in o for o in CSRF_TRUSTED_ORIGINS):
    CSRF_TRUSTED_ORIGINS.append(f"http://{coolify_fqdn}")
    CSRF_TRUSTED_ORIGINS.append(f"https://{coolify_fqdn}")

# Dominios adicionales explícitos
extra_hosts = ['softcom.ccg.hn', '10.30.1.11']
for host in extra_hosts:
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# CSRF Trusted Origins adicionales
extra_origins = [
    'https://softcom.ccg.hn', 
    'http://softcom.ccg.hn',
    'https://*.ccg.hn',
    'http://10.30.1.11',
    'http://127.0.0.1:8000'
]
for origin in extra_origins:
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

print(f"[DEBUG] CSRF_TRUSTED_ORIGINS final: {CSRF_TRUSTED_ORIGINS}")

# Configuracion para Proxy Inverso (Coolify/Nginx/Traefik)
# Confía en la cabecera X-Forwarded-Proto para determinar si la conexión es segura
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# n8n Automation Configuration
if IS_LOCAL:
     # En local usamos la IP pública directa para mayor estabilidad
     N8N_BASE_URL = 'http://localhost:5678'
     N8N_WEBHOOK_ENV = '/webhook-test/' # Para desarrollo/pruebas
else:
     # URL interna para comunicación entre contenedores en Coolify
     N8N_BASE_URL = os.environ.get('N8N_INTERNAL_URL', 'http://n8n-z8wscww488scgs84oo4os008:5678')
     N8N_WEBHOOK_ENV = '/webhook/' # Producción (requiere workflow Activo)

# --- Webhooks Específicos ---

# Extracción y Procesamiento de Documentos
N8N_PROCESS_DOCUMENT_WEBHOOK_URL = os.environ.get(
    'N8N_PROCESS_DOCUMENT_WEBHOOK_URL', 
    f'{N8N_BASE_URL}{N8N_WEBHOOK_ENV}process-document'
)
N8N_EXTRACT_TEXTO_WEBHOOK_URL = N8N_PROCESS_DOCUMENT_WEBHOOK_URL

# URL para avisos
URL_AVISOS = os.environ.get(
    'URL_AVISOS',
     f'{N8N_BASE_URL}{N8N_WEBHOOK_ENV}avisos-asignacion'
)
N8N_AVISOS_WEBHOOK_URL = URL_AVISOS


# Metadatos y Chat
N8N_CHAT_WEBHOOK_URL = os.environ.get('N8N_CHAT_WEBHOOK_URL', f'{N8N_BASE_URL}{N8N_WEBHOOK_ENV}chat-documento')
N8N_METADATA_SYNC_WEBHOOK = os.environ.get('N8N_METADATA_SYNC_WEBHOOK', f'{N8N_BASE_URL}{N8N_WEBHOOK_ENV}sync-metadatos-doc')

# Tickets (Callcenter)
N8N_TICKET_VECTORIZER_URL = os.environ.get('N8N_TICKET_VECTORIZER_URL', f'{N8N_BASE_URL}{N8N_WEBHOOK_ENV}vectorize-ticket')
N8N_TICKET_NOTIFY_URL = os.environ.get('N8N_TICKET_NOTIFY_URL', f'{N8N_BASE_URL}{N8N_WEBHOOK_ENV}ticket-notification')

# Materiales e Inventarios
N8N_SOLICITUD_WEBHOOK_URL = os.environ.get('N8N_SOLICITUD_WEBHOOK_URL', f'{N8N_BASE_URL}{N8N_WEBHOOK_ENV}solicitud-material')

# --- URL del Sitio para Callbacks ---
if os.environ.get('COOLIFY_FQDN'):
    SITE_URL = f"https://{os.environ.get('COOLIFY_FQDN')}"
    INTERNAL_SITE_URL = os.environ.get('INTERNAL_SITE_URL', 'http://kgogwsw00cwcw8g0wk0gsogg:8000')
else:
    SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')
    if IS_LOCAL:
        # Callback para n8n remoto (vía túnel reverso si aplica)
        INTERNAL_SITE_URL = os.environ.get('INTERNAL_SITE_URL', 'http://181.115.47.107:8000')
    else:
        INTERNAL_SITE_URL = SITE_URL


# --- AI & Embeddings Configuration ---
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
# Si no hay key de Gemini, loguear advertencia pero no detener el sistema
if not GEMINI_API_KEY:
    print("[WARNING] GEMINI_API_KEY no encontrada. La búsqueda semántica no funcionará.")


# Configuracion de subida de archivos
# Aumentar limites para evitar errores en subidas grandes (Proxy Error / Request Too Large)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB (Default 2.5 MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 MB



INSTALLED_APPS = [
    'storages',
    'core',  # Mover al inicio para que sus templates (overrides) tengan prioridad
    'callcenter',
    'documentos', # Nueva gestión documental
    'plantillas', # Sistema de plantillas Word
    'comunicaciones', # Nuevo sistema de mail/transmittals
    'proyectos', # Gestión de proyectos y actividades
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # Siempre debe estar
    'import_export',
    'django_celery_results',  # Para almacenar resultados de tareas Celery
    'colorfield',
    'activos',
    'mantenimiento',
    'presupuestos.apps.PresupuestosConfig',
    'inventarios',
    'auditorias',
    'almacen',
    'seguridad',
    'django.contrib.humanize',
    'corsheaders',
    'servicios',
    'ayuda.apps.AyudaConfig',
    'iot',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'energia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'core' / 'templates'], # Ruta relativa a BASE_DIR
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.ui_config',
                'ayuda.context_processors.help_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'energia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import dj_database_url

# En producción (Coolify), usa DATABASE_URL de variables de entorno
# En desarrollo local, usa la configuración hardcodeada apuntando al servidor Coolify
db_url = os.environ.get('DATABASE_URL')
if db_url:
    # Producción: Coolify proporciona DATABASE_URL automáticamente
    DATABASES = {
        'default': dj_database_url.config(
            default=db_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
    
    # Configuraciones de red AGRESIVAS para evitar OperationalError en Docker/Coolify
    if 'OPTIONS' not in DATABASES['default']:
        DATABASES['default']['OPTIONS'] = {}
    
    db_host = DATABASES['default'].get('HOST', '')
    
    # ALERTA CRITICA: Si en producción detectamos localhost o 127.0.0.1 en el host de la DB
    if not IS_LOCAL and db_host in ['localhost', '127.0.0.1', '']:
        print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
        print(f"[ERROR CRITICO] DB HOST DETECTADO COMO '{db_host}' EN PRODUCCION")
        print("Esto PROBABLEMENTE causará timeouts en el worker.")
        print("Asegúrate de que DATABASE_URL use el nombre del servicio de la DB.")
        print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")

    DATABASES['default']['OPTIONS'].update({
        'sslmode': 'disable',
        'connect_timeout': 20,           # Aumentado a 20s para redes lentas
        'keepalives': 1,
        'keepalives_idle': 30,
        'keepalives_interval': 10,
        'keepalives_count': 5,
    })
    
    print(f"[DEBUG] DB Producción: {db_host} - Puerto: {DATABASES['default'].get('PORT')} - Timeout: 20s")
else:
    # Diagnóstico: Si no hay DATABASE_URL pero no es local, algo está mal configurado en Coolify
    if not IS_LOCAL:
        print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
        print("[CRITICAL] DATABASE_URL NO DETECTADA EN PRODUCCION")
        print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")

    # Desarrollo local - Conexión manual vía Túnel (dist/Softcom_DB_Tunnel.exe)
    LOCAL_DB_PORT = 5434
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'postgres',
            'USER': 'postgres',
            'PASSWORD': 'admin123',
            'HOST': '127.0.0.1',
            'PORT': str(LOCAL_DB_PORT),
            'OPTIONS': {
                'sslmode': 'disable',
                'connect_timeout': 10,
            },
            'CONN_MAX_AGE': 600,
            'CONN_HEALTH_CHECKS': True,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-hn' # Cambiado a español de Honduras
TIME_ZONE = 'America/Tegucigalpa' # Cambiado a la zona horaria de Honduras

USE_I18N = True # Habilita la internacionalización
USE_TZ = True # Habilita zonas horarias para los modelos (recomendado)

# Configuración regional para Honduras (Lempiras, Punto para decimales)
# En Django >= 5.0, USE_L10N siempre es True. Debemos usar FORMAT_MODULE_PATH.
FORMAT_MODULE_PATH = [
    'core.formats',
]

DECIMAL_SEPARATOR = '.'
THOUSAND_SEPARATOR = ','
USE_THOUSAND_SEPARATOR = True
NUMBER_GROUPING = 3


# --- Static files (CSS, JavaScript, Images) ---
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# La URL para servir los archivos estáticos en el navegador.
STATIC_URL = '/static/'

# El directorio donde `collectstatic` recolectará *todos* los archivos estáticos
# de tus aplicaciones y de STATICFILES_DIRS. Este es el directorio que tu servidor web
# (como Nginx o el que Coolify use) debe servir directamente.
# Es crucial que este directorio sea accesible por tu servidor web.
STATIC_ROOT = BASE_DIR / 'staticfiles' # Un directorio llamado 'staticfiles' en la raíz de tu proyecto


# Dónde Django debe buscar *archivos estáticos adicionales* (no de una app específica).
# Esto incluye tu carpeta 'static' global en la raíz del proyecto.
STATICFILES_DIRS = []
_static_global = BASE_DIR / 'static'
if _static_global.exists():
    STATICFILES_DIRS.append(_static_global)

_static_core = BASE_DIR / 'core' / 'static'
if _static_core.exists():
    STATICFILES_DIRS.append(_static_core)


# --- Media files (User-uploaded files) ---
# La URL para servir los archivos subidos por los usuarios en el navegador.
MEDIA_URL = '/media/'

# El directorio donde se guardarán físicamente los archivos subidos por los usuarios.
# Asegúrate de que este directorio tenga permisos de escritura para tu aplicación.
MEDIA_ROOT = BASE_DIR / 'media'

# --- MinIO / S3 Storage Configuration ---
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', 'rootminio')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', 'PasswordRoot07')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'energia-media')

# Configuración de comunicación interna vs pública
if IS_LOCAL:
    # EN DESARROLLO: Usamos localhost a través del túnel Softcom
    MEDIA_URL = f'http://localhost:9000/{AWS_STORAGE_BUCKET_NAME}/'
    AWS_S3_ENDPOINT_URL = 'http://localhost:9000'
    AWS_S3_CUSTOM_DOMAIN = None 
    AWS_S3_URL_PROTOCOL = 'http:'
    AWS_S3_USE_SSL = False
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 604800 # 1 semana de vida para el link en local
else:
    # EN PRODUCCIÓN: Proxy de Django para evitar Mixed Content
    MEDIA_URL = '/media-proxy/'
    # CUSTOM_DOMAIN se usa para generar URLs públicas. 
    # Apuntamos al proxy de Django para evitar problemas de SSL/CORS.
    AWS_S3_CUSTOM_DOMAIN = 'softcom.ccg.hn/media-proxy'
    AWS_S3_URL_PROTOCOL = 'https:' 
    # Usamos el nombre del servicio interno de Coolify (minio) para UPLOADS
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', 'http://minio-cksckkgkcoogow4o4kg0gsog:9000')
    AWS_S3_USE_SSL = False
    AWS_QUERYSTRING_AUTH = False

# Configuración general de S3/MinIO
AWS_S3_VERIFY = False 
AWS_S3_REGION_NAME = 'us-east-1'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_FILE_OVERWRITE = False
AWS_S3_ADDRESSING_STYLE = 'path' # Crítico para compatibilidad con MinIO
AWS_S3_SECURE_URLS = not IS_LOCAL # Generar https:// en producción

# Configuración de Import-Export
# 'utf-8-sig' es más robusto para archivos CSV generados por Excel con BOM
IMPORT_EXPORT_ENCODING = 'utf-8-sig'

# Configuración de Storage
# SIEMPRE usar MinIO/S3 para archivos de media (imágenes de modelos, fotos de activos, etc.)
# Esto asegura que las imágenes estén centralizadas y accesibles desde cualquier entorno
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Configuración de WhiteNoise para mayor robustez en producción
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_USE_FINDERS = True
WHITENOISE_KEEP_ONLY_HASHED_FILES = False


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración para aumentar el límite de campos y tamaño en solicitudes POST
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB

# Configuración de Logging (ejemplo básico, puedes expandir según necesites)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

JAZZMIN_SETTINGS = {
    "site_title": "SoftCom-CCG Admin",
    "site_header": "SoftCom-CCG",
    "site_brand": "SoftCom-CCG",
    "welcome_sign": "Bienvenido al panel de administración",
    "copyright": "SoftCom-CCG Ltd",
    "search_model": "auth.User",
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "🌟 Menu Principal", "url": "/portal/", "permissions": ["auth.view_user"]},
        {"name": "📦 Dashboard Requisiciones", "url": "/presupuestos/requisiciones/dashboard/", "permissions": ["presupuestos.view_requisicion"]},
        {"model": "auth.User"},
        {"name": "Asistente AI", "url": "/admin/chatbot_trigger/", "new_window": False},
        {"name": "🔄 Sincronizar SIG", "url": "/admin/callcenter/solicitudticket/sync-tickets/", "permissions": ["callcenter.view_solicitudticket"]},
        {"name": "📊 Dashboard Importaciones", "url": "/activos/import-dashboard/", "permissions": ["activos.view_registroimportacion"]},
        {"name": "🎫 Dashboard Tickets", "url": "/callcenter/dashboard/", "permissions": ["callcenter.view_solicitudticket"]},
        {"name": "❓ Ayuda", "url": "/ayuda/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "presupuestos": "fas fa-wallet",
        "presupuestos.PresupuestoAnual": "fas fa-calendar-check",
        "presupuestos.PartidaPresupuestaria": "fas fa-list-alt",
        "presupuestos.CambioPresupuesto": "fas fa-exchange-alt",
        "presupuestos.Compromiso": "fas fa-handshake",
        "presupuestos.DetalleCompromiso": "fas fa-info-circle",
        "presupuestos.GastoEjecutado": "fas fa-receipt",
        "presupuestos.ItemPresupuesto": "fas fa-tag",
        "presupuestos.DetallePeriodico": "fas fa-clock",
        "presupuestos.PresupuestoAgrupado": "fas fa-object-group",
        "presupuestos.Requisicion": "fas fa-file-signature",
        "presupuestos.ArticuloRequisicion": "fas fa-shopping-basket",
        "presupuestos.DocumentoRequisicion": "fas fa-file-pdf",
        "presupuestos.SolicitudPago": "fas fa-money-check-alt",
        "presupuestos.ItemSolicitudPago": "fas fa-money-bill-wave",
        "documentos": "fas fa-file-alt",
        "activos": "fas fa-building",
        "mantenimiento": "fas fa-tools",
        "mantenimiento.Categoria": "fas fa-tags",
        "mantenimiento.Frecuencia": "fas fa-sync-alt",
        "mantenimiento.PuestoTrabajo": "fas fa-briefcase",
        "mantenimiento.Empresa": "fas fa-building",
        "mantenimiento.TecnicoPuesto": "fas fa-user-cog",
        "mantenimiento.Procedimiento": "fas fa-book",
        "mantenimiento.PasoProcedimiento": "fas fa-list-ol",
        "mantenimiento.Rutina": "fas fa-calendar-alt",
        "mantenimiento.Horario": "fas fa-clock",
        "mantenimiento.DiaHorario": "fas fa-calendar-day",
        "mantenimiento.RestriccionCalendario": "fas fa-calendar-times",
        "mantenimiento.PlanificacionMensual": "fas fa-calendar-check",
        "mantenimiento.Programacion": "fas fa-tasks",
        "mantenimiento.Falla": "fas fa-exclamation-triangle",
        "mantenimiento.Aviso": "fas fa-bell",
        "mantenimiento.FotoAviso": "fas fa-camera",
        "mantenimiento.NotificacionMantenimiento": "fas fa-envelope",
        "mantenimiento.OrdenTrabajo": "fas fa-clipboard-list",
        "mantenimiento.CierreOrdenTrabajo": "fas fa-check-double",
        "mantenimiento.ValorPasoOrden": "fas fa-check-square",
        "inventarios": "fas fa-warehouse",
        "inventarios.SolicitudMaterial": "fas fa-shopping-cart",
        "inventarios.CategoriaMaterial": "fas fa-tags",
        "inventarios.Material": "fas fa-cubes",
        "inventarios.CompatibilidadMaterial": "fas fa-link",
        "inventarios.Lote": "fas fa-boxes",
        "inventarios.StockRecord": "fas fa-boxes",
        "inventarios.MovimientoInventario": "fas fa-exchange-alt",
        "callcenter": "fas fa-headset",
        "callcenter.SolicitudTicket": "fas fa-ticket-alt",
        "callcenter.GrupoTicket": "fas fa-layer-group",
        "proyectos": "fas fa-project-diagram",
        "seguridad": "fas fa-shield-alt",
        "seguridad.TipoIncidente": "fas fa-biohazard",
        "seguridad.Incidente": "fas fa-exclamation-circle",
        "seguridad.TipoInspeccion": "fas fa-clipboard-list",
        "seguridad.ItemInspeccion": "fas fa-list-ul",
        "seguridad.Inspeccion": "fas fa-search-plus",
        "seguridad.ResultadoInspeccion": "fas fa-check-double",
        "seguridad.AsignacionEPP": "fas fa-hard-hat",
        "seguridad.AnalisisRiesgo": "fas fa-file-contract",
        "seguridad.PasoTrabajo": "fas fa-shoe-prints",
        "seguridad.Riesgo": "fas fa-skull-crossbones",
        "seguridad.Control": "fas fa-user-shield",
        "seguridad.TipoPermiso": "fas fa-id-card",
        "seguridad.RequisitoPermiso": "fas fa-tasks",
        "seguridad.PermisoTrabajo": "fas fa-file-signature",
        "seguridad.VerificacionRequisito": "fas fa-check-square",
        "servicios": "fas fa-concierge-bell",
        "ayuda": "fas fa-question-circle",
        "ayuda.CategoriaAyuda": "fas fa-folder",
        "ayuda.ArticuloAyuda": "fas fa-file-alt",
        "core": "fas fa-bolt",
        "plantillas": "fas fa-file-word",
        "django_celery_results": "fas fa-clock",
        "iot": "fas fa-microchip",
        "iot.BACnetGateway": "fas fa-network-wired",
        "iot.BACnetDevice": "fas fa-server",
        "iot.BACnetPoint": "fas fa-broadcast-tower",
        "iot.Telemetry": "fas fa-chart-line",
    },
    "order_with_respect_to": [
        "core", "activos", "documentos", "proyectos", "mantenimiento", 
        "inventarios", "callcenter", "presupuestos", "seguridad",
        "iot",
        "auth", "servicios", "ayuda", "plantillas", "django_celery_results"
    ],
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": [],
    "hide_models": [],
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": "core/css/admin_custom.css",
    "custom_js": "core/js/admin_search.js",
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
    "custom_links": {
        "mantenimiento": [
            {
                "name": "📊 Dashboard Mantenimiento",
                "url": "/mantenimiento/",
                "icon": "fas fa-chart-line",
                "permissions": ["mantenimiento.view_ordentrabajo"],
            },
        ],
        "inventarios": [
            {
                "name": "📦 Dashboard Inventarios",
                "url": "/inventarios/",
                "icon": "fas fa-warehouse",
                "permissions": ["inventarios.view_material"],
            },
        ],
        "documentos": [
            {
                "name": "📁 Carga Masiva",
                "url": "/documentos/carga-masiva/",
                "icon": "fas fa-upload",
                "permissions": ["documentos.add_documento"],
            },
        ],
        "presupuestos": [
            {
                "name": "📊 Dashboard de Pagos",
                "url": "/presupuestos/pagos/dashboard/",
                "icon": "fas fa-chart-pie",
                "permissions": ["presupuestos.view_solicitudpago"],
            },
        ],
        "servicios": [
            {
                "name": "📊 Dashboard de KPIs",
                "url": "/admin/servicios/kpi/",
                "icon": "fas fa-chart-bar",
                "permissions": ["servicios.view_kpi"],
            },
        ],
        "iot": [
            {
                "name": "📊 Dashboard IoT BACnet",
                "url": "/iot/dashboard/",
                "icon": "fas fa-microchip",
                "permissions": ["iot.view_telemetry"],
            },
        ],
    },
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-white",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_collapse": False,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Habilitar iframes para popups y modales en el admin
X_FRAME_OPTIONS = 'SAMEORIGIN'

# ===== CELERY CONFIGURATION =====
# Detección automática de entorno

# Celery Broker URL Configuration
if IS_LOCAL:
    # FORZADO: Usar DB 1 para evitar que el worker de producción en Coolify (DB 0) robe las tareas
    CELERY_BROKER_URL = 'redis://default:saul123@localhost:6379/1'
    print(f"[DEBUG] Entorno LOCAL detectado. Redis (AISLADO DB 1): {CELERY_BROKER_URL}")
else:
    # Producción: Redis interno de Coolify (usa nombre del servicio)
    CELERY_BROKER_URL = os.environ.get(
        'CELERY_BROKER_URL', 
        'redis://default:saul123@lwcc8sss480ks4oc8gcgw4go:6379/0'  # Nombre del servicio en Coolify
    )
    print(f"[DEBUG] Entorno PRODUCCION detectado. Redis: {CELERY_BROKER_URL}")

import sys
sys.stdout.flush()

CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'django-db')
CELERY_CACHE_BACKEND = 'django-cache'

# Celery Task Settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos máximo por tarea
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# TIMEOUTS AGRESIVOS para evitar hangs al enviar tareas
CELERY_BROKER_CONNECTION_TIMEOUT = 3  # Solo 3 segundos para conectar
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'socket_timeout': 3,
    'socket_connect_timeout': 3,
    'socket_keepalive': True,
}

# Caché compartida para que Celery y Django (runserver) se vean
# En ambos entornos usamos Redis si está disponible
if IS_LOCAL:
    # Local: Intentar usar el mismo Redis que Celery si está configurado
    try:
        import redis
        # Usar la URL del broker configurada (que viene de env o default) la cual ya usa DB 1
        redis_url = CELERY_BROKER_URL.replace('/0', '/1') if '/0' in CELERY_BROKER_URL else CELERY_BROKER_URL
        
        # Test connection
        r = redis.from_url(redis_url, socket_connect_timeout=1)
        r.ping()
        # Si llega aquí, Redis está disponible
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': redis_url,
                'OPTIONS': {
                    'socket_timeout': 5,
                    'socket_connect_timeout': 5,
                    'retry_on_timeout': True,
                }
            }
        }
        print(f"[DEBUG] Cache: Redis conectado exitosamente en {redis_url}")
    except Exception as e:
        # Redis no disponible, usar memoria local
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'unique-snowflake',
            }
        }
        print(f"[DEBUG] Cache: LocMem (Redis no disponible en {CELERY_BROKER_URL}: {e})")
else:
    # Producción: LocMem por ahora para evitar crashes
    # Producción: Redis compartido
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': CELERY_BROKER_URL,
            'OPTIONS': {
                'socket_timeout': 5,
                'socket_connect_timeout': 5,
                'retry_on_timeout': True,
            }
        }
    }
    print(f"[DEBUG] Cache: Redis Produccion ({CELERY_BROKER_URL})")

sys.stdout.flush()

# Configuración adicional para producción
if not DEBUG:
    # En producción, usar configuración más robusta
    CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
    CELERY_BROKER_CONNECTION_RETRY = True
    CELERY_BROKER_CONNECTION_MAX_RETRIES = 10

# Configuración de Email para Desarrollo
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'notificaciones@energia.com'

# Configuración de autenticación
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/app/'

# AI / NLP Settings
OLLAMA_API_URL = os.environ.get('OLLAMA_API_URL', 'http://localhost:11434')


# Programación de tareas periódicas (Celery Beat)
CELERY_BEAT_SCHEDULE = {
    'sync-document-embeddings-every-minute': {
        'task': 'documentos.tasks.sync_document_embeddings',
        'schedule': 60.0,  # Revisa documentos nuevos cada minuto
    },
}
