# Generated by Django 5.2.3 on 2025-12-17 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='ubicacion_legacy',
            field=models.CharField(blank=True, help_text='Ubicación física del activo (Texto libre - Deprecado)', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_ubicaciones', to='activos.ubicacion')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.AlterField(
            model_name='activo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='Ubicación jerárquica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.ubicacion'),
        ),
    ]
