# Generated by Django 5.2.3 on 2025-12-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='activos',
            field=models.ManyToManyField(blank=True, help_text='Activos que se visualizan en este plano', related_name='planos', to='activos.activo'),
        ),
    ]
