# Generated by Django 5.2.3 on 2025-12-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_plano_activos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='imagen',
        ),
        migrations.AddField(
            model_name='plano',
            name='archivo',
            field=models.FileField(blank=True, help_text='Subir imagen o PDF del plano', null=True, upload_to='planos/'),
        ),
    ]
