# Generated by Django 5.2.3 on 2025-12-19 20:01

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0007_remove_plano_imagen_plano_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisorPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visores', to='activos.plano')),
            ],
            options={
                'verbose_name': 'Visor de Plano',
                'verbose_name_plural': 'Visores de Planos',
            },
        ),
        migrations.CreateModel(
            name='PinPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='Posición X en porcentaje (0-100)')),
                ('y', models.FloatField(help_text='Posición Y en porcentaje (0-100)')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('nota', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pines_planos', to='activos.activo')),
                ('visor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pines', to='activos.visorplano')),
            ],
            options={
                'verbose_name': 'Pin de Plano',
                'verbose_name_plural': 'Pines de Planos',
            },
        ),
    ]
