# Generated by Django 5.2.3 on 2025-12-19 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_visorplano_pinplano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinplano',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pinplano',
            name='x',
            field=models.FloatField(help_text='Posición X en píxeles absolutos'),
        ),
        migrations.AlterField(
            model_name='pinplano',
            name='y',
            field=models.FloatField(help_text='Posición Y en píxeles absolutos'),
        ),
        migrations.CreateModel(
            name='PinFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='pines/fotos/')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='activos.pinplano')),
            ],
            options={
                'verbose_name': 'Foto de Pin',
                'verbose_name_plural': 'Fotos de Pines',
            },
        ),
    ]
