# Generated by Django 5.2.3 on 2025-12-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0009_alter_pinplano_nota_alter_pinplano_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(default='location', help_text='Nombre del icono de Ionicons (ej: flash, water, construct, bulb)', max_length=50),
        ),
    ]
