# Generated by Django 5.2.3 on 2025-12-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0010_categoria_icono'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together={('nombre', 'padre')},
        ),
    ]
