# Generated by Django 5.2.7 on 2025-12-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_alter_ubicacion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización y programación'),
        ),
    ]
