# Generated by Django 5.2.7 on 2025-12-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0012_ubicacion_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('REPARACION', 'En Reparación'), ('OBSOLETO', 'Obsoleto/De Baja')], db_index=True, default='OPERATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='activo',
            name='serie',
            field=models.CharField(blank=True, db_index=True, help_text='Número de serie del fabricante', max_length=100, null=True),
        ),
    ]
