# Generated by Django 5.2.7 on 2025-12-22 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0013_alter_activo_creado_en_alter_activo_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='level',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_ubicaciones', to='activos.ubicacion'),
        ),
    ]
