# Generated by Django 5.2.7 on 2025-12-23 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0014_remove_ubicacion_level_remove_ubicacion_lft_and_more'),
        ('mantenimiento', '0017_remove_categoria_level_remove_categoria_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinplano',
            name='aviso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pines_planos', to='mantenimiento.aviso'),
        ),
    ]
