# Generated by Django 5.2.7 on 2025-12-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0015_pinplano_aviso'),
        ('mantenimiento', '0017_remove_categoria_level_remove_categoria_lft_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pinplano',
            constraint=models.UniqueConstraint(condition=models.Q(('activo__isnull', False)), fields=('visor', 'activo'), name='unique_activo_per_visor'),
        ),
    ]
