# Generated by Django 5.2.7 on 2025-12-23 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0016_pinplano_unique_activo_per_visor'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos', to='activos.categoria'),
        ),
    ]
