# Generated by Django 5.2.7 on 2025-12-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0017_modelo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='categoria',
        ),
    ]
