# Generated by Django 5.2.3 on 2025-12-29 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0018_remove_activo_categoria'),
        ('mantenimiento', '0020_remove_rutina_categoria_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='mantenimiento_categoria',
            field=models.ForeignKey(blank=True, help_text='Vincular con una categoría de mantenimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_activos', to='mantenimiento.categoria'),
        ),
    ]
