# Generated by Django 5.2.7 on 2025-12-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0019_categoria_mantenimiento_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='mantenimiento_categoria',
        ),
    ]
