# Generated by Django 5.2.7 on 2025-12-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0020_remove_categoria_mantenimiento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='codigo_interno',
            field=models.CharField(default='S/C', help_text='Código de inventario interno', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
