# Generated by Django 5.2.7 on 2025-12-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0021_alter_activo_codigo_interno'),
        ('documentos', '0002_documentofirmado_firma_auditoriafirmas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='documento',
            field=models.ForeignKey(blank=True, help_text='Documento que contiene el archivo del plano (usa la última revisión)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos', to='documentos.documento'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='archivo',
            field=models.FileField(blank=True, help_text="Archivo directo (usar 'documento' para control de versiones)", null=True, upload_to='planos/'),
        ),
    ]
