# Generated by Django 5.2.7 on 2025-12-29 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0022_add_documento_to_plano'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinplano',
            name='actividad',
            field=models.ForeignKey(blank=True, help_text='Actividad de proyecto ubicada en este punto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pines_planos', to='proyectos.actividad'),
        ),
    ]
