# Generated by Django 5.2.7 on 2025-12-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0023_pinplano_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('EDIFICIO', 'Edificio'), ('NIVEL', 'Nivel/Piso'), ('ESPACIO', 'Espacio/Área'), ('OTRO', 'Otro')], default='NIVEL', help_text='Tipo de ubicación', max_length=20),
        ),
    ]
