# Generated by Django 5.2.7 on 2026-01-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0025_categoria_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='imagen_archivo',
            field=models.ImageField(blank=True, help_text='Cargar imagen desde el equipo', null=True, upload_to='modelos_fotos/'),
        ),
        migrations.AddField(
            model_name='modelo',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='O pegar una URL externa de la imagen', max_length=500, null=True),
        ),
    ]
