# Generated by Django 5.2.7 on 2026-01-08 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0026_modelo_imagen_archivo_modelo_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='padre',
            field=models.ForeignKey(blank=True, help_text='Activo principal del cual este forma parte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes', to='activos.activo'),
        ),
    ]
