# Generated by Django 5.2.7 on 2026-01-09 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0027_activo_padre'),
        ('mantenimiento', '0033_pasoprocedimiento_rango_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Horímetro Motor, Presión Aceite', max_length=100)),
                ('codigo', models.CharField(blank=True, help_text='Código corto opcional', max_length=50, null=True)),
                ('unidad', models.CharField(help_text='Ej: Hrs, Bar, °C, PSI', max_length=20)),
                ('es_acumulativo', models.BooleanField(default=False, help_text='Si se marca, el valor se suma al anterior (ej: horímetro)')),
                ('valor_objetivo', models.FloatField(blank=True, help_text='Valor nominal o límite de operación', null=True)),
                ('tolerancia', models.FloatField(blank=True, help_text='Rango de desviación permitido', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_medicion', to='activos.activo')),
            ],
            options={
                'verbose_name': 'Punto de Medición',
                'verbose_name_plural': 'Puntos de Medición',
            },
        ),
        migrations.CreateModel(
            name='DocumentoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha_lectura', models.DateTimeField(blank=True, default=None, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_medicion', to='mantenimiento.ordentrabajo')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas_registradas', to=settings.AUTH_USER_MODEL)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='activos.puntomedicion')),
            ],
            options={
                'verbose_name': 'Documento de Medición',
                'verbose_name_plural': 'Documentos de Medición',
                'ordering': ['-fecha_lectura'],
            },
        ),
    ]
