# Generated by Django 5.2.7 on 2026-01-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0028_puntomedicion_documentomedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentomedicion',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_totales', to='activos.activo'),
        ),
    ]
