# Generated by Django 5.2.7 on 2026-01-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0029_documentomedicion_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('REPARACION', 'En Reparación'), ('FUERA_SERVICIO', 'Fuera de Servicio'), ('OBSOLETO', 'Obsoleto/De Baja')], db_index=True, default='OPERATIVO', max_length=20),
        ),
    ]
