# Generated by Django 5.2.7 on 2026-01-12 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0030_alter_activo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinplano',
            name='alto',
            field=models.FloatField(default=0, help_text='Alto del área en píxeles (0 para puntos)'),
        ),
        migrations.AddField(
            model_name='pinplano',
            name='ancho',
            field=models.FloatField(default=0, help_text='Ancho del área en píxeles (0 para puntos)'),
        ),
        migrations.AddField(
            model_name='pinplano',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='Ubicación vinculada a esta zona del plano', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pines_planos', to='activos.ubicacion'),
        ),
        migrations.AlterField(
            model_name='pinplano',
            name='x',
            field=models.FloatField(help_text='Posición X (o Left) en píxeles absolutos'),
        ),
        migrations.AlterField(
            model_name='pinplano',
            name='y',
            field=models.FloatField(help_text='Posición Y (o Top) en píxeles absolutos'),
        ),
    ]
