# Generated by Django 5.2.7 on 2026-01-13 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0031_pinplano_alto_pinplano_ancho_pinplano_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría asociada para rutinas de mantenimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='activos.categoria'),
        ),
    ]
