# Generated by Django 5.2.7 on 2026-01-14 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0032_ubicacion_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfamilias', to='activos.familia')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'unique_together': {('nombre', 'padre')},
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='familia',
            field=models.ForeignKey(blank=True, help_text='Clasificación por familia de equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.familia'),
        ),
    ]
