# Generated by Django 5.2.7 on 2026-01-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0033_familia_activo_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='referencia',
            field=models.CharField(blank=True, help_text='Referencia adicional', max_length=100, null=True),
        ),
    ]
