# Generated by Django 5.2.7 on 2026-01-14 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0034_activo_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='plano',
            field=models.ForeignKey(blank=True, help_text='Plano principal donde se ubica este activo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_principales', to='activos.plano'),
        ),
    ]
