# Generated by Django 5.2.7 on 2026-01-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0035_activo_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Nombre del activo o equipo', max_length=200),
        ),
    ]
