# Generated by Django 5.2.7 on 2026-01-21 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0036_alter_activo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='codigo_interno',
            field=models.CharField(help_text='Código de inventario interno (Solo números)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'El código interno debe contener solo números.')]),
        ),
    ]
