# Generated by Django 5.2.7 on 2026-01-21 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0037_alter_activo_codigo_interno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de esta importación', max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('INICIANDO', 'Iniciando'), ('PROCESANDO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('REVERTIDO', 'Revertido'), ('ERROR', 'Error')], default='INICIANDO', max_length=20)),
                ('total_filas', models.IntegerField(default=0)),
                ('filas_nuevas', models.IntegerField(default=0)),
                ('filas_actualizadas', models.IntegerField(default=0)),
                ('filas_omitidas', models.IntegerField(default=0)),
                ('filas_error', models.IntegerField(default=0)),
                ('ids_creados', models.TextField(blank=True, help_text='IDs de activos creados en esta sesión (JSON)')),
                ('detalles_error', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Importación',
                'verbose_name_plural': 'Registros de Importaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
