# Generated by Django 5.2.7 on 2026-01-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0038_registroimportacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, verbose_name='No. de Doc'),
        ),
        migrations.AddField(
            model_name='plano',
            name='tipo_plano',
            field=models.CharField(blank=True, choices=[('PROYECTO_EJECUTIVO', 'Proyecto Ejecutivo'), ('AS_BUILT', 'Plano As Built'), ('TALLER', 'Plano Taller')], max_length=30, null=True, verbose_name='Tipo de Plano'),
        ),
        migrations.AddField(
            model_name='plano',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('padre', models.ForeignKey(blank=True, help_text='Disciplina de nivel superior', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdisciplinas', to='activos.disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='plano',
            name='disciplina',
            field=models.ForeignKey(blank=True, help_text='Disciplina y Subdisciplina vinculada al plano', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos', to='activos.disciplina'),
        ),
    ]
