# Generated by Django 5.2.7 on 2026-01-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0039_plano_numero_documento_plano_tipo_plano_plano_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
