# Generated by Django 5.2.7 on 2026-01-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0040_alter_disciplina_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
