# Generated by Django 5.2.7 on 2026-01-22 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0041_alter_plano_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos', to='activos.ubicacion'),
        ),
    ]
