# Generated by Django 5.2.7 on 2026-01-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0042_alter_plano_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='epc',
            field=models.CharField(blank=True, db_index=True, help_text='Código EPC (Electrónic Product Code) de la etiqueta RFID (Alfanumérico)', max_length=100, null=True, unique=True),
        ),
    ]
