# Generated by Django 5.2.7 on 2026-01-23 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0043_activo_epc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BienAfecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(db_index=True, help_text='Código patrimonial permanente', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Descripción del bien afecto', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('familia', models.ForeignKey(blank=True, help_text='Clasificación por familia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes_afectos', to='activos.familia')),
                ('responsable', models.ForeignKey(blank=True, help_text='Persona responsable del bien afecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes_afectos_responsable', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(blank=True, help_text='Ubicación actual del bien afecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes_afectos', to='activos.ubicacion')),
            ],
            options={
                'verbose_name': 'Bien Afecto',
                'verbose_name_plural': 'Bienes Afectos',
                'ordering': ['codigo_interno'],
            },
        ),
        migrations.CreateModel(
            name='HistorialBienAfecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, help_text='Fecha de asignación del activo')),
                ('fecha_baja', models.DateTimeField(blank=True, help_text='Fecha de baja del activo (vacío = activo actual)', null=True)),
                ('motivo_baja', models.CharField(blank=True, choices=[('REEMPLAZO', 'Reemplazo por nuevo equipo'), ('OBSOLETO', 'Equipo obsoleto'), ('DAÑADO', 'Equipo dañado irreparable'), ('ROBO', 'Robo o extravío'), ('TRANSFERENCIA', 'Transferencia a otro bien afecto'), ('OTRO', 'Otro motivo')], help_text='Razón de la baja', max_length=20, null=True)),
                ('observaciones_baja', models.TextField(blank=True, help_text='Detalles adicionales sobre la baja')),
                ('activo', models.ForeignKey(help_text='Activo físico asignado', on_delete=django.db.models.deletion.CASCADE, related_name='historial_bien_afecto', to='activos.activo')),
                ('bien_afecto', models.ForeignKey(help_text='Bien afecto al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='activos.bienafecto')),
                ('usuario_alta', models.ForeignKey(help_text='Usuario que dio de alta el activo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_bien_afecto', to=settings.AUTH_USER_MODEL)),
                ('usuario_baja', models.ForeignKey(blank=True, help_text='Usuario que dio de baja el activo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_bien_afecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Bien Afecto',
                'verbose_name_plural': 'Historial de Bienes Afectos',
                'ordering': ['-fecha_alta'],
                'indexes': [models.Index(fields=['bien_afecto', '-fecha_alta'], name='activos_his_bien_af_8601f1_idx'), models.Index(fields=['activo'], name='activos_his_activo__d7d182_idx')],
            },
        ),
    ]
