# Generated by Django 5.2.7 on 2026-01-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0044_bienafecto_historialbienafecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroimportacion',
            name='resumen_columnas',
            field=models.JSONField(blank=True, help_text='Resumen de qué columnas se actualizaron y cuántas veces', null=True),
        ),
    ]
