# Generated by Django 5.2.7 on 2026-02-05 16:52

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0045_registroimportacion_resumen_columnas'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienafecto',
            name='plano',
            field=models.ForeignKey(blank=True, help_text='Plano actual del bien afecto (Heredado del activo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes_afectos', to='activos.plano'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=core.storage.MinIOStorage(), upload_to='activos_fotos/'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='imagen_archivo',
            field=models.ImageField(blank=True, help_text='Cargar imagen desde el equipo', null=True, storage=core.storage.MinIOStorage(), upload_to='modelos_fotos/'),
        ),
        migrations.AlterField(
            model_name='pinfoto',
            name='imagen',
            field=models.ImageField(storage=core.storage.MinIOStorage(), upload_to='pines/fotos/'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='archivo',
            field=models.FileField(blank=True, help_text="Archivo directo (usar 'documento' para control de versiones)", null=True, storage=core.storage.MinIOStorage(), upload_to='planos/'),
        ),
    ]
