# Generated by Django 5.2.7 on 2026-02-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0046_bienafecto_plano_alter_activo_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSubmittal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField(blank=True, null=True, verbose_name='Recibido')),
                ('codigo_ficha', models.CharField(db_index=True, max_length=100, verbose_name='Código Ficha')),
                ('codigo_submittal', models.CharField(db_index=True, max_length=100, verbose_name='Código Submittal')),
                ('num_submittal', models.IntegerField(blank=True, null=True, verbose_name='No. Submittal')),
                ('fecha_revisado_epc', models.DateField(blank=True, null=True, verbose_name='Revisado EPC')),
                ('comentario_epc', models.TextField(blank=True, null=True, verbose_name='Comentario EPC')),
                ('observacion_epc', models.TextField(blank=True, null=True, verbose_name='Observación de EPC')),
                ('fecha_envio_sup', models.DateField(blank=True, null=True, verbose_name='Fecha Envío Sup.')),
                ('transmision_epc_sup', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transmisión EPC / SUP')),
                ('transmision_sup_epc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transmisión SUP. / EPC')),
                ('fecha_recepcion_sup', models.DateField(blank=True, null=True, verbose_name='Fecha Recepción Sup')),
                ('dictamen_sup', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dictamen SUP')),
                ('observacion_sup', models.TextField(blank=True, null=True, verbose_name='Observación SUP.')),
                ('enviado_constructora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enviado a Constructora')),
                ('fecha_envio_ccc', models.DateField(blank=True, null=True, verbose_name='Fecha Envío CCC (1)')),
                ('estatus_aconex', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estatus Aconex')),
                ('estatus_ccg', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estatus en CCG (ICCE)')),
                ('carpeta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Carpeta')),
                ('transmitido_a_ccc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transmitido a CCC')),
                ('fecha_envio_ccc_final', models.DateField(blank=True, null=True, verbose_name='Fecha Envío CCC (2)')),
            ],
            options={
                'verbose_name': 'Control de Submittal',
                'verbose_name_plural': 'Control de Submittals',
                'ordering': ['-fecha_recibido', 'codigo_ficha'],
            },
        ),
    ]
