# Generated by Django 5.2.7 on 2026-02-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0047_controlsubmittal'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsubmittal',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='controlsubmittal',
            name='especialidad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='controlsubmittal',
            name='trab_act_n',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TRAB-ACT-N'),
        ),
        migrations.AlterField(
            model_name='controlsubmittal',
            name='dictamen_sup',
            field=models.CharField(blank=True, choices=[('ADECUADO', 'Adecuado'), ('ADECUADO_CON_NOTAS', 'Adecuado con Notas'), ('NO_ADECUADO', 'No Adecuado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=100, null=True, verbose_name='Dictamen SUP'),
        ),
        migrations.AlterField(
            model_name='controlsubmittal',
            name='num_submittal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Submittal'),
        ),
    ]
