# Generated by Django 5.2.7 on 2026-02-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0048_controlsubmittal_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroimportacion',
            name='tipo',
            field=models.CharField(default='Activos', help_text='Tipo de datos (Activos, Planos, Submittals, etc.)', max_length=100),
        ),
    ]
