# Generated by Django 5.1.15 on 2026-02-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0049_registroimportacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('EDIFICIO', 'Edificio'), ('NIVEL', 'Nivel/Piso'), ('ESPACIO', 'Espacio/Área'), ('BODEGA', 'Bodega'), ('OTRO', 'Otro')], default='NIVEL', help_text='Tipo de ubicación', max_length=20),
        ),
    ]
