# Generated by Django 5.1.15 on 2026-02-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0050_alter_ubicacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='es_almacen',
            field=models.BooleanField(default=False, help_text='Marcar si esta ubicación funciona como bodega/almacén de materiales'),
        ),
    ]
