# Generated by Django 5.2.7 on 2026-03-04 16:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0051_ubicacion_es_almacen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAltaBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja')], max_length=10, verbose_name='Tipo de Documento')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número de Documento')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Documento')),
                ('motivo', models.TextField(verbose_name='Motivo / Justificación')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_altabaja_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('elaborado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_altabaja_elaborados', to=settings.AUTH_USER_MODEL, verbose_name='Elaborado por')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_altabaja_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Documento de Alta/Baja',
                'verbose_name_plural': 'Documentos de Alta/Baja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemAltaBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, help_text='Observación específica para este activo', max_length=500)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_altabaja', to='activos.activo')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='activos.documentoaltabaja')),
            ],
            options={
                'verbose_name': 'Activo en Documento',
                'verbose_name_plural': 'Activos en Documento',
                'unique_together': {('documento', 'activo')},
            },
        ),
    ]
