# Generated by Django 5.2.7 on 2026-03-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0052_documentoaltabaja_itemaltabaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoaltabaja',
            name='numero',
            field=models.CharField(blank=True, help_text='Se genera automáticamente', max_length=50, unique=True, verbose_name='Número de Documento'),
        ),
    ]
