# Generated by Django 5.2.7 on 2026-03-04 17:15

import activos.models.documento_altabaja
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0053_alter_documentoaltabaja_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAltaBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=activos.models.documento_altabaja.altabaja_upload_path, verbose_name='Archivo')),
                ('comentario', models.CharField(blank=True, max_length=500, verbose_name='Comentario')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='activos.documentoaltabaja')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['subido_en'],
            },
        ),
    ]
