# Generated by Django 5.2.7 on 2026-03-05 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0054_archivoaltabaja'),
        ('core', '0015_perfilusuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, help_text='Unidad de medida por defecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_asociados', to='core.unidadmedida'),
        ),
    ]
