# Generated by Django 5.2.7 on 2026-03-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0055_modelo_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='precio_promedio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario promedio para presupuestos', max_digits=12),
        ),
    ]
