# Generated by Django 5.2.7 on 2026-03-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0056_modelo_precio_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del modelo', null=True),
        ),
    ]
