# Generated by Django 5.2.7 on 2026-03-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0057_modelo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='precio_promedio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Precio unitario promedio para presupuestos', max_digits=12, null=True),
        ),
    ]
