# Generated by Django 5.2.12 on 2026-03-08 22:11

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0058_alter_modelo_precio_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='archivo_3d',
            field=models.FileField(blank=True, help_text='Archivo de modelo 3D específico para este activo (formato .glb). Si se deja en blanco, usará el del modelo asociado (si tiene uno).', null=True, storage=core.storage.MinIOStorage(), upload_to='activos_3d/'),
        ),
        migrations.AddField(
            model_name='modelo',
            name='archivo_3d',
            field=models.FileField(blank=True, help_text='Archivo de modelo 3D (formato .glb o .gltf)', null=True, storage=core.storage.MinIOStorage(), upload_to='modelos_3d/'),
        ),
    ]
