# Generated by Django 5.2.12 on 2026-03-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0059_activo_archivo_3d_modelo_archivo_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='puntos_3d_data',
            field=models.JSONField(blank=True, default=list, help_text='Datos de hotspots/pines en formato JSON'),
        ),
        migrations.AddField(
            model_name='modelo',
            name='puntos_3d_data',
            field=models.JSONField(blank=True, default=list, help_text='Datos de hotspots/pines en formato JSON'),
        ),
    ]
