# Generated by Django 5.2.12 on 2026-03-09 10:21

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0060_activo_puntos_3d_data_modelo_puntos_3d_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='archivo_3d',
            field=models.FileField(blank=True, help_text='Escaneo 3D o modelo de la ubicación (.glb)', null=True, storage=core.storage.MinIOStorage(), upload_to='ubicaciones_3d/'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='puntos_3d_data',
            field=models.JSONField(blank=True, default=list, help_text='Pines/Hotspots 3D en esta ubicación'),
        ),
    ]
