# Generated by Django 5.2.12 on 2026-04-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0061_fix_puntos_3d_data_modelo_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='codigo_qr',
            field=models.CharField(blank=True, help_text='Código físico de la ubicación (ej. UBC000000001)', max_length=50, null=True, unique=True),
        ),
    ]
