# Generated by Django 5.2.12 on 2026-04-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0062_ubicacion_codigo_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaEtiquetaQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Molde')),
                ('ancho_cm', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Ancho (cm)')),
                ('alto_cm', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Alto (cm)')),
                ('prefijo_defecto', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Prefijo Frecuente')),
                ('padding_digitos', models.IntegerField(default=5, verbose_name='Dígitos de Padding')),
                ('header_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto Cabecera')),
                ('footer_mode', models.CharField(choices=[('secuencial', 'Secuencial Automático'), ('vacio', 'Vacío')], default='secuencial', max_length=50, verbose_name='Modo de Pie')),
                ('font_size', models.IntegerField(default=10, verbose_name='Tamaño Fuente (pt)')),
                ('qr_scale', models.IntegerField(default=80, verbose_name='Escala QR (%)')),
                ('border_thickness', models.IntegerField(default=1, verbose_name='Grosor Borde (px)')),
                ('compiled_html', models.TextField(blank=True, null=True, verbose_name='HTML Compilado Interno')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla QR',
                'verbose_name_plural': 'Plantillas QR',
                'ordering': ['-creado_en'],
            },
        ),
    ]
