# Generated by Django 5.2.12 on 2026-04-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0063_plantillaetiquetaqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaetiquetaqr',
            name='margin_top',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Margen Superior (cm)'),
        ),
    ]
