# Generated by Django 5.2.12 on 2026-04-15 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0065_fotoubicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('filtros', models.JSONField(default=dict, help_text='JSON con los filtros aplicados')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas_activos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vista Guardada',
                'verbose_name_plural': 'Vistas Guardadas',
                'ordering': ['-creada_en'],
            },
        ),
    ]
