# Generated by Django 5.2.12 on 2026-04-16 02:23

import core.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0066_vistaguardada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del reporte', max_length=200)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, storage=core.storage.MinIOStorage(), upload_to='reportes_generados/')),
                ('detalles_error', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-creado_en'],
            },
        ),
    ]
