# Generated by Django 5.2.12 on 2026-04-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0067_reportegenerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportegenerado',
            name='task_id',
            field=models.CharField(blank=True, help_text='ID de la tarea en Celery', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
