# Generated by Django 5.2.12 on 2026-04-22 23:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0068_reportegenerado_task_id_alter_reportegenerado_estado'),
        ('mantenimiento', '0067_ordentrabajo_equipo_parado_alter_ordentrabajo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duracion_horas', models.FloatField(default=0, help_text='Duración calculada en horas')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('hallazgos', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_paradas', to='activos.activo')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='mantenimiento.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Historial de Parada',
                'verbose_name_plural': 'Historial de Paradas',
                'ordering': ['-inicio'],
            },
        ),
    ]
