# Generated by Django 5.2.12 on 2026-04-22 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0069_downtimeactivo'),
        ('mantenimiento', '0068_aviso_equipo_parado_aviso_fecha_fin_parada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimeactivo',
            name='aviso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='mantenimiento.aviso'),
        ),
        migrations.AlterField(
            model_name='downtimeactivo',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='mantenimiento.ordentrabajo'),
        ),
    ]
