# Generated by Django 5.2.12 on 2026-05-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0070_downtimeactivo_aviso_and_more'),
        ('core', '0020_seed_elementoapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Capacidad, Voltaje, Color', max_length=100)),
                ('tipo_dato', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('BOOLEANO', 'Sí/No (Booleano)'), ('OPCIONES', 'Lista de Opciones')], default='TEXTO', max_length=20)),
                ('opciones', models.CharField(blank=True, help_text="Opciones separadas por coma si eligió 'Lista de Opciones'. Ej: Rojo,Verde,Azul", max_length=255, null=True)),
                ('requerido', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='activos.categoria')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidadmedida')),
            ],
            options={
                'verbose_name': 'Característica de Categoría',
                'verbose_name_plural': 'Características de Categoría',
            },
        ),
        migrations.CreateModel(
            name='ValorCaracteristicaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=255, null=True)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.caracteristicacategoria')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_caracteristicas', to='activos.modelo')),
            ],
            options={
                'verbose_name': 'Valor de Característica',
                'verbose_name_plural': 'Valores de Características',
                'unique_together': {('modelo', 'caracteristica')},
            },
        ),
    ]
