# Generated by Django 5.2.12 on 2026-05-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0071_caracteristicacategoria_valorcaracteristicamodelo'),
        ('inventarios', '0022_fotodespacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='materiales_compatibles',
            field=models.ManyToManyField(blank=True, related_name='modelos_compatibles_m2m', through='inventarios.CompatibilidadMaterial', to='inventarios.material'),
        ),
    ]
