# Generated by Django 5.2.12 on 2026-05-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0072_modelo_materiales_compatibles'),
        ('documentos', '0033_alter_documento_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='documentos',
            field=models.ManyToManyField(blank=True, help_text='Biblioteca de documentos asociados a este modelo', related_name='modelos', to='documentos.documento'),
        ),
    ]
