# Generated by Django 6.0.6 on 2026-07-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0073_modelo_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='ancho_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ancho del área (solo para Bodegas)', max_digits=8, null=True, verbose_name='Ancho (m)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='largo_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largo del área (solo para Bodegas)', max_digits=8, null=True, verbose_name='Largo (m)'),
        ),
    ]
