# Generated by Django 6.0.6 on 2026-07-16 04:56

import django.db.models.deletion
import portalsub.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalsub', '0001_initial'),
        ('presupuestos', '0066_refactor_area_manual_en_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FACTURA', 'Factura'), ('REPORTE', 'Reporte'), ('ESTIMACION', 'Estimación'), ('RESPALDO', 'Documento de Respaldo'), ('GARANTIA', 'Garantía'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de documento')),
                ('archivo', models.FileField(upload_to=portalsub.models.oc_document_path, verbose_name='Archivo')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('es_valido', models.BooleanField(default=True, verbose_name='Válido')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_contratista', to='presupuestos.ordencompra', verbose_name='Orden de Compra')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento de OC',
                'verbose_name_plural': 'Documentos de Órdenes de Compra',
                'ordering': ['-creado_en'],
            },
        ),
    ]
