# Generated by Django 6.0.6 on 2026-07-16 05:04

import portalsub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalsub', '0002_documentoordencompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoordencompra',
            name='archivo',
            field=models.FileField(max_length=500, upload_to=portalsub.models.oc_document_path, verbose_name='Archivo'),
        ),
    ]
