# Generated by Django 6.0.6 on 2026-07-16 05:08

import django.db.models.deletion
import portalsub.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0086_tecnicopuesto_telefono_and_more'),
        ('portalsub', '0003_alter_documentoordencompra_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CV', 'CV Actualizado'), ('CERTIFICACION', 'Certificaciones'), ('DNI', 'Copia del DNI'), ('ANTECEDENTES', 'Antecedentes Penales'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de documento')),
                ('archivo', models.FileField(max_length=500, upload_to=portalsub.models.personal_document_path, verbose_name='Archivo')),
                ('es_valido', models.BooleanField(default=True, verbose_name='Válido')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='mantenimiento.tecnicopuesto')),
            ],
            options={
                'verbose_name': 'Documento del Personal',
                'verbose_name_plural': 'Documentos del Personal',
                'ordering': ['tipo'],
                'unique_together': {('tecnico', 'tipo')},
            },
        ),
    ]
