# Generated by Django 6.0.6 on 2026-07-16 05:25

import django.db.models.deletion
import portalsub.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0086_tecnicopuesto_telefono_and_more'),
        ('portalsub', '0004_documentopersonal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del entregable')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_maestro', models.BooleanField(default=False, help_text='RTN, Acta, Contrato — no requieren mes específico', verbose_name='Documento maestro (sin mes)')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Entregable',
                'verbose_name_plural': 'Tipos de Entregables',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja'), ('REINGRESO', 'Reingreso'), ('CAMBIO_PUESTO', 'Cambio de Puesto'), ('DOCUMENTO', 'Documento Subido'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de evento')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='mantenimiento.tecnicopuesto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Historial del Personal',
                'verbose_name_plural': 'Historial del Personal',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EntregableContratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses_aplicacion', models.JSONField(blank=True, default=list, help_text='Ej: [1,3,5,7,9,11] para bimensual. Vacío/null = todos los meses', null=True, verbose_name='Meses de aplicación')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables_config', to='mantenimiento.empresa')),
                ('tipo_entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_por_empresa', to='portalsub.tipoentregable')),
            ],
            options={
                'verbose_name': 'Entregable del Contratista',
                'verbose_name_plural': 'Entregables del Contratista',
                'unique_together': {('empresa', 'tipo_entregable')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoEntregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mes')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('archivo', models.FileField(max_length=500, upload_to=portalsub.models.entregable_path, verbose_name='Archivo')),
                ('es_valido', models.BooleanField(default=True, verbose_name='Válido')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_entregables', to='mantenimiento.empresa')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_subidos', to='portalsub.tipoentregable')),
            ],
            options={
                'verbose_name': 'Documento de Entregable',
                'verbose_name_plural': 'Documentos de Entregables',
                'ordering': ['tipo_entregable', 'mes'],
                'unique_together': {('empresa', 'tipo_entregable', 'mes', 'anio')},
            },
        ),
    ]
