# Generated by Django 6.0.6 on 2026-07-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalsub', '0006_seed_entregables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoentregable',
            name='es_maestro',
        ),
    ]
