# Generated by Django 6.0.6 on 2026-08-17 03:16

import portalsub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalsub', '0009_tipodocumentopersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoentregable',
            name='no_aplica',
            field=models.BooleanField(default=False, verbose_name='No Aplica'),
        ),
        migrations.AlterField(
            model_name='documentoentregable',
            name='archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=portalsub.models.entregable_path, verbose_name='Archivo'),
        ),
    ]
