# Generated by Django 6.0.6 on 2026-08-17 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalsub', '0010_add_no_aplica_documento_entregable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('ENVIADO', 'Expediente Enviado'), ('APROBADO', 'Expediente Aprobado'), ('RECHAZADO', 'Expediente Rechazado'), ('REENVIADO', 'Expediente Reenviado'), ('CREADO', 'Expediente Creado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='portalsub.expedientemensual')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Expediente',
                'verbose_name_plural': 'Historial de Expedientes',
                'ordering': ['-fecha'],
            },
        ),
    ]
